using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
// ⚠ 与拆分前 `ServiceProbe/Program.cs` 顶部的 using-alias **逐字一致**：
//   `GF` = `RawGamutFit`（原 Program.cs:21）。拆出后必须自带，
//   否则 `GF.M2020To709` 等引用全部 CS0103（拆分时实测踩过）。
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
// ⚠ 2026-10-05 审查补：`engine`(`ProbeEngineAb`) / `simdswitch`(`ProbeSimdSwitch`) 两个 mode
//   当初**漏搬**（组表声明了却没人实现 ⇒ 独立跑 0 条断言；旧宿主是 35/0 与 28/0）
//   ⇒ 现补搬。它们用到原宿主顶部的这些别名，**逐字照抄**（漏写即 CS0103；本次实测踩过）。
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using ST = FfmpegGui.Models.ColorStrategy;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Engine
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // GamutFit.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> EngineGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class EngineGroup
    {
        private static void ProbeEngineAb()
        {
            var RCP = typeof(FfmpegGui.Services.ColorMapping.RawColorPipeline);
            var ff = FfmpegGui.Services.AppSettingsService.Current.FfmpegPath;
            string dir = "tests/output/validate/engineab";
            Directory.CreateDirectory(dir);

            // A/B 只在“两侧意图相同”时才有意义：legacy 不读 --color-tone-map（它用 --tonemap-curve），
            // 所以 HDR→SDR 的 tonemap 用例**不进本表**（否则比的是“一边映射一边不映射”）。
            var cases = new (string name, string src, string cs)[]
            {
                ("sRGB→P3",  "tests/output/sources/src_8bit.png", "Display P3"),
                ("P3→sRGB",  "tests/output/results/color/a2_srgb_p3.png", "sRGB"),
            };
            foreach (var cse in cases)
            {
                string src = cse.src;
                if (!File.Exists(src)) { Check(false, $"{cse.name} 缺素材 {src}（先跑 generate-sources.ps1 + ensure-fixtures.ps1）"); continue; }
                foreach (var fmt in new[] { "png", "jpg", "webp", "tiff" })
                {
                    var o = new FfmpegGui.Models.FfmpegOptions
                    {
                        Format = fmt, ColorSpace = cse.cs,
                        ColorStrategy = FfmpegGui.Models.ColorStrategy.Recommended, BitDepth = 8,
                    };
                    var intent = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(o, src, out var why);
                    if (intent == null) { Check(false, $"{cse.name}/{fmt} 装配失败：{why}"); continue; }
                    var plan = CE.Plan(intent);
                    if (!plan.IsOk) { Check(false, $"{cse.name}/{fmt} 计划拒绝：{plan.Reason}"); continue; }

                    string ext = fmt == "tiff" ? "tif" : fmt;
                    // 诊断行：把“执行入参”原样打出来（像素错时第一需要知道的是 spec 而不是产物）
                    {
                        var sp0 = plan.ToSpec();
                        string mts = sp0.Matrix == null ? "恒等"
                            : $"[{sp0.Matrix[0]:F4},{sp0.Matrix[1]:F4},{sp0.Matrix[2]:F4}]";
                        Console.WriteLine($"  · {cse.name}/{fmt} spec: src={sp0.SrcCurve.Name} dst={sp0.DstCurve.Name} "
                            + $"scale={sp0.LinearScale:F4} 矩阵={mts} tone={(sp0.Tone?.ToString() ?? "无")} "
                            + $"outBit={plan.OutBitDepth} action={plan.Action} loss={plan.ColorLoss}");
                    }
                    string engOut = $"{dir}/eng_{cse.name}_{fmt}.{ext}";
                    if (File.Exists(engOut)) File.Delete(engOut);
                    try
                    {
                        var st = FfmpegGui.Services.ColorMapping.RawColorPipeline.TransformFileAsync(
                            src, engOut, plan.ToSpec(), plan, null, default, 2).GetAwaiter().GetResult();
                        Check(File.Exists(engOut) && new FileInfo(engOut).Length > 200,
                            $"{cse.name}/{fmt} 引擎产出 {new FileInfo(engOut).Length}B（{st.Width}x{st.Height}, 变换 {st.ProcessMs}ms）");
                    }
                    catch (Exception ex) { Check(false, $"{cse.name}/{fmt} 引擎异常：{ex.Message}"); continue; }

                    // 与 legacy 对比：同一目标走 ffmpeg 色彩链，逐像素算 PSNR（peak=1.0，两侧同域）
                    if (string.IsNullOrWhiteSpace(ff) || !File.Exists(ff)) { Check(false, $"{cse.name}/{fmt} 无 ffmpeg，A/B 不可运行"); continue; }
                    string legOut = $"{dir}/leg_{cse.name}_{fmt}.{ext}";
                    if (File.Exists(legOut)) File.Delete(legOut);
                    var args = FfmpegGui.Services.FfmpegCommandBuilder.BuildArguments(o, src, legOut);
                    using (var pr = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(
                        ff, args) { RedirectStandardError = true, UseShellExecute = false })!)
                    { pr.StandardError.ReadToEnd(); pr.WaitForExit(120_000); }
                    if (!File.Exists(legOut)) { Check(false, $"{cse.name}/{fmt} legacy 未产出（A/B 无法对比）"); continue; }

                    try
                    {
                        var (w1, h1) = FfmpegGui.Services.ColorMapping.RawColorPipeline.ProbeSizeAsync(engOut).GetAwaiter().GetResult();
                        var (w2, h2) = FfmpegGui.Services.ColorMapping.RawColorPipeline.ProbeSizeAsync(legOut).GetAwaiter().GetResult();
                        if (w1 != w2 || h1 != h2) { Check(false, $"{cse.name}/{fmt} A/B 尺寸不一致 {w1}x{h1} vs {w2}x{h2}"); continue; }
                        var a = FfmpegGui.Services.ColorMapping.RawColorPipeline.DecodeToRgb48Async(engOut, w1, h1).GetAwaiter().GetResult();
                        var b = FfmpegGui.Services.ColorMapping.RawColorPipeline.DecodeToRgb48Async(legOut, w1, h1).GetAwaiter().GetResult();
                        double mse = 0, meanA = 0, meanB = 0; long n = 0;
                        for (int i = 0; i + 1 < a.Length && i + 1 < b.Length; i += 2)
                        {
                            double x = a[i] | (a[i + 1] << 8), y = b[i] | (b[i + 1] << 8);
                            double d = (x - y) / 65535.0;
                            mse += d * d; meanA += x; meanB += y; n++;
                        }
                        mse /= Math.Max(1, n); meanA /= Math.Max(1, n); meanB /= Math.Max(1, n);
                        double psnr = mse > 0 ? 10 * Math.Log10(1.0 / mse) : 99;
                        // 阈值按容器性质分开定：**无损容器**（png/tiff）两路应几乎同值；
                        // **损失编码容器**（jpg/webp）两侧各自做了 YUV 量化/DCT，差异来自编码器而非色彩，
                        // 拿同一个 40dB 去卡它们只会测到“编码器噪声”，反而遮住真正的色彩偏差。
                        // 所以对损失容器只要求“亮度不偏”（均值差）+ 一个宽松下限。
                        bool lossyContainer = fmt is "jpg" or "webp";
                        double thr = lossyContainer ? 20.0 : 40.0;
                        Console.WriteLine($"  {cse.name}/{fmt} 源={plan.Src?.Name} 目标={plan.Dst?.Name} "
                            + $"psnr={psnr:F2}dB engMean={meanA / 65535.0:F4} legMean={meanB / 65535.0:F4}"
                            + (lossyContainer ? "（损失编码容器：两侧量化差异不计入色彩门禁）" : ""));
                        Check(psnr >= thr, $"{cse.name}/{fmt} 引擎 vs legacy PSNR≥{thr}dB（实 {psnr:F2}，{n} 样本）");
                        // 色彩不偏的真正判据（与容器是否损失无关）：两路均值必须在 2% 内
                        Check(System.Math.Abs(meanA - meanB) / 65535.0 < 0.02,
                              $"{cse.name}/{fmt} 引擎与 legacy 平均亮度一致（差 {System.Math.Abs(meanA - meanB) / 65535.0:F4}）");
                        // 亮度不变量：纯色域映射不应把图压成全黑或抛成全白
                        Check(meanA / 65535.0 > 0.02 && meanA / 65535.0 < 0.98,
                            $"{cse.name}/{fmt} 引擎产物亮度合理（engMean={meanA / 65535.0:F4}）");
                    }
                    catch (Exception ex) { Check(false, $"{cse.name}/{fmt} A/B 对比异常：{ex.Message}"); }
                }
            }

            // ═════════════════ #29：`--color-709-curve` 的**端到端**行为锁（真产物字节）═════════════════
            // 与 `contract` 的 C7b 分工：C7b 在**内核**上量口径差（无外部依赖、上下界可推演），
            // 本段把它跑成**真产物**（ffmpeg 解码 → H1 变换 → PNG 编码 → 再解码对拍）——
            // 缺陷当初的表象就是"两条 CLI 命令产物逐字节相同"（2026-09-26 实测四格 × {std,zimg} 全同 md5），
            // 只有真产物层能证明"用户这次拿到的确实是另一个东西"。
            // 格子必须结构上落在 H1：Display P3 ⊄ BT.709 ⇒ 开 GMO ⇒ needsGmo ⇒ 后端与口径无关
            // （若落进 H2，比的就是 zscale 而不是我们的出口曲线，本段就测不到要测的东西 ⇒ 下面先断言前提）。
            {
                string p3Src = "tests/output/results/color/a2_srgb_p3.png";
                if (!File.Exists(p3Src) || string.IsNullOrWhiteSpace(ff) || !File.Exists(ff))
                {
                    Check(false, $"#29 端到端缺前提（素材 {p3Src} 或 ffmpeg）⇒ 本段未验证，不是通过");
                }
                else
                {
                    var o709 = new FfmpegGui.Models.FfmpegOptions
                    {
                        Format = "png", ColorSpace = "BT.709", ColorStrategy = FfmpegGui.Models.ColorStrategy.Recommended,
                        BitDepth = 8, ColorGamutMap = "on",
                        Quality = FfmpegGui.Models.FfmpegOptions.GetDefaultQuality("png"),
                    };
                    var byCurve = new System.Collections.Generic.Dictionary<string, string>();
                    bool premOk = true;
                    foreach (var curve in new[] { "std", "zimg" })
                    {
                        o709.Color709Curve = curve;
                        var it709 = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(o709, p3Src, out var why709);
                        if (it709 == null) { Check(false, $"#29 端到端 {curve} 意图装配失败：{why709}"); premOk = false; break; }
                        var pl709 = CE.Plan(it709);
                        if (!pl709.IsOk) { Check(false, $"#29 端到端 {curve} 计划拒绝：{pl709.Reason}"); premOk = false; break; }
                        if (pl709.Backend != CB.InProcess)
                        { Check(false, $"#29 端到端前提：{curve} 必须落在 H1（实为 {pl709.Backend}）{pl709.Reason}"); premOk = false; break; }
                        string op = $"{dir}/_709_{curve}.png";
                        if (File.Exists(op)) File.Delete(op);
                        try
                        {
                            FfmpegGui.Services.ColorMapping.RawColorPipeline.TransformFileAsync(
                                p3Src, op, pl709.ToSpec(), pl709, null, default, 2).GetAwaiter().GetResult();
                            byCurve[curve] = op;
                        }
                        catch (Exception ex) { Check(false, $"#29 端到端 {curve} 引擎异常：{ex.Message}"); premOk = false; break; }
                    }
                    if (premOk && byCurve.Count == 2)
                    {
                        var bStd = File.ReadAllBytes(byCurve["std"]);
                        var bZim = File.ReadAllBytes(byCurve["zimg"]);
                        Check(!bStd.AsSpan().SequenceEqual(bZim),
                            $"#29 端到端：std 与 zimg 的真产物必须**逐字节不同**（std {bStd.Length}B / zimg {bZim.Length}B）"
                          + "⇒ 缺陷原貌就是两者同 md5（静默无效参数）");

                        // 差多少：解码回 rgb48（8bit 产物 ⇒ 码值 = 8bit×257），换算成 8bit LSB 再比上下界。
                        var (ws, hs) = FfmpegGui.Services.ColorMapping.RawColorPipeline
                            .ProbeSizeAsync(byCurve["std"]).GetAwaiter().GetResult();
                        var pxStd = FfmpegGui.Services.ColorMapping.RawColorPipeline
                            .DecodeToRgb48Async(byCurve["std"], ws, hs).GetAwaiter().GetResult();
                        var pxZim = FfmpegGui.Services.ColorMapping.RawColorPipeline
                            .DecodeToRgb48Async(byCurve["zimg"], ws, hs).GetAwaiter().GetResult();
                        int maxE2e = 0; long sumE2e = 0; long cntE2e = 0;
                        for (int i = 0; i + 1 < pxStd.Length && i + 1 < pxZim.Length; i += 2)
                        {
                            int d = Math.Abs((pxStd[i] | (pxStd[i + 1] << 8)) - (pxZim[i] | (pxZim[i + 1] << 8))) / 257;
                            if (d > maxE2e) maxE2e = d;
                            sumE2e += d; cntE2e++;
                        }
                        double meanE2e = (double)sumE2e / Math.Max(1, cntE2e);
                        Check(maxE2e >= 24 && maxE2e <= 32 && meanE2e >= 2.0,
                            $"#29 端到端差量级：max={maxE2e} LSB@8bit（界 24–32，理论 27.2）mean={meanE2e:F2}"
                          + $"（{ws}x{hs}，{cntE2e} 样本）⇒ 差的是口径量级，不是压缩/元数据噪声");

                        // 反向：同口径重跑必须逐字节相同（把"差"归因到口径，而不是抖动/RNG/时间戳）
                        string op2 = $"{dir}/_709_std_rerun.png";
                        if (File.Exists(op2)) File.Delete(op2);
                        o709.Color709Curve = "std";
                        var it2 = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(o709, p3Src, out var why2);
                        var pl2 = CE.Plan(it2!);
                        FfmpegGui.Services.ColorMapping.RawColorPipeline.TransformFileAsync(
                            p3Src, op2, pl2.ToSpec(), pl2, null, default, 2).GetAwaiter().GetResult();
                        Check(File.ReadAllBytes(op2).AsSpan().SequenceEqual(bStd),
                            "#29 端到端反向：std 重跑产物必须逐字节相同（确定性；差异只应来自口径本身）");
                    }
                }
            }
        }
    }
}
