using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
// ⚠ 与拆分前 `ServiceProbe/Program.cs` 顶部的 using-alias **逐字一致**：
//   `GF` = `RawGamutFit`（原 Program.cs:21）。拆出后必须自带，
//   否则 `GF.M2020To709` 等引用全部 CS0103（拆分时实测踩过）。
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
// ⚠ 2026-10-05 审查补：`engine`(`ProbeEngineAb`) / `simdswitch`(`ProbeSimdSwitch`) 两个 mode
//   当初**漏搬**（组表声明了却没人实现 ⇒ 独立跑 0 条断言；旧宿主是 35/0 与 28/0）
//   ⇒ 现补搬。它们用到原宿主顶部的这些别名，**逐字照抄**（漏写即 CS0103；本次实测踩过）。
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using ST = FfmpegGui.Models.ColorStrategy;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Engine
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // GamutFit.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> EngineGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class EngineGroup
    {
        private static void ProbeGamutFit()
        {
            // ── 1. 常量交叉锁：本内核的 M2020To709 == 产品注册表里同一对矩阵 ──
            //     两处独立维护同一对矩阵 ⇒ 抄错一处端到端测不出来。
            var reg = ColorSpaceRegistry.LinearMatrixBetweenPrimaries("bt2020", "bt709");
            Check(reg != null, "gamutfit: 注册表提供 bt2020→bt709 矩阵");
            if (reg != null)
            {
                double err = 0;
                for (int i = 0; i < 3; i++)
                    for (int j = 0; j < 3; j++)
                        err = Math.Max(err, Math.Abs(GF.M2020To709[i, j] - reg[i * 3 + j]));
                Console.WriteLine($"GF.M2020To709 vs ColorSpaceRegistry maxErr={err:E2}");
                Check(err <= 1e-15, "gamutfit: M2020To709 派生自注册表（≤1e-15，非后备常数）");
            }
            // 派生值仍须落在 BT.2080 发布值附近（拦住"注册表整条错"这种情形）
            {
                var pub = new[]
                {
                    1.660491, -0.587641, -0.072850,
                   -0.124550,  1.132901, -0.008350,
                   -0.018151, -0.100581,  1.118731,
                };
                double e = 0;
                for (int i = 0; i < 3; i++)
                    for (int j = 0; j < 3; j++)
                        e = Math.Max(e, Math.Abs(GF.M2020To709[i, j] - pub[i * 3 + j]));
                Console.WriteLine($"GF.M2020To709 vs BT.2080 发布值 maxErr={e:E2}");
                Check(e <= 2e-3, "gamutfit: M2020To709 与 BT.2080 发布值一致（≤2e-3）");
            }

            // ── 2. 正反矩阵互逆 ──
            double idErr = 0;
            for (int i = 0; i < 3; i++)
                for (int j = 0; j < 3; j++)
                {
                    double s = 0;
                    for (int k = 0; k < 3; k++) s += GF.M2020To709[i, k] * GF.M709To2020[k, j];
                    idErr = Math.Max(idErr, Math.Abs(s - (i == j ? 1.0 : 0.0)));
                }
            Console.WriteLine($"M2020To709 x M709To2020 与单位阵偏差 max={idErr:E2}");
            Check(idErr <= 1e-12, "gamutfit: 正反矩阵互逆（≤1e-12）");

            // ── 3. 阈值形态（方向必须 fail-closed）──
            Check(GF.FracThreshold > 0 && GF.FracThreshold <= 0.01,
                  $"gamutfit: FracThreshold in (0,1%]（实 {GF.FracThreshold}）");
            Check(GF.NegThreshold < 0, $"gamutfit: NegThreshold < 0（实 {GF.NegThreshold}）");
            Check(GF.FloorFactor > 0 && GF.FloorFactor <= 1,
                  $"gamutfit: FloorFactor in (0,1]（实 {GF.FloorFactor}）");
            // ⚠ 容差必须比真实越界量级小至少 2 个数量级（否则会掩盖真越界）
            Check(GF.EpsNeg > 0 && GF.EpsNeg <= 1e-3,
                  $"gamutfit: EpsNeg in (0,1e-3]（实 {GF.EpsNeg}）");

            // ── 4. 行为：合成数据 ──
            static byte[] Rgb48(int n, Func<int, (int r, int g, int b)> f)
            {
                var a = new byte[n * 6];
                for (int i = 0; i < n; i++)
                {
                    var (r, g, b) = f(i);
                    a[i * 6 + 0] = (byte)(r & 0xFF); a[i * 6 + 1] = (byte)((r >> 8) & 0xFF);
                    a[i * 6 + 2] = (byte)(g & 0xFF); a[i * 6 + 3] = (byte)((g >> 8) & 0xFF);
                    a[i * 6 + 4] = (byte)(b & 0xFF); a[i * 6 + 5] = (byte)((b >> 8) & 0xFF);
                }
                return a;
            }
            const int N = 4096;

            // (a) 中性灰 ⇒ bt709 里仍是灰（无负值）⇒ 判"装得下"
            var gray = GF.MeasureRgb48(Rgb48(N, _ => (30000, 30000, 30000)), N, 1);
            Console.WriteLine($"(a) 中性灰: measurable={gray.Measurable} frac={gray.FracOutOf709:E2} maxNeg={gray.MaxNegExcursion:E2} fits={gray.FitsIn709}");
            Check(gray.Measurable && gray.FitsIn709, "gamutfit(a): 中性灰 ⇒ 装在 bt709 内");

            // (b) 纯 bt2020 红 ⇒ bt709 的 G/B 变负（≈ −0.1246）⇒ 判"超出"
            var red = GF.MeasureRgb48(Rgb48(N, _ => (65535, 0, 0)), N, 1);
            Console.WriteLine($"(b) bt2020 纯红: measurable={red.Measurable} frac={red.FracOutOf709:E2} maxNeg={red.MaxNegExcursion:F4} fits={red.FitsIn709}");
            Check(red.Measurable && !red.FitsIn709, "gamutfit(b): bt2020 纯红 ⇒ 超出 bt709");

            // (c) 全黑 ⇒ 地板以上像素为 0 ⇒ 必须"测不出"（**不得**返回"装得下"）
            var black = GF.MeasureRgb48(Rgb48(N, _ => (0, 0, 0)), N, 1);
            Console.WriteLine($"(c) 全黑: measurable={black.Measurable} reason={black.Reason}");
            Check(!black.Measurable, "gamutfit(c): 全黑 ⇒ 三态「测不出」（不得当成装得下）");
            Check(!black.FitsIn709, "gamutfit(c): 测不出时 FitsIn709 必须为 false（保守）");

            // (d) bt709 纯红（换算成 bt2020 表示）⇒ 恰在边界上 ⇒ 判"装得下"
            //     ⚠ 这条钉的是 EpsNeg：去掉容差 ⇒ 边界色被整片计成越界 ⇒ 本条转红。
            var inRed = GF.MeasureRgb48(Rgb48(N, _ => (41123, 4528, 1075)), N, 1);
            Console.WriteLine($"(d) bt709 纯红(bt2020 表示): measurable={inRed.Measurable} frac={inRed.FracOutOf709:E2} maxNeg={inRed.MaxNegExcursion:F6} fits={inRed.FitsIn709}");
            Check(inRed.Measurable && inRed.FitsIn709, "gamutfit(d): bt709 边界内的红 ⇒ 装在 bt709 内（EpsNeg 生效）");

            // (e) **地板负控**：99% 中性灰 + 1% 极暗的越界红 ⇒ 越界像素全在地板下 ⇒ 仍判"装得下"
            //     ⚠ 变异验证：把 FloorFactor 置 0 ⇒ 该暗红像素被计入 ⇒ 本条必须转红。
            var floorCase = GF.MeasureRgb48(
                Rgb48(N, i => (i % 100 == 0) ? (200, 0, 0) : (30000, 30000, 30000)), N, 1);
            Console.WriteLine($"(e) 灰+暗越界红: measurable={floorCase.Measurable} floor={floorCase.LuminanceFloor:F5} frac={floorCase.FracOutOf709:E2} fits={floorCase.FitsIn709}");
            Check(floorCase.Measurable && floorCase.FitsIn709,
                  "gamutfit(e): 越界像素全在亮度地板以下 ⇒ 判「装得下」（地板负控）");

            // ══ (g) **小样本**：99.9 分位不得退化成 max ══════════════════════════════════
            //  ⚠⚠ 2026-10-05 新增（补一个**真实的缺陷**：此前全仓无任何小样本覆盖）。
            //  缺陷：旧写法 `need = ceil(sampled * 0.999)` 在 `sampled <= 999` 时**恒等于 sampled**
            //    ⇒ 直方图累积到该 bin 的那一项就是**最亮样本** ⇒ `yP999 = max(Y)`，
            //      而它**不是** 99.9 分位。地板随 `0.25 × max` 被抬飞 ⇒ 真实越界像素落进地板下
            //      ⇒ `FracOutOf709` 被压到阈值以下 ⇒ **误判「装得下 bt709」**（静默乐观）。
            //  可达性：抽样步长 = `pixels / 1_000_000` ⇒ 任何 **< 1000 像素**的输入都落进该区间
            //    （缩略图 / 裁剪图 / 测试夹具），而画面里只要有一个高光坏点就会触发。
            //  本条的构造（**刻意做成"最小可判"**——即夹具必须**真能区分**新旧行为）：
            //    · 小样本（100 像素，落在退化区间 `sampled <= 999` 内）
            //    · 1 个**极亮白**（max → 旧实现的地板 = 0.25 × 1.0 = **0.25**）
            //    · 其余 99 个是**中等亮度的越界红**（≈0.5 满量程 ⇒ Y ≈ 0.1314）
            //      ⚠ 亮度必须选得**足够暗**：早先我用满量程纯红（Y=0.2627 > 0.25），
            //        它在**退化地板之上**照样被计入 ⇒ 新旧行为**读数相同**、断言抓不到缺陷
            //        （我第一版就是这么写的，变异验证时发现主断言仍绿 ⇒ 夹具无效，已改正）。
            //  ⇒ 正确地板 ≈ 0.25 × 0.1314 ≈ 0.0329 < 0.1314 ⇒ 越界像素在地板之上 ⇒ 判「超出」✅
            //  ⇒ 退化地板 = 0.25 > 0.1314      ⇒ 越界像素全落地板下 ⇒ 判「装得下」❌（旧行为）
            //  变异验证：删掉 `if (need >= sampled) need = sampled - 1;` ⇒ 本条**必须转红**（已实测）。
            const int SmallN = 100;
            const int MidRed = 32768;   // ≈0.5 满量程；Y ≈ 0.1314 < 0.25 ⇒ 能区分新旧地板
            var smallSample = GF.MeasureRgb48(
                Rgb48(SmallN, i => (i == 0) ? (65535, 65535, 65535) : (MidRed, 0, 0)), SmallN, 1);
            Console.WriteLine($"(g) 小样本({SmallN})+极亮白: measurable={smallSample.Measurable} " +
                              $"floor={smallSample.LuminanceFloor:F5} frac={smallSample.FracOutOf709:F4} " +
                              $"maxNeg={smallSample.MaxNegExcursion:F4} fits={smallSample.FitsIn709}");
            Check(smallSample.Measurable, "gamutfit(g): 小样本仍须「可测」（不得因样本少就报测不出）");
            Check(!smallSample.FitsIn709,
                  "gamutfit(g): 小样本下 99.9 分位**不得退化成 max** ⇒ 越界像素必须仍被判「超出」"
                  + "（旧实现地板=max×0.25=0.25 > 该像素的 Y≈0.13 ⇒ 全部落地板下 ⇒ 误判装得下）");
            // 两条反控：分别钉住"地板没被抬飞"与"确实是那些像素在起作用"
            Check(smallSample.LuminanceFloor < 0.10,
                  $"gamutfit(g) 反控1: 小样本地板须显著低于极亮白（实 {smallSample.LuminanceFloor:F5}；"
                  + "旧实现的退化地板恒为 0.25）");
            Check(smallSample.FracOutOf709 > GF.FracThreshold,
                  $"gamutfit(g) 反控2: 越界占比须超过判据阈值（实 {smallSample.FracOutOf709:F4} "
                  + $"vs FracThreshold={GF.FracThreshold}）⇒ 本条不是『恰好』过的");

            // (f) 输入长度不符 ⇒ 必须"测不出"（不得把截断数据当有效样本）
            var bad = GF.MeasureRgb48(new byte[N * 6 - 6], N, 1);
            Check(!bad.Measurable, "gamutfit(f): 长度不符 ⇒ 三态「测不出」");
        }
    }
}
