using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
// ⚠ 与拆分前 `ServiceProbe/Program.cs` 顶部的 using-alias **逐字一致**：
//   `GF` = `RawGamutFit`（原 Program.cs:21）。拆出后必须自带，
//   否则 `GF.M2020To709` 等引用全部 CS0103（拆分时实测踩过）。
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
// ⚠ 2026-10-05 审查补：`engine`(`ProbeEngineAb`) / `simdswitch`(`ProbeSimdSwitch`) 两个 mode
//   当初**漏搬**（组表声明了却没人实现 ⇒ 独立跑 0 条断言；旧宿主是 35/0 与 28/0）
//   ⇒ 现补搬。它们用到原宿主顶部的这些别名，**逐字照抄**（漏写即 CS0103；本次实测踩过）。
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using ST = FfmpegGui.Models.ColorStrategy;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Engine
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // GamutFit.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> EngineGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class EngineGroup
    {
        private static void ProbeGamut(string[] args)
        {
            if (args.Length < 2) { Console.WriteLine("usage: ServiceProbe gamut <jpeg> [expectedToken]"); Harness.FailOnly(); return; }
            var got = GainMapDecoder.DetectBasePrimaries(args[1]);
            Console.WriteLine($"base_primaries={got ?? "(null→sRGB惯例)"}");
            Check(got != null, "底图 ICC 可读出原色（已附 ICC）");
            if (args.Length >= 3)
                Check(string.Equals(got, args[2], StringComparison.OrdinalIgnoreCase), $"底图原色 == {args[2]}（实际 {got ?? "null"}）");
        }
    }
}
