using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Color
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // ColorGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> ColorGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class ColorGroup
    {
        private static void ProbeColorMathAgainstZimg()
        {
            // token → 9 项行主序（与 LinearMatrixBetweenPrimaries 同形：out[r] = Σ m[r*3+k]·in[k]）
            //   ⚠ 每个数组都过了一道独立校验：**三行之和必须各为 1**（白→白，与白点无关）——
            //     第一版这里有 4 个 token 因为平面序重排写错，正是这条校验逐个抓出来的。
            var zimg = new (string Tok, double[] M)[]
            {
                ("bt709",     new[] { 1.0, 0.0, 0.0,  0.0, 1.0, 0.0,  0.0, 0.0, 1.0 }),
                ("bt470m",    new[] { 1.48616, -0.40355, -0.08260,  -0.02510, 0.95402, 0.07108,  -0.02722, -0.04410, 1.07132 }),
                ("bt470bg",   new[] { 1.04404, -0.04404, 0.0,  0.0, 1.0, 0.0,  0.0, 0.01179, 0.98821 }),
                ("smpte170m", new[] { 0.93954, 0.05018, 0.01028,  0.01777, 0.96579, 0.01643,  -0.00162, -0.00437, 1.00599 }),
                ("smpte240m", new[] { 0.93954, 0.05018, 0.01028,  0.01777, 0.96579, 0.01643,  -0.00162, -0.00437, 1.00599 }),
                ("film",      new[] { 1.34618, -0.33920, -0.00698,  -0.04735, 1.06605, -0.01870,  -0.02166, -0.06131, 1.08298 }),
                ("bt2020",    new[] { 1.66049, -0.58764, -0.07285,  -0.12455, 1.13290, -0.00835,  -0.01815, -0.10058, 1.11873 }),
                ("smpte428",  new[] { 3.14666, -1.66646, -0.48019,  -0.99552, 1.95576, 0.03976,  0.06359, -0.21456, 1.15097 }),
                ("smpte431",  new[] { 1.15752, -0.15496, -0.00255,  -0.04150, 1.04557, -0.00407,  -0.01805, -0.07858, 1.09663 }),
                ("smpte432",  new[] { 1.22494, -0.22494, 0.0,  -0.04206, 1.04206, 0.0,  -0.01964, -0.07864, 1.09827 }),
                ("jedec-p22", new[] { 1.02525, -0.02655, 0.00130,  0.01939, 0.94803, 0.03258,  -0.00177, -0.00144, 1.00321 }),
            };
            // ── 容差**分档**（P4 收口：原先一个 1e-3 把两种性质完全不同的上限混在一起）──
            //   实测残差（2026-09-26，本 mode 自己打出来的 maxErr，不是估的）：
            //     bt2020 1.14e-6 · bt470bg 3.38e-6 · smpte432 3.95e-6 · smpte170m 4.91e-6
            //     · smpte240m 4.91e-6 · jedec-p22 4.92e-6  ⇒ **A 档**
            //     bt470m 1.76e-4 · smpte431 2.36e-4        ⇒ **B 档**
            //   A 档 = 1e-5：锚 A（zimg）的读数只有 5 位小数 ⇒ 单元素舍入地板 5e-6，
            //     实测最大 4.92e-6 正贴着它 ⇒ 再严就是在抄 zimg 的舍入，而不是在验本仓的数学。
            //   B 档 = 5e-4：这两格的残差**不来自原色抄错**，而来自"白点只给到有限位数"这一事实——
            //     `bt470m` 用 Illuminant C (0.3101,0.3162)、`smpte431` 用影院白 (0.314,0.351)，
            //     而色适应矩阵对白点位数远比原色敏感（残差集中在对角元 1,1 / 反对角 0,2 正是适应项）。
            //     ⇒ 要收紧 B 档，先按权威源取更高精度的白点常数、再用同一锚复测；
            //       **不许**把 5e-4 调到 1e-3 去"吸收"，也不许拿 A 档去判它（那会立刻假红）。
            //   ⚠ 没登记进本表的 token ⇒ 判红并点名"不知道该用哪档"：默认走宽松档就是这条锁漏齿的方式。
            var tolTier = new System.Collections.Generic.Dictionary<string, (double Tol, string Why)>
            {
                ["bt2020"] = (1e-5, "A 档=锚读数舍入地板 5e-6"),
                ["bt470bg"] = (1e-5, "A 档=锚读数舍入地板 5e-6"),
                ["smpte432"] = (1e-5, "A 档=锚读数舍入地板 5e-6"),
                ["smpte170m"] = (1e-5, "A 档=锚读数舍入地板 5e-6"),
                ["smpte240m"] = (1e-5, "A 档=锚读数舍入地板 5e-6"),
                ["jedec-p22"] = (1e-5, "A 档=锚读数舍入地板 5e-6"),
                ["bt470m"] = (5e-4, "B 档=白点位数上限（Illuminant C）"),
                ["smpte431"] = (5e-4, "B 档=白点位数上限（影院白 0.314,0.351）"),
            };

            foreach (var (tok, expect) in zimg)
            {
                var got = ColorSpaceRegistry.LinearMatrixBetweenPrimaries(tok, "bt709");
                if (tok == "bt709")
                {
                    // 同 token 的契约就是 null（=不映射）；把它当"缺矩阵"判红是我第一版的错向断言。
                    Check(got == null, "bt709→bt709 必须 null（同原色 = 不映射，绝不生成单位阵去乘一遍）");
                    continue;
                }
                if (got == null)
                {
                    // null 只有在「本仓**故意**不收录」时才正确，且必须逐个点名理由：
                    //   film     = 未收录（lcms 有原色但残差 2.1e-4，精度不足以填表）
                    //   smpte428 = **xy 参数化表达不了**（H.273 蓝原色 y=0 ⇒ 归一化退化）⇒ 只能不收录
                    // 其余 token 拿到 null 一律红：那说明表被删漏了，而不是"设计如此"。
                    var whyNull = new System.Collections.Generic.Dictionary<string, string>
                    {
                        ["film"] = "未收录（精度不足）",
                        ["smpte428"] = "xy 不可表达 ⇒ 故意不收录，不许挑一组「看着像」的补回来",
                    };
                    Check(whyNull.ContainsKey(tok),
                        $"{tok}→bt709 返回 null ⇒ 只允许出现在「故意不收录」名单里（名单与理由：film=精度不足、smpte428=xy 表达不了）");
                    continue;
                }
                double err = 0; int worst = -1;
                for (int i = 0; i < 9; i++)
                {
                    double d = Math.Abs(got[i] - expect[i]);
                    if (d > err) { err = d; worst = i; }
                }
                Console.WriteLine($"  {tok,-11} maxErr={err:E2} (位置 {worst / 3},{worst % 3}) " +
                    $"本仓=[{string.Join(",", got.Select(v => v.ToString("0.0000", System.Globalization.CultureInfo.InvariantCulture)))}] " +
                    $"zimg=[{string.Join(",", expect.Select(v => v.ToString("0.0000", System.Globalization.CultureInfo.InvariantCulture)))}]");
                if (!tolTier.TryGetValue(tok, out var tier))
                {
                    // 新加 token 时**必须**同时登记档位与依据 ⇒ 否则"这条到底该多严"会变成隐含默认值。
                    Check(false, $"{tok}→bt709 未登记容差档位 ⇒ 不判（实测 maxErr={err:E2}；请补 tolTier 与依据）");
                    continue;
                }
                Check(err <= tier.Tol,
                    $"{tok}→bt709 与 zimg 参照逐元素一致（≤{tier.Tol:0.######}，{tier.Why}）实差 {err:E2}");
            }

            // 表内重复项的直接后果：名义上不同的标准被判"同原色"⇒ 跳映射（用户明令禁止的那类静默）
            var dup = new System.Collections.Generic.List<string>();
            for (int i = 0; i < zimg.Length; i++)
                for (int j = i + 1; j < zimg.Length; j++)
                {
                    var a = ColorSpaceRegistry.LinearMatrixBetweenPrimaries(zimg[i].Tok, "bt709");
                    var b = ColorSpaceRegistry.LinearMatrixBetweenPrimaries(zimg[j].Tok, "bt709");
                    if (a == null || b == null) continue;
                    bool same = true;
                    for (int k = 0; k < 9; k++) if (Math.Abs(a[k] - b[k]) > 1e-9) { same = false; break; }
                    if (same) dup.Add($"{zimg[i].Tok}≡{zimg[j].Tok}");
                }
            Console.WriteLine("  本仓把不同标准算成**同一矩阵**的 token 对：" + (dup.Count == 0 ? "无" : string.Join(" ", dup)));
            // 重复**不是自动违法**：zimg 自己也让 smpte170m 与 smpte240m 同原色（差异只在传递函数），
            // 所以这里要的是「白名单之外不得重复」——白名单每一对都必须有外部锚的理由，
            // 加对进白名单等同于改判据，必须写清楚是谁、凭什么加进来的（别用"看着一样"当理由）。
            var allowedDup = new System.Collections.Generic.Dictionary<string, string>
            {
                ["smpte170m≡smpte240m"] = "两锚同判：lcms chrm 与 zimg 矩阵都给出同一组原色，差异只在 trc/matrix",
            };
            var badDup = dup.Where(x => !allowedDup.ContainsKey(x)).ToList();
            Check(dup.Count > 0 && badDup.Count == 0,
                $"同矩阵对全部落在白名单内（实得 {dup.Count} 对，白名单外 {badDup.Count} 对：{string.Join(" ", badDup)}）");
        }
    }
}
