using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Color
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // ColorGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> ColorGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class ColorGroup
    {
        private static void ProbeCurve()
        {
            void Anch(string what, double got, double want, double tol)
            {
                Console.WriteLine($"  {what,-34} got={got:F6} want={want:F6} err={Math.Abs(got - want):E1}");
                Check(Math.Abs(got - want) <= tol, $"{what} 锚点（≤{tol:g2}）");
            }
            // 锚点值写成**标准定义式**自算，而不是抄录小数（本探针曾因抄错小数把正确实现判为 FAIL）
            Anch("sRGB ToLinear(0.5)", TC.Srgb.ToLinear(0.5), Math.Pow((0.5 + 0.055) / 1.055, 2.4), 1e-9);
            Anch("BT.709 ToLinear(0.5)", TC.Bt709.ToLinear(0.5), Math.Pow((0.5 + 0.099) / 1.099, 1 / 0.45), 1e-9);
            // 趾段：sRGB EOTF 为 L = V/12.92（不是 ×12.92）；BT.709 为 L = V/4.5。c = 1/斜率。
            Anch("sRGB 趾段 ToLinear(0.03)", TC.Srgb.ToLinear(0.03), 0.03 / 12.92, 1e-9);
            Anch("BT.709 趾段 ToLinear(0.05)", TC.Bt709.ToLinear(0.05), 0.05 / 4.5, 1e-9);
            Anch("gamma2.2 ToLinear(0.5)", TC.Gamma22.ToLinear(0.5), Math.Pow(0.5, 2.2), 1e-9);
            Anch("gamma2.6 ToLinear(0.5)", TC.Gamma26.ToLinear(0.5), Math.Pow(0.5, 2.6), 1e-9);
            Anch("ProPhoto ToLinear(0.5)", TC.ProPhoto.ToLinear(0.5), Math.Pow(0.5, 1.8), 1e-9);
            Anch("ProPhoto 趾段 ToLinear(0.03)", TC.ProPhoto.ToLinear(0.03), 0.03 / 16.0, 1e-12);
            Anch("ProPhoto 趾段连续(拐点 d)", TC.ProPhoto.ToLinear(TC.ProPhoto.D), TC.ProPhoto.D / 16.0, 1e-12);
            // ⚠️ PQ 绝对锚点：码值必须是**精确解**，容差必须**紧到能抓住常数错误**。
            //    旧锚点用 0.5799 / 0.7516（4 位小数）+ 容差 1 / 3 —— 这两个数都是**不精确的码值**：
            //    203 nits 处 4 位小数的量化误差就有 ±1.4 nits，而 m1 常数写错（2610→2615，差 0.19%）
            //    在 203 nits 处只造成 ~1.1 nits 偏差，**正好藏在容差里** —— 这是该错误长期存活的原因之一。
            //    现码值经 **zimg 实测核对**（ffmpeg -vf "zscale=tin=smpte2084:t=linear:npl=10000"，
            //    16-bit 量化地板 ±0.04 nits）：0.580694 → 203.25 nits、0.751812 → 999.77 nits、
            //    0.5 → 92.32 nits ⇒ 203 nits 的 PQ 码值是 **0.5807** 而不是 0.5799（后者仅 201.5 nits）。
            Anch("PQ EOTF(0.5) nits", TC.Pq.ToLinear(0.5) * 10000.0, 92.28, 0.5);
            Anch("PQ EOTF(0.580694) nits(=203)", TC.Pq.ToLinear(0.580694) * 10000.0, 203.0, 0.5);
            Anch("PQ EOTF(0.751812) nits(=1000)", TC.Pq.ToLinear(0.751812) * 10000.0, 1000.0, 1.0);
            Anch("HLG EOTF(0.5)=拐点 1/12", TC.Hlg.ToLinear(0.5), 1.0 / 12.0, 1e-6);
            Anch("HLG EOTF(0.2)=V^2/3", TC.Hlg.ToLinear(0.2), 0.04 / 3.0, 1e-9);
            Anch("Linear ToLinear(0.37)", TC.Linear.ToLinear(0.37), 0.37, 0.0);

            // 互逆自洽：17 个采样点往返
            var curves = new[] { TC.Srgb, TC.Bt709, TC.Gamma22, TC.Gamma28, TC.ProPhoto, TC.Gamma18,
                                 TC.Gamma26, TC.Smpte240M, TC.Pq, TC.Hlg };
            foreach (var cv in curves)
            {
                double worst = 0;
                for (int i = 0; i <= 16; i++)
                {
                    double x = i / 16.0;
                    worst = Math.Max(worst, Math.Abs(cv.FromLinear(cv.ToLinear(x)) - x));
                }
                Check(worst <= 1e-6, $"{cv.Name} 往返互逆（max err={worst:E2}）");
            }

            // 单调性 + 表生成
            foreach (var cv in new[] { TC.Srgb, TC.Bt709, TC.ProPhoto, TC.Pq, TC.Hlg, TC.Gamma26 })
            {
                var t = cv.BuildEotfTable8();
                bool mono = t[0] <= t[1];
                for (int i = 2; i < 256; i++) mono &= t[i] > t[i - 1];
                Check(mono && Math.Abs(t[255] - 1.0f) < 2e-6f, $"{cv.Name} 8bit 表单调且白点=1.0");
            }

            // 与现有生产内核一致（统一性：引擎必须与 SimdPixelOps 的 sRGB 一致）
            double worstSrgb = 0;
            for (int i = 0; i <= 255; i += 17)
                worstSrgb = Math.Max(worstSrgb, Math.Abs(TC.Srgb.ToLinear(i / 255.0)
                    - FfmpegGui.Services.SimdPixelOps.SrgbToLinearScalar((float)(i / 255.0))));
            Check(worstSrgb <= 1e-5, $"引擎 sRGB 曲线与 SimdPixelOps 一致（max={worstSrgb:E2}）");

            // 与生产 SIMD 内核的 PQ 一致（统一性护栏：同一曲线只允许一份真值，否则两处会分叉）
            double worstPq = 0;
            foreach (double v in new[] { 0.0, 0.01, 0.1, 0.25, 0.5, 0.5799, 0.7516, 0.9, 1.0 })
            {
                worstPq = Math.Max(worstPq, Math.Abs(TC.Pq.ToLinear(v) - FfmpegGui.Services.SimdPixelOps.PqEotfScalar((float)v)));
                worstPq = Math.Max(worstPq, Math.Abs(TC.Pq.FromLinear(v) - FfmpegGui.Services.SimdPixelOps.PqOetfScalar((float)v)));
            }
            Check(worstPq <= 2e-5, $"引擎 PQ 与 SimdPixelOps 双向一致（max={worstPq:E2}，float 参考实现含 MathF 误差）");

            // 查询接口
            Check(TC.ForCicpTransfer("bt470m")!.Value.G == 2.2, "CICP bt470m → gamma2.2");
            Check(TC.ForCicpTransfer("iec61966-2-1")!.Value.Equivalent(TC.Srgb), "CICP iec61966-2-1 → sRGB");
            Check(TC.ForCicpTransfer("prophoto") == null, "未知 CICP token → null（不猜）");
            Check(TC.ForSourceTransfer("gamma1.8")!.Value.G == 1.8, "源名 gamma1.8 → 1.8");
            Check(TC.Srgb.CicpToken == "iec61966-2-1" && TC.ProPhoto.CicpToken == null,
                "CICP 可命名性标记正确（ProPhoto 不可命名）");
            Check(TC.Pq.CicpToken == "smpte2084" && TC.Hlg.CicpToken == "arib-std-b67", "HDR 曲线 CICP 标记");

            // ── #29：BT.709 的 **zimg 实现形态**（`--color-709-curve zimg` 的出口曲线）锚点 ──
            // 这条曲线存在的唯一理由 = 复刻历史产物；它**不是** BT.709 的定义式，两者差到肉眼可见
            // （见下方 16bit 最大差锚点）。所以它必须同时满足：
            //   ① 数学上是纯 γ(1/2.4)（无 α、无线性趾）；② 不被 CICP token 查询命中（默认口径永远是定义式）；
            //   ③ 与定义式的差**量级可断言**（不是"差不多"也不是"等价写法"）。
            Anch("Bt709Zimg ToLinear(0.5)", TC.Bt709Zimg.ToLinear(0.5), Math.Pow(0.5, 2.4), 1e-12);
            Anch("Bt709Zimg FromLinear(0.5)", TC.Bt709Zimg.FromLinear(0.5), Math.Pow(0.5, 1.0 / 2.4), 1e-12);
            Check(TC.Bt709Zimg.CicpToken == null && !TC.Bt709Zimg.HasToeSegment
                  && !TC.Bt709Zimg.HasItuRoundingKink && !TC.Bt709Zimg.Equivalent(TC.Bt709),
                  $"Bt709Zimg 不可 CICP 命名且无趾段（实 token={TC.Bt709Zimg.CicpToken ?? "null"} 趾={TC.Bt709Zimg.HasToeSegment}）"
                + "⇒ 它只描述像素，不冒充标准里的 bt709");
            Check(TC.ForCicpTransfer("bt709")!.Value.Equivalent(TC.Bt709),
                "CICP bt709 仍解析为定义式（zimg 形态不得变成 token 的默认解读，否则 std 口径被静默替换）");
            {
                double maxD = 0, sumD = 0;
                const int samples = 65536;
                for (int i = 0; i < samples; i++)
                {
                    double l = i / (samples - 1.0);
                    double d = Math.Abs(TC.Bt709.FromLinear(l) - TC.Bt709Zimg.FromLinear(l));
                    if (d > maxD) maxD = d;
                    sumD += d;
                }
                // 实测锚点：定义式与纯 γ(1/2.4) 的编码差最大 6986/65535（linear≈0.017），
                // 均值 3059/65535；zscale=t=bt709 的实测值 7231 与之差 245 ≈ 1 LSB@8bit 的量化地板。
                Check(maxD * 65535 >= 6900 && maxD * 65535 <= 7100 && sumD / samples * 65535 >= 2900
                      && sumD / samples * 65535 <= 3200,
                    $"两条 BT.709 口径的差可看见：max={maxD * 65535:F0} LSB@16bit（={maxD * 255:F1} LSB@8bit）"
                  + $" mean={sumD / samples * 65535:F0}（界 6900–7100 / 2900–3200）");
            }
        }
    }
}
