using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Color
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // ColorGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> ColorGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class ColorGroup
    {
        private static void ProbeIccName()
        {
            var expect = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["sRGB"] = "sRGB", ["Display P3"] = "Display P3",
                ["ProPhoto RGB"] = "ProPhoto RGB", ["BT.2020"] = "Rec.2020",
                // ❗ Adobe RGB / ColorMatch RGB 的**自身原色在 CICP 里没有 token**（iccgen 只能按 token 生成），
                //   而 registry 对它们的 Out* 就是“归一到 BT.2020”⇒ 这条路径生成出的**本来就是 BT.2020 ICC**。
                //   所以这里必须期望 Rec.2020（期望“Adobe RGB”才是错的，不要为了绿而改断言）。
                //   真正携带 Adobe RGB 原色的 ICC 只能由具名条目/纯托管生成器产出（见下面的专项断言）。
                ["Adobe RGB"] = "Rec.2020", ["ColorMatch RGB"] = "Rec.2020",
            };
            int generated = 0;
            foreach (var (spec, want) in expect)
            {
                var s = ColorSpaceRegistry.Resolve(spec);
                if (s == null) { Check(false, $"{spec}：registry 应能解析（现在解不出）"); continue; }
                var icc = IccProfileService.ResolveNamedIcc(spec, null,
                    s.OutPrimaries ?? "bt709", s.OutTrc ?? "iec61966-2-1", s.OutMatrix ?? "bt709");
                if (string.IsNullOrWhiteSpace(icc) || !File.Exists(icc))
                { Console.WriteLine($"  {spec,-14} SKIP（无法生成命名 ICC，不给绿灯）"); continue; }
                generated++;
                var got = FfmpegGui.Services.ColorMapping.ColorSpaceIdentify.IdentifyIccSpaceName(icc, "RGB built-in");
                Console.WriteLine($"  {spec,-14} 生成 ICC tokens={s.OutPrimaries}/{s.OutTrc} → 识别={got ?? "(null)"}");
                Check(string.Equals(got, want, StringComparison.OrdinalIgnoreCase),
                      $"{spec}：描述被误导时仍按度量认出 {want}（实得 {got ?? "null"}）");
                IccProfileService.TryDeleteIcc(icc);
            }
            Check(generated >= 4, $"至少 4 个标准空间可被生成并度量识别（实 {generated}）");
            // 兜底与“绝不猜”：无 ICC 时描述才当线索；两者都无 ⇒ null
            Check(FfmpegGui.Services.ColorMapping.ColorSpaceIdentify.IdentifyIccSpaceName(null, "Display P3") == "Display P3",
                "无 ICC 时仍按描述兜底（保住相机 JPEG 这类只给描述的场景）");
            Check(FfmpegGui.Services.ColorMapping.ColorSpaceIdentify.IdentifyIccSpaceName(null, null) == null,
                "既无 ICC 又无可读描述 ⇒ null（绝不猜成 sRGB）");

            // 专项：具名空间自己的 ICC（纯托管生成，如 ProPhoto 保真 ICC）必须能按色度认回本名，
            // 而不被“内置描述/无关描述”带偏——这才是“保真携带”路径赖以成立的根据。
            {
                var pIcc = FfmpegGui.Services.IccProfileService.GetFaithfulIcc("ProPhoto RGB");
                if (string.IsNullOrWhiteSpace(pIcc) || !File.Exists(pIcc))
                { Console.WriteLine("  ProPhoto 保真 ICC  SKIP（生成不可用，不给绿灯）"); }
                else
                {
                    var g = FfmpegGui.Services.ColorMapping.ColorSpaceIdentify.IdentifyIccSpaceName(pIcc, "Whatever weird name");
                    Console.WriteLine($"  ProPhoto 保真 ICC → 识别={g ?? "(null)"}（描述被故意写成一个无意义名字）");
                    Check(string.Equals(g, "ProPhoto RGB", StringComparison.OrdinalIgnoreCase),
                          $"保真 ICC 能被色度认回 ProPhoto RGB（实得 {g ?? "null"}）");
                }
            }
        }
    }
}
