using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Color
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // ColorGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> ColorGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class ColorGroup
    {
        private static double[] Mul9(double[] a, double[] b)
        {
            var o = new double[9];
            for (int r = 0; r < 3; r++)
                for (int c = 0; c < 3; c++)
                    o[r * 3 + c] = a[r * 3] * b[c] + a[r * 3 + 1] * b[3 + c] + a[r * 3 + 2] * b[6 + c];
            return o;
        }

        private static void ProbeMatrix()
        {
            const double Tol = 2e-3;   // 色度输入仅 3 位小数 → 与发布值差 ~1e-3

            void Cmp(string name, string from, string to, double[] expected)
            {
                var m = ColorSpaceRegistry.LinearMatrixBetweenPrimaries(from, to);
                if (m == null) { Check(false, $"{name}: 矩阵为 null（未实现该对）"); return; }
                double err = 0;
                for (int i = 0; i < 9; i++) err = Math.Max(err, Math.Abs(m[i] - expected[i]));
                Console.WriteLine($"{name} maxErr={err:E2} m=[{string.Join(",", m.Select(v => v.ToString("0.00000", System.Globalization.CultureInfo.InvariantCulture)))}]");
                Check(err <= Tol, $"{name} 与发布值一致（≤{Tol}）");
            }

            // BT.2020 → BT.709（ITU-R BT.2080 / 业界通用值：1.6605,-0.5877,-0.0728 | -0.1246,1.1330,-0.0084 | -0.0182,-0.1006,1.1187）
            // ⚠️ 曾误用第二个常见写法（第二行 1.422456）作为期望值 → 该错已由“两矩阵互不为逆”自身拦下：
            //    期望常量必须过互逆校验才能入库。
            Cmp("bt2020→bt709", "bt2020", "bt709", new[] {
                1.660491, -0.587641, -0.072850,
               -0.124550,  1.132901, -0.008350,
               -0.018151, -0.100581,  1.118731 });
            // BT.709 → BT.2020（BT.2080 Table：0.627404,0.329282,0.043314 | 0.069097,0.919544,0.011360 | 0.016392,0.088014,0.895600）
            Cmp("bt709→bt2020", "bt709", "bt2020", new[] {
                0.627404, 0.329282, 0.043314,
                0.069097, 0.919544, 0.011360,
                0.016392, 0.088014, 0.895600 });
            // 互逆自洽：正向与反向矩阵必须互为逆（仅抄录外部数值不够，这个检查能拦住“抄错行”）
            var a = ColorSpaceRegistry.LinearMatrixBetweenPrimaries("bt2020", "bt709");
            var b = ColorSpaceRegistry.LinearMatrixBetweenPrimaries("bt709", "bt2020");
            if (a != null && b != null)
            {
                var prod = Mul9(a, b);
                double idErr = 0;
                for (int i = 0; i < 9; i++) idErr = Math.Max(idErr, Math.Abs(prod[i] - (i % 4 == 0 ? 1.0 : 0.0)));
                Console.WriteLine($"bt2020→709→bt2020 与单位阵偏差 max={idErr:E2}");
                Check(idErr <= 1e-4, "双向矩阵互逆（≤1e-4）");
            }
            else Check(false, "双向矩阵互逆：存在 null");
            // Display P3 → sRGB (D65)
            Cmp("smpte432→bt709", "smpte432", "bt709", new[] {
                1.2249401, -0.2249404, 0.0,
               -0.0420569,  1.0420571, 0.0,
               -0.0196376, -0.0786361, 1.0982735 });

            // 同 token / 未知 token → null（调用不得“只改标签”）
            Check(ColorSpaceRegistry.LinearMatrixBetweenPrimaries("bt709", "bt709") == null, "同原色返回 null（无需映射）");
            Check(ColorSpaceRegistry.LinearMatrixBetweenPrimaries("nonsense", "bt709") == null, "未知原色返回 null");
            // 行和为 1（中性守恒）：白→白，保证灰阶不偏色
            var m = ColorSpaceRegistry.LinearMatrixBetweenPrimaries("bt2020", "bt709");
            if (m != null)
            {
                for (int r = 0; r < 3; r++)
                {
                    double s = m[r * 3] + m[r * 3 + 1] + m[r * 3 + 2];
                    Check(Math.Abs(s - 1.0) <= 1e-3, $"bt2020→bt709 第{r}行和≈1（白点守恒）实值={s:0.000000}");
                }
            }
            // 传递函数命名能力（不可精确表达者必须为 null，绝不凑近似）
            Check(ColorSpaceRegistry.ExactTransferName("Adobe RGB") == "bt470m", "Adobe RGB → bt470m(gamma2.2) 可精确表达");
            Check(ColorSpaceRegistry.ExactTransferName("sRGB") == "iec61966-2-1", "sRGB → iec61966-2-1");
            Check(ColorSpaceRegistry.ExactTransferName("Display P3") == "iec61966-2-1", "Display P3 → sRGB 曲线");
            Check(ColorSpaceRegistry.ExactTransferName("BT.2100 PQ") == "smpte2084", "BT.2100 PQ → smpte2084");
            Check(ColorSpaceRegistry.ExactTransferName("ProPhoto RGB") == null, "ProPhoto(1.8) 不可精确表达 → null");
            Check(ColorSpaceRegistry.ExactTransferName("DCI-P3") == null, "DCI-P3(2.6) 不可精确表达 → null");
        }
    }
}
