using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Color
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // ColorGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> ColorGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class ColorGroup
    {
        private static void ProbeOotf()
        {
            double G(double lw) => FfmpegGui.Services.ColorMapping.Bt2100Ootf.SystemGamma(lw);
            Check(Math.Abs(G(1000) - 1.2) < 1e-12, $"γ(1000nit) = 1.2（建议书明示）");
            Check(Math.Abs(G(4000) - 1.4527) < 1e-3, $"γ(4000nit) = 1.2+0.42·log10(4) = {G(4000):F4}（3 位有效 1.45）");
            Check(Math.Abs(G(300) - 0.9804) < 1e-3, $"γ(300nit) = {G(300):F4}（≈0.98）");
            Check(Math.Abs(G(10000) - 1.62) < 1e-12, $"γ(10000nit) = {G(10000):F4}（=1.62）");
            double sum = FfmpegGui.Services.ColorMapping.Bt2100Ootf.YsR
                       + FfmpegGui.Services.ColorMapping.Bt2100Ootf.YsG
                       + FfmpegGui.Services.ColorMapping.Bt2100Ootf.YsB;
            Check(Math.Abs(sum - 1.0) < 1e-12, $"Y_S 系数和 = 1（{sum}）→ 消色差时 Y_S≡E，不引入额外增益");

            double r = 1, g = 1, b = 1;
            FfmpegGui.Services.ColorMapping.Bt2100Ootf.Apply(ref r, ref g, ref b, 1000);
            Check(Math.Abs(r - 1000) < 1e-9 && Math.Abs(g - 1000) < 1e-9,
                $"α=L_W：消色差名义峰值 (1,1,1) → {r:F1} nits（应等于 L_W=1000）");

            bool ach = true;
            for (int i = 1; i <= 20; i++)
            {
                double e = i / 10.0;   // 含超白 1.1..2.0
                double rr = e, gg = e, bb = e;
                FfmpegGui.Services.ColorMapping.Bt2100Ootf.Apply(ref rr, ref gg, ref bb, 1000);
                double want = FfmpegGui.Services.ColorMapping.Bt2100Ootf.ApplyAchromatic(e, 1000);
                if (Math.Abs(rr - want) > 1e-9 * Math.Max(1, want)) ach = false;
            }
            Check(ach, "一般式与消色差特例一致：F = α·E^γ（含超白 E>1）");

            bool mono = true;
            for (int i = 1; i < 512; i++)
                if (FfmpegGui.Services.ColorMapping.Bt2100Ootf.ApplyAchromatic(i / 511.0 * 2, 1000)
                    < FfmpegGui.Services.ColorMapping.Bt2100Ootf.ApplyAchromatic((i - 1) / 511.0 * 2, 1000) - 1e-12)
                    mono = false;
            Check(mono, "消色差 OOTF 在 [0,2] 上单调不降");

            // 往返恒等（含超白与负值：Note 5h 要求不得钳位，反解必须能原路返回）
            double worst = 0; string worstAt = "";
            foreach (var t in new[] { (0.3, 0.2, 0.1), (1.5, 1.5, 1.5), (2.0, 0.5, 0.05), (0.9, -0.2, 0.05) })
            {
                double x = t.Item1, y = t.Item2, z = t.Item3;
                var key = $"({x},{y},{z})";
                FfmpegGui.Services.ColorMapping.Bt2100Ootf.Apply(ref x, ref y, ref z, 4000);
                FfmpegGui.Services.ColorMapping.Bt2100Ootf.ApplyInverse(ref x, ref y, ref z, 4000);
                double e = Math.Max(Math.Abs(x - t.Item1), Math.Max(Math.Abs(y - t.Item2), Math.Abs(z - t.Item3)));
                if (e > worst) { worst = e; worstAt = key; }
            }
            Check(worst < 1e-12, $"OOTF ∘ OOTF⁻¹ 恒等（最大误差 {worst:E2} @ {worstAt}，含超白/负值）");

            double sw = 1.5, sg = 1.5, sb = 1.5;
            FfmpegGui.Services.ColorMapping.Bt2100Ootf.Apply(ref sw, ref sg, ref sb, 1000);
            Check(sw > 1000, $"Note 5h：超白不被钳位（1.5 → {sw:F1} nits > L_W）");

            // 外部锚点：HLG 系统级 EOTF 的 0.75 码值经 OOTF(1000nit) 后应落在 SDR 参考白附近
            double e75 = TC.Hlg.ToLinear(0.75);
            double rr75 = e75, gg75 = e75, bb75 = e75;
            FfmpegGui.Services.ColorMapping.Bt2100Ootf.Apply(ref rr75, ref gg75, ref bb75, 1000);
            Console.WriteLine($"    锚点：HLG 0.75 → 场景线性 {e75:F5} → 显示 {rr75:F1} nits（SDR 参考白 {TC.SdrWhiteNits:F0}）");
            Check(Math.Abs(rr75 - TC.SdrWhiteNits) / TC.SdrWhiteNits < 0.05,
                $"HLG 0.75 码值≈SDR 参考白（{rr75:F1} vs {TC.SdrWhiteNits:F0} nits，偏差 {100 * Math.Abs(rr75 - TC.SdrWhiteNits) / TC.SdrWhiteNits:F1}%）");
        }
    }
}
