using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;

namespace Tests.Diagnostics
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // DiagnosticsGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> DiagnosticsGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class DiagnosticsGroup
    {
        private static async Task ProbePsnr(string[] args)
        {
            if (args.Length < 3) { Console.WriteLine("usage: ServiceProbe psnr <a> <b> [thresholdDb]"); Harness.FailOnly(); return; }
            double thr = args.Length >= 4 && double.TryParse(args[3], System.Globalization.NumberStyles.Any,
                System.Globalization.CultureInfo.InvariantCulture, out var t) ? t : 55;
            var (wa, ha) = await FfmpegGui.Services.ColorMapping.RawColorPipeline.ProbeSizeAsync(args[1]).ConfigureAwait(false);
            var (wb, hb) = await FfmpegGui.Services.ColorMapping.RawColorPipeline.ProbeSizeAsync(args[2]).ConfigureAwait(false);
            Check(wa > 0 && wa == wb && ha == hb, $"两图尺寸相同且可探测（{wa}x{ha} vs {wb}x{hb}）");
            if (wa <= 0 || wa != wb || ha != hb) return;
            var a = await FfmpegGui.Services.ColorMapping.RawColorPipeline.DecodeToRgb48Async(args[1], wa, ha).ConfigureAwait(false);
            var b = await FfmpegGui.Services.ColorMapping.RawColorPipeline.DecodeToRgb48Async(args[2], wb, hb).ConfigureAwait(false);
            double psnr = CM.Psnr16(a, b);
            int maxDiff = 0;
            int n = Math.Min(a.Length, b.Length);
            for (int i = 0; i + 1 < n; i += 2)
                maxDiff = Math.Max(maxDiff, Math.Abs((a[i] | (a[i + 1] << 8)) - (b[i] | (b[i + 1] << 8))));
            Console.WriteLine($"psnr={psnr:F2}dB maxDiff={maxDiff}/65535 尺寸={wa}x{ha}");
            Check(psnr >= thr, $"两路产物 PSNR ≥ {thr}dB（实 {psnr:F2}）");
        }
    }
}
