using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;

namespace Tests.Diagnostics
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // DiagnosticsGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> DiagnosticsGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class DiagnosticsGroup
    {
        private static void ProbeSelfTest()
        {
            int w = 128, h = 128;
            var src = SyntheticFrame16(w, h);
            var cases = new (string name, string sp, string st, string dp, string dt)[]
            {
                ("sRGB→P3", "bt709", "iec61966-2-1", "smpte432", "iec61966-2-1"),
                ("P3→sRGB", "smpte432", "iec61966-2-1", "bt709", "iec61966-2-1"),
                ("sRGB→BT.2020", "bt709", "iec61966-2-1", "bt2020", "bt709"),
                ("BT.2020→sRGB", "bt2020", "bt709", "bt709", "iec61966-2-1"),
                ("sRGB 自身曲线往返", "bt709", "iec61966-2-1", "bt709", "iec61966-2-1"),
            };
            foreach (var (name, sp, st, dp, dt) in cases)
            {
                var spec = Spec(sp, st, dp, dt);
                var dst = new byte[src.Length];
                var dstFast = new byte[src.Length];
                var tt = (CK.BuildTables(spec.SrcCurve), CK.BuildTables(spec.DstCurve));
                CK.TransformRgb48le(src, dst, spec, w * h);
                CK.TransformRgb48le(src, dstFast, spec, w * h, tt.Item1, tt.Item2);   // 表驱动快路径
                
                // 0) 快路径 == 解析式参考路径（生产用表，验证必须覆盖表）
                //    ⚠️ 必须按 16-bit 样本比对：逐字节比会把 0x0100 vs 0x00FF（仅差 1 LSB）算成“差 255”。
                int lsb = 0, worstOff = -1;
                for (int i = 0; i + 2 <= dst.Length; i += 2)
                {
                    int dv = Math.Abs((dst[i] | (dst[i + 1] << 8)) - (dstFast[i] | (dstFast[i + 1] << 8)));
                    if (dv > lsb) { lsb = dv; worstOff = i; }
                }
                if (lsb > 1 && worstOff >= 0)
                {
                    int px = worstOff / 6 * 6;   // 同像素起点
                    Console.WriteLine($"    最差样本 byteOff={worstOff} 解析={(dst[worstOff] | (dst[worstOff + 1] << 8))} " +
                        $"表={(dstFast[worstOff] | (dstFast[worstOff + 1] << 8))} " +
                        $"输入像素=({src[px] | (src[px + 1] << 8)},{src[px + 2] | (src[px + 3] << 8)},{src[px + 4] | (src[px + 5] << 8)}) " +
                        $"输出像素 解析=({dst[px] | (dst[px + 1] << 8)},{dst[px + 2] | (dst[px + 3] << 8)},{dst[px + 4] | (dst[px + 5] << 8)}) " +
                        $"表=({dstFast[px] | (dstFast[px + 1] << 8)},{dstFast[px + 2] | (dstFast[px + 3] << 8)},{dstFast[px + 4] | (dstFast[px + 5] << 8)}) " +
                        $"src={spec.SrcCurve.Name} dst={spec.DstCurve.Name}");
                }
                // 容差按目标曲线自身性质定：BT.709/240M 的 toe 是幂段切线（ITU 系数取整后留有
                // ~21 LSB 台阶，lcms2/zimg 同样存在），拐点附近选分支不同可差至 24 LSB；其余曲线应 ≤1。
                int tolLsb = spec.DstCurve.HasItuRoundingKink ? 24 : 1;
                Check(lsb <= tolLsb, $"{name}: 表驱动与解析式一致（max {lsb}/65535，容差 {tolLsb}"
                    + (spec.DstCurve.HasItuRoundingKink ? "，ITU 取整拐点台阶" : "") + "）");

                // 0b) **8-bit 出口**也要表/解析双路径互验 —— 实际教训：EncodeTo8 的解析式分支
                //     漏乘 65535（把 0..1 当 16-bit 码值），整幅输出变近黑，而此缺口只在无表路径出现
                //     （小帧 <256k 像素就是不建表），16-bit 出口的上面那条断言根本看不到。
                {
                    var d8a = new byte[w * h * 3];
                    var d8t = new byte[w * h * 3];
                    CK.TransformRgb48leToRgb8(src, d8a, spec, w * h, null, null, w, 0);
                    CK.TransformRgb48leToRgb8(src, d8t, spec, w * h, tt.Item1, tt.Item2, w, 0);
                    int mx = 0, worst8 = -1;
                    for (int i = 0; i < d8a.Length; i++)
                    { int dd = Math.Abs(d8a[i] - d8t[i]); if (dd > mx) { mx = dd; worst8 = i; } }
                    // 均值也要报：只查“两路一致”会漏掉“两路一起错”（黑图两边都黑照样通过）
                    double meanA = 0, meanT = 0;
                    foreach (byte by in d8a) meanA += by;
                    foreach (byte by in d8t) meanT += by;
                    meanA /= Math.Max(1, d8a.Length); meanT /= Math.Max(1, d8t.Length);
                    Console.WriteLine($"    rgb8 出口：最大差异 {mx}/255（idx={worst8}）解析均值={meanA:F1} 表均值={meanT:F1}");
                    Check(mx <= (spec.DstCurve.HasItuRoundingKink ? 2 : 1),
                        $"{name}: rgb8 出口 表驱动与解析式一致（max {mx}/255）");
                    Check(meanA > 8 && meanT > 8, $"{name}: rgb8 出口亮度合理（均值 {meanA:F1}/{meanT:F1}，非全黑）");
                }

                // 0c) **8-bit 源降位必须恒等**（任务 #12；16 个抖动相位全扫，两条出口路径都扫）。
                //     依据：8-bit 源经 `format=rgb48le` 升位后码值恒为 **257 的整数倍** ⇒ 16→8 是可精确还原的，
                //     抖动在这种值上只会注入误差。旧抖动用**未居中**的 Bayer（减 2/16 而非 7.5/16）
                //     ⇒ t ∈ [−2/16, +13/16]，16 个相位里 6 个 t ≥ 0.5 ⇒ 精确值被抬 +1（纯色/渐变上长出斑）。
                //     居中后 |t| ≤ 0.46875 ⇒ `Round(v + t) == v` 对 16 个相位都成立 —— 这条断言就是钉这个的。
                //     ⚠ 只在"恒等变换"那一格判：其余 4 格做了真实色彩映射，改值是本分。
                if (name == "sRGB 自身曲线往返")
                {
                    var id48 = new byte[256 * 3 * 2];
                    var want = new byte[256 * 3];
                    for (int v = 0; v < 256; v++)
                        for (int c = 0; c < 3; c++)
                        {
                            int o = (v * 3 + c) * 2;
                            id48[o] = (byte)((v * 257) & 0xFF);
                            id48[o + 1] = (byte)((v * 257) >> 8);
                            want[v * 3 + c] = (byte)v;
                        }
                    int worstDev = 0, worstPh = -1, badPhases = 0, worstAt = -1;
                    for (int ph = 0; ph < 16; ph++)
                    {
                        for (int pass = 0; pass < 2; pass++)   // 0=解析式 1=表驱动（两条路都得恒等）
                        {
                            var out8 = new byte[256 * 3];
                            if (pass == 0) CK.TransformRgb48leToRgb8(id48, out8, spec, 256, null, null, 256, ph);
                            else CK.TransformRgb48leToRgb8(id48, out8, spec, 256, tt.Item1, tt.Item2, 256, ph);
                            int dev = 0, at = -1;
                            for (int i = 0; i < out8.Length; i++)
                            {
                                int dd = Math.Abs(out8[i] - want[i]);
                                if (dd > dev) { dev = dd; at = i; }
                            }
                            if (dev > 0) badPhases++;
                            if (dev > worstDev) { worstDev = dev; worstPh = ph; worstAt = at; }
                        }
                    }
                    Console.WriteLine($"    8-bit 源降位恒等：最大偏差 {worstDev}/255"
                        + (worstAt >= 0 ? $"（相位 {worstPh}，码值 {worstAt / 3}）" : "")
                        + $"，不恒等的相位×路径组合 {badPhases}/32");
                    Check(worstDev == 0 && badPhases == 0,
                        $"8-bit 源降位恒等（16 相位 × 解析/表两条路径；最大偏差 {worstDev}/255"
                        + (worstDev > 0 ? $"，出现在相位 {worstPh} 的码值 {worstAt / 3}" : "") + "）");
                    // ⚠ 对照组：这条断言必须**能红**。零偏差既可能是"真恒等"，也可能是"我根本没在比东西"
                    //   （want 构错、循环空转都会给出 0）。⇒ 同一份产物与 `want+1` 比，偏差必须恰为 1，
                    //   以此证明比较链路是活的；这一条红了说明判据本身失效，而不是产品的降位坏了。
                    {
                        var out8c = new byte[256 * 3];
                        CK.TransformRgb48leToRgb8(id48, out8c, spec, 256, null, null, 256, 0);
                        int ctlDev = int.MaxValue;
                        for (int i = 0; i < out8c.Length; i++)
                        {
                            if (want[i] >= 255) continue;   // 255+1 越界：钳位后会造出假 0，必须跳过顶格
                            int dd = Math.Abs(out8c[i] - (want[i] + 1));
                            if (dd < ctlDev) ctlDev = dd;
                        }
                        // 夹具/产物都必须**非常数**：want 若退化成全 0，"逐字节相等"与"什么都没比"长得一样。
                        int distinctWant = (int)want.Distinct().Count();
                        int distinctOut = (int)out8c.Distinct().Count();
                        Check(distinctWant >= 250 && distinctOut >= 250,
                            $"对照组：夹具与产物都必须是满值域斜坡（want 去重 {distinctWant}/256，产物 {distinctOut}/256）"
                            + " —— 常数夹具会让「恒等」与「没在比」长得一样");
                        // 用 min 而非 max：`want+1` 与产物的**最小**可能偏差必须是 1（产物恒等 ⇒ 全体差 1；
                        // 若这里读到 0，说明产物里存在某个码值恰好等于 want+1 ⇒ 恒等判据本身就不该报绿）。
                        Check(ctlDev == 1, $"对照组：与 want+1 比的最小偏差应为 1（实得 {ctlDev}）—— 读到 0 说明恒等判据没在比东西");
                    }
                }

                // 1) 快内核 == 参考实现（同一数学的两个入口不能分叉）
                double worst = 0; int checkedCount = 0;
                for (int i = 0; i < w * h; i += 7)
                {
                    int o = i * 6;
                    var (rr, gg, bb) = CK.TransformPixelReference(
                        (src[o] | (src[o + 1] << 8)) / 65535f,
                        (src[o + 2] | (src[o + 3] << 8)) / 65535f,
                        (src[o + 4] | (src[o + 5] << 8)) / 65535f, spec);
                    worst = Math.Max(worst, Math.Abs(rr * 65535 - (dst[o] | (dst[o + 1] << 8))));
                    worst = Math.Max(worst, Math.Abs(gg * 65535 - (dst[o + 2] | (dst[o + 3] << 8))));
                    worst = Math.Max(worst, Math.Abs(bb * 65535 - (dst[o + 4] | (dst[o + 5] << 8))));
                    checkedCount++;
                }
                Check(worst <= 1.5, $"{name}: 融合内核与参考实现一致（max {worst:F2}/65535，样本 {checkedCount}）");

                // 2) 中性保持：灰阶斜坡映射后 R=G=B（白点守恒的直接体现）
                int off = (h / 8) * w * 6;
                int bad = 0;
                for (int x = 0; x < w; x++)
                {
                    int o = off + x * 6;
                    int r = dst[o] | (dst[o + 1] << 8), g = dst[o + 2] | (dst[o + 3] << 8), b = dst[o + 4] | (dst[o + 5] << 8);
                    if (Math.Max(Math.Abs(r - g), Math.Max(Math.Abs(g - b), Math.Abs(r - b))) > 2) bad++;
                }
                Check(bad == 0, $"{name}: 灰阶保持中性（异常 {bad}/{w}）");

                // 3) 单调性：斜坡不得出现反向跳变
                int rev = 0;
                for (int x = 1; x < w; x++)
                {
                    int a = off + (x - 1) * 6, bq = off + x * 6;
                    if ((dst[bq] | (dst[bq + 1] << 8)) < (dst[a] | (dst[a + 1] << 8))) rev++;
                }
                Check(rev == 0, $"{name}: 斜坡单调（反向 {rev}）");
            }

            // 4) 往返：sRGB→P3→sRGB 应基本恒等
            var a1 = new byte[src.Length]; var a2 = new byte[src.Length];
            CK.TransformRgb48le(src, a1, Spec("bt709", "iec61966-2-1", "smpte432", "iec61966-2-1"), w * h);
            CK.TransformRgb48le(a1, a2, Spec("smpte432", "iec61966-2-1", "bt709", "iec61966-2-1"), w * h);
            double psnr = CM.Psnr16(src, a2);
            Console.WriteLine($"  sRGB→P3→sRGB 往返 PSNR(16bit) = {psnr:F1} dB");
            Check(psnr >= 80, $"往返恒等（PSNR ≥ 80dB）");

            // 5) 恒等跳过：IsIdentity 必须为 true（避免无谓全帧重编码）
            Check(Spec("bt709", "iec61966-2-1", "bt709", "iec61966-2-1", matrix: false).IsIdentity, "同空间 Spec.IsIdentity=true");

            // 6) 8-bit 表路径：同空间往返必须字节不变
            var lut = TC.Srgb.BuildEotfTable8();
            var s8 = new byte[] { 0, 32, 64, 255, 128, 12, 200, 255, 1, 2, 3, 255 };
            var d8 = new byte[12];
            var enc = CK.BuildEncodeLut16(TC.Srgb, true);
            CK.TransformRgba8(s8, d8, Spec("bt709", "iec61966-2-1", "bt709", "iec61966-2-1", matrix: false), lut, w, h, enc);
            bool same = true;
            for (int i = 0; i < 12; i++) same &= s8[i] == d8[i];
            Check(same, "8bit 表路径：同空间往返字节不变");

            // 7) 调度器规模分档：小图单线程、中图整帧并行、大图流式（不新增并发限制，仅选策略）
            var sc1 = FfmpegGui.Services.ColorMapping.ColorScheduler.ForItem(2, 512, 512, 6);
            var sc2 = FfmpegGui.Services.ColorMapping.ColorScheduler.ForItem(2, 8192, 4096, 6);
            var scM = FfmpegGui.Services.ColorMapping.ColorScheduler.ForItem(2, 4096, 2160, 6);
            Check(sc1.Tier == "S" && sc1.Dop == 1, $"小图走 S 档单线程（实为 {sc1.Tier}/dop{sc1.Dop}）");
            Check(scM.Tier == "M" && !scM.Streaming, $"4K 走 M 档整帧并行（实为 {scM.Tier} stream={scM.Streaming}）");
            Check(sc2.Streaming && sc2.TileRows >= 1, $"8K 走 L 档流式（{sc2.ToLogFragment()}）");

            // ── 托盘/窗口图标资源（2026-10-02 的真实缺陷：托盘只有菜单没有图标）──
            // 成因链是**静默**的：`icon.ico` 没被记进 `<AvaloniaResource>` ⇒ `AssetLoader.Exists` 恒 false
            // ⇒ `App.LoadTrayIcon()` 返回 null ⇒ `TrayIcon.Icon` 空。而且旧那份文件其实是 32×32 的 PNG
            // 改了扩展名（既进不了 `ApplicationIcon`，也没有多档尺寸）。⇒ 两级各钉一条：
            //   ① 程序集里那份 avares 清单确实收录了它（不依赖 Avalonia 运行时，纯反射读清单字节）；
            //   ② `AssetLoader` 这条**产品真正走的路**能打开并解码。
            {
                var asm = typeof(FfmpegGui.App).Assembly;
                using (var ms = asm.GetManifestResourceStream("!AvaloniaResources"))
                {
                    var manifest = ms == null ? Array.Empty<byte>() : new BinaryReader(ms).ReadBytes((int)ms.Length);
                    Check(System.Text.Encoding.UTF8.GetString(manifest).Contains("Resources/icon_raw.png"),
                         $"① avares 清单收录 Resources/icon_raw.png（清单 {manifest.Length} B；缺失 ⇒ csproj 的 AvaloniaResource 又漏了）");
                }
                try
                {
                    var uri = new Uri("avares://FfmpegGui/Resources/icon_raw.png");
                    if (!Avalonia.Platform.AssetLoader.Exists(uri))
                    {
                        Check(false, "② AssetLoader.Exists 认得这条 avares URI");
                    }
                    else
                    {
                        using var s = Avalonia.Platform.AssetLoader.Open(uri);
                        using var bmp = new Avalonia.Media.Imaging.Bitmap(s);
                        Check(bmp.PixelSize.Width >= 16 && bmp.PixelSize.Height >= 16,
                             $"② 托盘图标可解码（实得 {bmp.PixelSize.Width}x{bmp.PixelSize.Height}）");
                    }
                }
                catch (Exception ex)
                {
                    // 本宿主没起 Avalonia 运行时 ⇒ 这条判不了，**点名 SKIP**，不许当成通过
                    Skip($"② AssetLoader 解码路径在本宿主判不了：{ex.GetType().Name}: {ex.Message}");
                }
            }
        }
    }
}
