using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;

namespace Tests.Diagnostics
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // DiagnosticsGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> DiagnosticsGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class DiagnosticsGroup
    {
        private static void ProbeToolDetect(string[] args)
        {
            int budgetSec = 120;
            if (args.Length > 1 && int.TryParse(args[1], out var bs) && bs > 0) budgetSec = bs;

            int Handles()
            {
                try
                {
                    using var self = System.Diagnostics.Process.GetCurrentProcess();
                    self.Refresh();
                    return self.HandleCount;
                }
                catch { return -1; }
            }

            var tmp = Path.Combine(Path.GetTempPath(),
                "tooldetect_" + Guid.NewGuid().ToString("N").Substring(0, 8));
            Directory.CreateDirectory(tmp);
            int h0 = Handles();
            try
            {
                // ── ① 读数：每个扩展搜索根的递归扫描耗时 + 句柄增量 ──
                var roots = FfmpegGui.Services.ExternalToolsDetector.GetExtendedSearchPaths();
                Console.WriteLine($"[读数] 扩展搜索根 {roots.Count} 个，起始句柄 {h0}");
                // 看门狗：单根扫描若**永不返回**，只靠"下一行为什么没出现"归因太弱 ⇒ 每 5s 打一次句柄。
                bool watching = true;
                var wd = new System.Threading.Thread(() =>
                {
                    while (watching)
                    {
                        System.Threading.Thread.Sleep(5000);
                        if (!watching) break;
                        Console.WriteLine($"[watch] 句柄 {Handles()}");
                        Console.Out.Flush();
                    }
                }) { IsBackground = true };
                wd.Start();
                double spent = 0; int scanned = 0, skipped = 0;
                foreach (var r in roots)
                {
                    if (spent > budgetSec) { skipped++; continue; }
                    int hb = Handles();
                    // ⚠ **扫之前**先点名并 flush：卡在某个根上时，这条读数才能归因（否则输出停在半截说不清是谁）
                    Console.WriteLine($"[读数] → 扫描 {r}");
                    Console.Out.Flush();
                    var sw = System.Diagnostics.Stopwatch.StartNew();
                    var found = FfmpegGui.Services.PlatformServices.FindToolInDirectory(
                        r, FfmpegGui.Services.PlatformServices.Djxl,
                        FfmpegGui.Services.PlatformServices.DjxlSearchWildcard);
                    sw.Stop();
                    int ha = Handles();
                    spent += sw.Elapsed.TotalSeconds; scanned++;
                    Console.WriteLine($"[读数]   {sw.Elapsed.TotalSeconds,6:F1}s 句柄 {hb}->{ha} (Δ{ha - hb,6})  " +
                                      $"{r}  命中={(found ?? "(无)")}");
                }
                watching = false;
                if (skipped > 0) Console.WriteLine($"[读数] 超出预算 {budgetSec}s ⇒ {skipped} 个根未扫");
                int h1 = Handles();
                Console.WriteLine($"[读数] 合计 {spent:F1}s（扫 {scanned}/{roots.Count} 根），句柄 {h0}->{h1} (Δ{h1 - h0})");
                Console.Out.Flush();

                // ── ①b 反挂死锁：拿"用户配置文件根目录"当唯一根找一个必然不存在的工具 ──
                //   这是实测到的真实形态：本机进程 PATH 里出现过裸 `C:\Users\20210`，而旧的
                //   `SearchOption.AllDirectories` 递归在这种树上**永不返回**（60 s 时句柄已 9 万）。
                //   预算常量不凭记忆写：断言的是「不超过单根预算 + 5s 抖动」。
                if (OperatingSystem.IsWindows())
                {
                    var prof = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
                    var swP = System.Diagnostics.Stopwatch.StartNew();
                    var ghost = FfmpegGui.Services.PlatformServices.FindToolInDirectory(
                        prof, "zz_no_such_tool_xyz.exe", "*zz_no_such_tool_xyz*.exe");
                    swP.Stop();
                    int hp = Handles();
                    //   ⚠ 上界**不得**只取产品常量：否则实现里把 `PerRootScanBudgetSec` 调大，本条判据
                    //     会跟着自动放宽 ⇒ 等于没有判据。⇒ 先锁常量的合理区间，再用它推上界。
                    int budgetConst = FfmpegGui.Services.ExternalToolsDetector.PerRootScanBudgetSec;
                    Check(budgetConst >= 5 && budgetConst <= 30,
                        $"①e 单根预算常量必须落在 [5,30]s（实得 {budgetConst}s；实测合法根 `C:\\Program Files` 全树 3.0s（`_probe-tool-detect.out:6`））");
                    Console.WriteLine($"[读数] 病态根 {prof} 单根扫描 {swP.Elapsed.TotalSeconds:F1}s 命中={(ghost ?? "(无)")} 句柄 {hp}");
                    Console.Out.Flush();
                    Check(ghost == null && hp >= 0 && swP.Elapsed.TotalSeconds <= budgetConst + 5,
                        $"①b 病态根必须在预算内返回 null（实得 {swP.Elapsed.TotalSeconds:F1}s / 上限 " +
                        $"{budgetConst + 5}s / 命中 {(ghost ?? "(null)")} / 句柄读数 {(hp < 0 ? "(取不到⇒判红)" : hp.ToString())}）");
                    // ⚠ 泄漏的判据是**斜率**不是绝对值：绝对阈值抓不住"每根几十、累计上千"的慢泄漏
                    //   （实测合法实现两次读数在 -2 ~ +35 之间摆动，而回归态是 9 万）。
                    int hb2 = Handles();
                    var sw2 = System.Diagnostics.Stopwatch.StartNew();
                    var ghost2 = FfmpegGui.Services.PlatformServices.FindToolInDirectory(
                        prof, "zz_no_such_tool_xyz.exe", "*zz_no_such_tool_xyz*.exe");
                    sw2.Stop();
                    int ha2 = Handles();
                    Check(ghost2 == null && hb2 >= 0 && ha2 >= 0 && (ha2 - hb2) <= 200,
                        $"①c 同一病态根**连扫两次**，第二次的句柄增量必须≈0（泄漏随次数线性涨；" +
                        $"Δ {ha2 - hb2} ≤ 200，第二次耗时 {sw2.Elapsed.TotalSeconds:F1}s）");
                }
                else Skip("①b/①c/①e 依赖 Windows 的『PATH 含大树』形态 ⇒ 本机不判（不是通过）");

                // ── ①f 反挂死判据**自己**要有牙（2026-09-22 变异实测的直接产物）──
                //   拿真实用户目录当"病态根"时，去掉 `EnumerateFilesSafe` 的 reparse 跳过 ⇒ ①b/①c
                //   **一条都不红**：真实目录本来就是靠 15 s 预算收口的，而 ①b 的上界 = 预算 + 5，
                //   结构上任何"重解析放大"都超不过 20 s ⇒ 判据形同虚设（成因=针无牙，不是没触发）。
                //   ⇒ 判据要咬得住，得自己造一个**必然成环**的根：`looproot\loop -> looproot`（自环 junction）。
                //     · 实现正确（跳过 reparse）⇒ 永不进入 loop ⇒ 亚秒级返回 null
                //     · 实现被改坏 ⇒ 无限下降直到撞满预算 ⇒ 本条转红（阈值 5 s ≪ 单根预算 15 s）
                //   ⚠ 收尾顺序是硬要求：**先单独摘掉 junction**（`Delete(link,false)` 只摘链接），
                //     再做递归清理 —— 反过来会让"递归删除跟着链接走进自己"（本仓已登记过 junction 删除坑）。
                if (OperatingSystem.IsWindows())
                {
                    var loopRoot = Path.Combine(tmp, "looproot");
                    var loopLink = Path.Combine(loopRoot, "loop");
                    Directory.CreateDirectory(loopRoot);
                    File.WriteAllText(Path.Combine(loopRoot, "loop_fixture.txt"), "fixture");
                    bool made = false;
                    try
                    {
                        var mk = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                        {
                            FileName = "cmd.exe",
                            Arguments = $"/c mklink /J \"{loopLink}\" \"{loopRoot}\"",
                            UseShellExecute = false, CreateNoWindow = true,
                            RedirectStandardOutput = true, RedirectStandardError = true
                        });
                        if (mk != null) { mk.WaitForExit(5000); }
                        made = Directory.Exists(loopLink);
                    }
                    catch (Exception ex) { Console.WriteLine($"[读数] mklink 异常：{ex.GetType().Name}"); }
                    Console.WriteLine($"[读数] 自环 junction 根造好={made}（{loopRoot}）");
                    if (!made) Skip("①f 本机造不出 junction（权限/被拦）⇒ 本条不判，不是通过");
                    else
                    {
                        // ⚠⚠ 判据**不能是耗时**：2026-09-23 变异实测 —— 去掉 reparse 跳过后，自环 walk
                        //   不是撞满 15 s 预算，而是在 ~12 层 `\loop` 后被 **MAX_PATH** 截停，全程 0.2 s
                        //   ⇒ 任何"≤ N 秒"型阈值都咬不住这条变异（`①b/①c 无牙`的翻版）。
                        //   ⇒ 换成**与时间无关**的判据：同一个标记文件必须**只被看见一次**。
                        //     跳过 reparse ⇒ 1 次；走进自环 ⇒ 每层都撞见一次 ⇒ 计数 >1 ⇒ 红。
                        var swL = System.Diagnostics.Stopwatch.StartNew();
                        var seen = FfmpegGui.Services.ExternalToolsDetector.EnumerateFilesSafe(loopRoot, "loop_fixture.txt");
                        var loopHit = FfmpegGui.Services.PlatformServices.FindToolInDirectory(
                            loopRoot, "zz_no_such_tool_xyz.exe", "*zz_no_such_tool_xyz*.exe");
                        swL.Stop();
                        // 负控/对照：同样计数法用在**没有环**的根上必须也是 1 ⇒ 证明红来自"成环"，不是计数口径写错
                        var plainRoot = Path.Combine(tmp, "plainroot");
                        Directory.CreateDirectory(plainRoot);
                        File.WriteAllText(Path.Combine(plainRoot, "loop_fixture.txt"), "fixture");
                        int plainSeen = FfmpegGui.Services.ExternalToolsDetector.EnumerateFilesSafe(plainRoot, "loop_fixture.txt").Count;
                        try { Directory.Delete(loopLink, false); } catch { }
                        bool linkGone = !Directory.Exists(loopLink);
                        Check(linkGone, "①f-清理 junction 必须能单独摘掉（摘不掉 ⇒ 立刻判红，绝不留给递归清理）");
                        Check(plainSeen == 1,
                            $"①f-对照 无环根的同名文件必须恰好被看见 1 次（实得 {plainSeen}）⇒ 下一条的计数口径本身可信");
                        Check(seen.Count == 1 && loopHit == null,
                            $"①f 自环根里的标记文件**只能被看见一次**（实得 {seen.Count} 次 / {swL.Elapsed.TotalSeconds:F1}s；" +
                            $"跳过 reparse 才做得到，>1 = 走进了环 ⇒ 与耗时无关，MAX_PATH 截停也照样红）");
                    }
                }
                else Skip("①f 的自环 junction 只在 Windows 上可造 ⇒ 本机不判，不是通过");

                // ── ② 诚实性：已证实**无法启动**的候选不得被报成可用工具 ──
                //   形态 (a)：一个后缀 .exe 但不是有效 PE 的文件（Prefetch 的 *.pf 之外的另一类"看着像"）。
                var junk = Path.Combine(tmp, "djxl_junk.exe");
                File.WriteAllText(junk, "this is not a portable executable");
                //   对照组（**负断言必须带一条两边都有的对照串**，否则"返回 null"可能只是因为根本没找到）：
                //   真能起来的 djxl 复制成一个不同名文件。
                //   ⚠ "文件存在" ≠ "起得来" ⇒ 每个候选都要**实跑一次**再认。2026-09-25 两种失效都踩过：
                //     · 只判 File.Exists 就用仓内 `tools/src/libjxl/build/tools/Release/djxl.exe` —— 它依赖
                //       `build/lib/Release/*.dll`（实测单独拷走 ⇒ 加载器退出 127、缺 `jxl_cms.dll`）
                //       ⇒ ②b/⑤/⑥ 一起变成 **5 条假红**（对照组自己起不来，负断言全部失去方向）。
                //     · 只认 `PlanFolderPath/jxl/bin/djxl.exe` —— 本机 PlanFolderPath 解析成 `C:\PLAN` 而那里没有
                //       jxl ⇒ ② 判红、⑤/⑥ 连带 SKIP（**覆盖丢失**，SKIP 不是通过）。
                //   ⇒ 候选按序：产品解析出的 PLAN 发布版 → 仓内 `publish/PLAN/jxl/bin/djxl.exe`
                //     （实测自带依赖、单独拷到 temp 仍 `--version` exit=0）。全部实跑失败 ⇒ 判红并列出试过什么。
                string LaunchableCtl(string exe)   // 自己启动来判，不走被测的 ChooseBestExecutable（否则是构造恒等）
                {
                    try
                    {
                        var psi = new System.Diagnostics.ProcessStartInfo(exe, "--version")
                        {
                            RedirectStandardOutput = true,
                            RedirectStandardError = true,
                            UseShellExecute = false,
                            CreateNoWindow = true
                        };
                        using var pp = System.Diagnostics.Process.Start(psi);
                        if (pp == null) return "Process.Start 返回 null";
                        var tOut = pp.StandardOutput.ReadToEndAsync();     // ⚠ 先挂读取、再等退出（本仓范式）
                        var tErr = pp.StandardError.ReadToEndAsync();
                        if (!pp.WaitForExit(8000)) { try { pp.Kill(entireProcessTree: true); } catch { } return "超时(8s)"; }
                        string o = tOut.GetAwaiter().GetResult() + tErr.GetAwaiter().GetResult();
                        return (pp.ExitCode == 0 || !string.IsNullOrWhiteSpace(o)) ? "ok" : $"exit={pp.ExitCode} 无输出";
                    }
                    catch (Exception ex) { return $"{ex.GetType().Name}: {ex.Message}"; }
                }
                var ctlCands = new List<string>();
                void AddCtl(string p)
                {
                    if (!string.IsNullOrWhiteSpace(p) && File.Exists(p) && !ctlCands.Contains(p)) ctlCands.Add(p);
                }
                AddCtl(Path.Combine(FfmpegGui.Services.PlatformServices.PlanFolderPath ?? "", "jxl", "bin", "djxl.exe"));
                for (var dp = new DirectoryInfo(AppContext.BaseDirectory); dp != null; dp = dp.Parent)
                    AddCtl(Path.Combine(dp.FullName, "publish", "PLAN", "jxl", "bin", "djxl.exe"));
                var real = Path.Combine(tmp, "djxl_real.exe");
                var realSrc = "";
                var ctlLog = new StringBuilder();
                foreach (var cd in ctlCands)
                {
                    try { File.Copy(cd, real, true); }
                    catch (Exception ex) { ctlLog.Append($" [{cd}] 拷贝失败 {ex.GetType().Name}"); continue; }
                    var vv = LaunchableCtl(real);
                    if (vv == "ok") { realSrc = cd; break; }
                    ctlLog.Append($" [{cd}] {vv}");
                }
                bool haveReal = realSrc.Length > 0;
                // ⚠ 对照组缺失**必须判红**（旧写法只 `Console.WriteLine("FAIL …")` ⇒ 不进 `_fail`、
                //   汇总仍是 `fail=0` ⇒ ②b/②c 整段蒸发而门禁照绿 = 假绿通道）。
                if (!haveReal)
                    Check(false, "② 对照组缺失：" + (ctlCands.Count == 0
                            ? "一个候选都没凑出来（PLAN 与仓内 publish 都没有 djxl.exe）"
                            : ctlLog.ToString().Trim())
                        + " ⇒ ②b/②c 无从判（绝不静默跳过）");

                var junkOnly = FfmpegGui.Services.ExternalToolsDetector
                    .ChooseBestExecutable(new[] { junk });
                Check(junkOnly == null,
                    $"②a 只有「起不来的 .exe」时返回 null（实得 {(junkOnly ?? "(null)")}）——不得回退成假 ✅");
                if (haveReal)
                {
                    var realOnly = FfmpegGui.Services.ExternalToolsDetector
                        .ChooseBestExecutable(new[] { real });
                    Check(string.Equals(realOnly, real, StringComparison.OrdinalIgnoreCase),
                        $"②b 对照组：真能起来的 exe 必须被选中（实得 {(realOnly ?? "(null)")}）");
                    var mixed = FfmpegGui.Services.ExternalToolsDetector
                        .ChooseBestExecutable(new[] { junk, real });
                    Check(string.Equals(mixed, real, StringComparison.OrdinalIgnoreCase),
                        "②c 真假混合：坏候选被跳过、选中好的（顺序把坏的放前面）");
                }

                //   形态 (b)：Prefetch 里的 `EXIFTOOL.EXE-<hash>.pf` —— 只有**无扩展名约束**的通配会命中它。
                var pfDir = Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.Windows), "Prefetch");
                string? pfHit = null;
                try
                {
                    using var en = Directory.EnumerateFiles(pfDir, "*exiftool.exe*").GetEnumerator();
                    while (en.MoveNext()) { pfHit = en.Current; break; }
                }
                catch (Exception ex) { Console.WriteLine($"[读数] Prefetch 枚举不可用：{ex.GetType().Name}"); }
                Console.WriteLine($"[读数] `*exiftool.exe*` 在 Prefetch 命中: {(pfHit ?? "(本机无命中)")}");
                if (pfHit != null)
                {
                    var pf = FfmpegGui.Services.ExternalToolsDetector.ChooseBestExecutable(new[] { pfHit });
                    Check(pf == null, $"②d Prefetch 的 .pf 不得被当作工具（实得 {(pf ?? "(null)")}）");
                }
                // ⚠ 本机 Prefetch 读不到（非提权令牌的 DACL 只给 BA）或确实没有命中 ⇒ **点名 SKIP**，
                //   不许让这条"因为条件不满足而没跑"变成汇总里的一个绿点。
                else Skip("②d Prefetch 形态本机不可判（无命中或目录不可枚举）⇒ 不是通过");

                // ── ③ 可注入性：降级路径的门禁必须能**确定地**关掉系统级搜索根 ──
                if (OperatingSystem.IsWindows())
                {
                    var emptyA = Path.Combine(tmp, "rootA");
                    Directory.CreateDirectory(emptyA);
                    var saved = Environment.GetEnvironmentVariable("FFMPEGGUI_EXT_SEARCH_DIRS");
                    try
                    {
                        Environment.SetEnvironmentVariable("FFMPEGGUI_EXT_SEARCH_DIRS", emptyA);
                        var rs = FfmpegGui.Services.ExternalToolsDetector.GetExtendedSearchPaths();
                        Check(rs.Count == 1 && string.Equals(rs[0], emptyA, StringComparison.OrdinalIgnoreCase),
                            $"③ FFMPEGGUI_EXT_SEARCH_DIRS 覆盖系统根（实得 [{string.Join(" | ", rs)}]）");
                        Environment.SetEnvironmentVariable("FFMPEGGUI_EXT_SEARCH_DIRS", emptyA + ";");
                        var rs2 = FfmpegGui.Services.ExternalToolsDetector.GetExtendedSearchPaths();
                        Check(rs2.Count == 1 && string.Equals(rs2[0], emptyA, StringComparison.OrdinalIgnoreCase),
                            $"③b 末尾空段不得被当成「整个 PATH」（实得 [{string.Join(" | ", rs2)}]）");
                    }
                    finally
                    {
                        Environment.SetEnvironmentVariable("FFMPEGGUI_EXT_SEARCH_DIRS", saved);
                    }
                    Console.WriteLine($"[读数] 撤掉覆盖后根数回到 {FfmpegGui.Services.ExternalToolsDetector.GetExtendedSearchPaths().Count}");
                }
                else Skip("③/③b 的可注入收口只在 Windows 上有意义（非 Windows 本就不做系统递归搜索）⇒ 不是通过");

                // ── ⑤ 系统 PATH 这一级必须真的存在且真的非递归 ──
                //   2026-09-22 实测：`DjxlService.Detect` 的 `// ⑤ PATH` **只有注释没有代码**，
                //   而 `GetExtendedSearchPaths` 排除 `C:\Windows*` 的理由正是"⑤ 会兜住 PATH 工具"
                //   ⇒ 前提不成立 ⇒ 放在 System32 的 djxl 永远发现不了（且只表现为静默换通路）。
                //   判据成对：**原语行为**（放得进 PATH 就找得到 / 拿掉就找不到）+ **接线源码锁**
                //   （`DjxlService` 真的调它 —— 光有原语不挡住"忘了接线"，那正是本次的缺陷形态）。
                if (OperatingSystem.IsWindows() && haveReal)
                {
                    var pathDir = Path.Combine(tmp, "pathroot");
                    Directory.CreateDirectory(pathDir);
                    File.Copy(realSrc, Path.Combine(pathDir, "djxl.exe"), true);
                    var savedPath = Environment.GetEnvironmentVariable("PATH");
                    bool foundInPath = false; string? foundAt = null;
                    try
                    {
                        Environment.SetEnvironmentVariable("PATH", pathDir + ";" + savedPath);
                        foundInPath = FfmpegGui.Services.PlatformServices.TryFindInPath(
                            FfmpegGui.Services.PlatformServices.Djxl, out foundAt);
                    }
                    finally { Environment.SetEnvironmentVariable("PATH", savedPath); }
                    Check(foundInPath && !string.IsNullOrEmpty(foundAt)
                          && Path.GetDirectoryName(foundAt)!.Equals(pathDir, StringComparison.OrdinalIgnoreCase),
                        $"⑤a 原语：只在 PATH 里的 djxl 必须被找到（实得 found={foundInPath} path={foundAt ?? "(null)"}）");
                    // 负控：同一原语在**没**注入 PATH 时必须找不到（否则 ⑤a 是"总能找到"的真空绿）
                    bool stillFound = FfmpegGui.Services.PlatformServices.TryFindInPath(
                        "zz_no_such_tool_in_path.exe", out var stillAt);
                    Check(!stillFound && stillAt == null,
                        $"⑤a-负控 不在 PATH 的工具必须找不到（实得 found={stillFound} path={stillAt ?? "(null)"}）");
                    // 源码锁要先定位仓库根（同 `InitExternalTools` 的向上走法；找不到 ⇒ 判红，不静默跳过）
                    string? djsPath = null;
                    for (var d2 = new DirectoryInfo(AppContext.BaseDirectory); d2 != null; d2 = d2.Parent)
                    {
                        var cand = Path.Combine(d2.FullName, "src", "FfmpegGui", "Services", "DjxlService.cs");
                        if (File.Exists(cand)) { djsPath = cand; break; }
                    }
                    Check(djsPath != null, $"⑤b 前置：定位到 DjxlService.cs（实得 {djsPath ?? "(未找到 ⇒ 接线锁无法判)"}）");
                    var djs = djsPath == null ? "" : File.ReadAllText(djsPath);
                    Check(djs.Contains("TryFindInPath(PlatformServices.Djxl"),
                        "⑤b 接线锁：DjxlService 的 ⑤ 真的调用 TryFindInPath（只剩注释/被删即红）");
                    Check(!System.Text.RegularExpressions.Regex.IsMatch(djs, @"//\s*⑤\s*PATH\s*\r?\n\s*\}"),
                        "⑤b2 接线锁：不得再出现「只有 `// ⑤ PATH` 注释、下一行就收尾」的形态");
                }
                else Skip("⑤a/⑤b 需要 Windows + 可执行的 djxl 对照组 ⇒ 本机不判（不是通过）");

                // ── ⑥ SIMD 标签选路：文件名后缀必须按本机 CPU 能力定序，且「标签优先」不得盖过「起不起来」 ──
                //   2026-09-24 补的**零覆盖**：`ChooseBestExecutable` 里这一段（`GetSimdPriorityTags()` → 逐个
                //   tag 用 `name.Contains(tag)` 收拢 → 剩余追加 → `generic` 兜住全部）此前**一条判据都没有** ——
                //   把它整段删掉，①/②/③/⑤ 全照样绿（它们要么只喂单元素候选，要么喂不带标签的文件名）。
                //   ⚠ 判据刻意**不重算产品的排序**（那只会做成"构造恒等"自检）：断言的是外部可观察后果 ——
                //     输入顺序无关、高优先标签必胜、高优先那份起不来时必须落到次高、全带标签且全起不来必须 null。
                //   ⚠ 夹具前提单独断言（不信任自己的构造）：选出的两个标签**互不为子串**，且三个文件名都
                //     不命中比 hi 更早的标签 ⇒ 否则"期望 = hi 那份"根本不可计算（子串歧义会让判据失去方向）。
                if (haveReal)
                {
                    var tags = FfmpegGui.Services.CpuFeatureService.GetSimdPriorityTags();
                    Check(tags.Length > 0 && tags[tags.Length - 1] == "generic",
                        $"⑥a1 标签表非空且末位是 generic（实得 {tags.Length} 项 / 末位 \"{tags[tags.Length - 1]}\"）");
                    bool anyBlank = false;
                    foreach (var t2 in tags) if (string.IsNullOrWhiteSpace(t2)) anyBlank = true;
                    //   匹配判据是 `name.Contains(tag)` ⇒ 一个空/空白标签会让**第一轮**吞掉全部候选并按**逆序**
                    //   返回（`for i = Count-1 downto 0`），选路静默退化成"最后入列者优先"，且不抛错不打日志。
                    Check(!anyBlank, "⑥a2 标签表不得含空/空白项（`Contains(\"\")` 恒真 ⇒ 排序退化为逆序，见上）");
                    string? hi = null, lo = null;
                    for (int a = 0; a < tags.Length && hi == null; a++)
                    {
                        if (tags[a] == "generic") break;
                        for (int b = a + 1; b < tags.Length; b++)
                        {
                            if (tags[b] == "generic") break;
                            if (!tags[a].Contains(tags[b], StringComparison.Ordinal)
                                && !tags[b].Contains(tags[a], StringComparison.Ordinal)) { hi = tags[a]; lo = tags[b]; break; }
                        }
                    }
                    if (hi == null || lo == null)
                    {
                        Skip("⑥b–⑥e 需要标签表里存在**互不为子串**的一对（本机表 = ["
                             + string.Join(", ", tags) + "]）⇒ 造不出无歧义夹具，不判，不是通过");
                    }
                    else
                    {
                        int idxHi = Array.IndexOf(tags, hi);
                        int idxLo = Array.IndexOf(tags, lo);
                        var simdDir = Path.Combine(tmp, "simd");
                        var simdJunk = Path.Combine(tmp, "simdjunk");
                        Directory.CreateDirectory(simdDir);
                        Directory.CreateDirectory(simdJunk);
                        string MkReal(string dir, string tag)
                        {
                            var p = Path.Combine(dir, "zzprobe-" + tag + ".exe");
                            File.Copy(realSrc, p, true);           // 同一份**真起得来**的二进制，只差文件名
                            return p;
                        }
                        var pHi = MkReal(simdDir, hi);
                        var pLo = MkReal(simdDir, lo);
                        var pPlain = Path.Combine(simdDir, "zzprobeplain.exe");
                        File.Copy(realSrc, pPlain, true);
                        var jHi = Path.Combine(simdJunk, "zzprobe-" + hi + ".exe");
                        File.WriteAllText(jHi, "this is not a portable executable");
                        var jLo = Path.Combine(simdJunk, "zzprobe-" + lo + ".exe");
                        File.WriteAllText(jLo, "this is not a portable executable");
                        string N(string? p) { return p == null ? "(null)" : Path.GetFileName(p); }
                        Check(idxHi >= 0 && idxLo > idxHi,
                            $"⑥a3 选出的标签顺序与表内优先级一致（hi={hi}@{idxHi} / lo={lo}@{idxLo}）");
                        bool premiseOk = true;
                        foreach (var nm in new[] { N(pHi), N(pLo), N(pPlain) })
                        {
                            var ln = nm.ToLowerInvariant();
                            for (int k = 0; k < idxHi; k++) if (ln.Contains(tags[k])) premiseOk = false;
                        }
                        foreach (var t2 in tags)
                            if (t2 != "generic" && N(pPlain).ToLowerInvariant().Contains(t2)) premiseOk = false;
                        Check(premiseOk,
                            $"⑥-premise 夹具前提：hi/lo/plain 的文件名都不得命中比 hi 更早的标签，且 plain 不得命中任何实标签" +
                            $"（表=[{string.Join(", ", tags)}]，hi={hi}@{idxHi}）");
                        var r1 = FfmpegGui.Services.ExternalToolsDetector.ChooseBestExecutable(new[] { pLo, pHi, pPlain });
                        var r2 = FfmpegGui.Services.ExternalToolsDetector.ChooseBestExecutable(new[] { pPlain, pHi, pLo });
                        var r3 = FfmpegGui.Services.ExternalToolsDetector.ChooseBestExecutable(new[] { pHi, pPlain, pLo });
                        Check(string.Equals(r1, pHi, StringComparison.OrdinalIgnoreCase)
                              && string.Equals(r2, pHi, StringComparison.OrdinalIgnoreCase)
                              && string.Equals(r3, pHi, StringComparison.OrdinalIgnoreCase),
                            $"⑥b 三种输入顺序都必须选高优先标签那份（实得 {N(r1)} / {N(r2)} / {N(r3)}，期望 {N(pHi)}）");
                        var r4 = FfmpegGui.Services.ExternalToolsDetector.ChooseBestExecutable(new[] { pPlain, pLo });
                        Check(string.Equals(r4, pLo, StringComparison.OrdinalIgnoreCase),
                            $"⑥c 拿掉 hi 时应落到次高标签那份（实得 {N(r4)}，期望 {N(pLo)}）⇒ 起作用的是标签匹配而不是「返回第一个」");
                        var r5 = FfmpegGui.Services.ExternalToolsDetector.ChooseBestExecutable(new[] { jHi, pLo, pPlain });
                        Check(string.Equals(r5, pLo, StringComparison.OrdinalIgnoreCase),
                            $"⑥d hi 位置换成起不来的垃圾 ⇒ 必须落到 lo（实得 {N(r5)}，期望 {N(pLo)}）：标签优先级不得盖过「起不起来」");
                        var r6 = FfmpegGui.Services.ExternalToolsDetector.ChooseBestExecutable(new[] { jHi, jLo });
                        Check(r6 == null,
                            $"⑥e 全是「带特征后缀 + 起不来」的候选 ⇒ 必须 null（实得 {N(r6)}）——末尾兜底不得把带标签的垃圾报成工具");
                        Console.WriteLine($"[读数] ⑥ 夹具 hi={hi} lo={lo} 表=[{string.Join(", ", tags)}] " +
                                          $"CPU={FfmpegGui.Services.CpuFeatureService.Summary()}");
                    }
                }
                else Skip("⑥ 依赖 ② 的真 djxl 对照组来造「都起得来、只差文件名」的三份候选（对照组缺失时 ② 已判红）⇒ 不判");

                // ── ④ 残留自证（精确路径，不用通配） ──
                int del = 0;
                foreach (var f in Directory.GetFiles(tmp, "*", SearchOption.AllDirectories)) { File.Delete(f); del++; }
                Directory.Delete(tmp, true);
                Check(!Directory.Exists(tmp), $"④ 运行级目录已清零（删 {del} 个文件）：{tmp}");
            }
            finally
            {
                try { if (Directory.Exists(tmp)) Directory.Delete(tmp, true); } catch { }
            }
        }
    }
}
