using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;

namespace Tests.Diagnostics
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // DiagnosticsGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> DiagnosticsGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class DiagnosticsGroup
    {
        private static async System.Threading.Tasks.Task ProbeXcheck(string[] args)
        {
            if (args.Length < 6)
            {
                Console.WriteLine("usage: ServiceProbe xcheck <input> <srcPrim> <srcTrc> <dstPrim> <dstTrc> [outDir]");
                Harness.FailOnly(); return;
            }
            string input = args[1];
            var (w, h) = await FfmpegGui.Services.ColorMapping.RawColorPipeline.ProbeSizeAsync(input).ConfigureAwait(false);
            if (w <= 0) { Check(false, "无法探测尺寸"); return; }
            var outDir = args.Length >= 7 ? args[6] : Path.Combine(Path.GetTempPath(), "cmsx");
            Directory.CreateDirectory(outDir);
            var spec = Spec(args[2], args[3], args[4], args[5]);

            // A) 引擎路径
            var raw = await FfmpegGui.Services.ColorMapping.RawColorPipeline
                .DecodeToRgb48Async(input, w, h).ConfigureAwait(false);
            var raw2 = new byte[raw.Length];
            CK.TransformRgb48le(raw, raw2, spec, w * h, CK.BuildTables(spec.SrcCurve), CK.BuildTables(spec.DstCurve));
            string enginePng = Path.Combine(outDir, "engine.png");
            await FfmpegGui.Services.ColorMapping.RawColorPipeline.WriteRgb48ToPngAsync(
                raw2, w, h, enginePng, args[4], args[5], null).ConfigureAwait(false);

            // B) 参照路径（zimg 自己完成同样的 primaries/曲线转换）
            //    ⚠️ 必须像生产代码那样在 **-i 之前**声明输入色彩（-color_primaries/-color_trc）：
            //    源文件无 CICP 时（lavfi 产出的 PNG 为 gbr/unknown/unknown），只写 zscale 的 tin=
            //    会被当 unknown 处理（实测参照几乎不变，差仅 244/65535），导致“参照失效”而误判引擎错。
            string mTok = args[4] == "bt2020" ? "bt2020nc" : "bt709";
            string zimgPng = Path.Combine(outDir, "zimg.png");
            var ff = AppSettingsService.Current.FfmpegPath;
            var psi = new System.Diagnostics.ProcessStartInfo
            {
                FileName = ff,
                Arguments = $"-y -hide_banner -loglevel error -color_primaries {args[2]} -color_trc {args[3]} -i \"{input}\" "
                  + $"-vf \"format=gbrpf32le,zscale=pin={args[2]}:tin={args[3]}:min=gbr:rin=pc:p={args[4]}:t={args[5]}:m={mTok}:r=pc,format=rgb48le\" \"{zimgPng}\"",
                RedirectStandardError = true, UseShellExecute = false, CreateNoWindow = true,
            };
            using (var p = System.Diagnostics.Process.Start(psi))
            {
                if (p == null) { Check(false, "无法启动 ffmpeg"); return; }
                string err = await p.StandardError.ReadToEndAsync().ConfigureAwait(false);
                await p.WaitForExitAsync().ConfigureAwait(false);
                if (p.ExitCode != 0) { Check(false, $"zscale 参照路径失败: {err.Trim()}"); return; }
            }

            // C) 比对：两路均写成 16bit PNG → 各自解回 rgb48 再比
            var a = await FfmpegGui.Services.ColorMapping.RawColorPipeline.DecodeToRgb48Async(enginePng, w, h).ConfigureAwait(false);
            var b = await FfmpegGui.Services.ColorMapping.RawColorPipeline.DecodeToRgb48Async(zimgPng, w, h).ConfigureAwait(false);
            double psnr = CM.Psnr16(a, b);
            int maxDiff = 0, deSamples = 0; double worstDeltaE = 0, sumDeltaE = 0;
            int n = Math.Min(a.Length, b.Length);
            for (int i = 0; i + 6 <= n; i += 6)
            {
                int r1 = a[i] | (a[i + 1] << 8), g1 = a[i + 2] | (a[i + 3] << 8), b1 = a[i + 4] | (a[i + 5] << 8);
                int r2 = b[i] | (b[i + 1] << 8), g2 = b[i + 2] | (b[i + 3] << 8), b2 = b[i + 4] | (b[i + 5] << 8);
                maxDiff = Math.Max(maxDiff, Math.Max(Math.Abs(r1 - r2), Math.Max(Math.Abs(g1 - g2), Math.Abs(b1 - b2))));
                if ((i / 6) % 53 == 0)   // 抽样算 ΔE（8bit 口径，与业界一致）
                {
                    double de = CM.DeltaE76((byte)(r1 >> 8), (byte)(g1 >> 8), (byte)(b1 >> 8),
                                             (byte)(r2 >> 8), (byte)(g2 >> 8), (byte)(b2 >> 8));
                    worstDeltaE = Math.Max(worstDeltaE, de); sumDeltaE += de; deSamples++;
                }
            }
            Console.WriteLine($"xcheck {Path.GetFileName(input)} {args[2]}/{args[3]}→{args[4]}/{args[5]}  {w}x{h}");
            Console.WriteLine($"  PSNR(16bit)={psnr:F2}dB  maxDiff={maxDiff}/65535  ΔE max={worstDeltaE:F3} avg={(deSamples > 0 ? sumDeltaE / deSamples : 0):F4} (样本 {deSamples})");
            Check(psnr >= 55, $"引擎 vs zimg PSNR ≥ 55dB（实 {psnr:F1}）");
            Check(maxDiff <= 1500, $"最大单通道差异 ≤ 1500/65535（实 {maxDiff}）");
            Check(worstDeltaE <= 1.5, $"峰值 ΔE*ab ≤ 1.5（实 {worstDeltaE:F3}）");
        }
    }
}
