using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Geometry
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // GeometryGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> GeometryGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class GeometryGroup
    {
        private static async System.Threading.Tasks.Task ProbeOrientMeta(string[] args)
        {
            string ff = AppSettingsService.Current.FfmpegPath;
            string exif = FfmpegGui.Services.ExifToolService.DetectedPath ?? "";
            if (string.IsNullOrWhiteSpace(ff) || !File.Exists(ff))
            { Check(false, "orientmeta：未找到 ffmpeg"); return; }
            if (string.IsNullOrWhiteSpace(exif) || !File.Exists(exif))
            { Check(false, "orientmeta：未检测到 exiftool ⇒ 无法造夹具（显式判红，不静默跳过）"); return; }

            string root = args.Length >= 2 ? args[1] : "tests/output/validate";
            string dir = Path.Combine(root, "orientmeta_" + Guid.NewGuid().ToString("N").Substring(0, 8));
            Directory.CreateDirectory(dir);
            Console.WriteLine($"orientmeta-out={dir}");
            var created = new List<string>();

            async Task Run(string exe, string a)
            {
                using var p = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(exe, a)
                { RedirectStandardOutput = true, RedirectStandardError = true, UseShellExecute = false, CreateNoWindow = true })!;
                var so = p.StandardOutput.ReadToEndAsync();
                var se = p.StandardError.ReadToEndAsync();
                await p.WaitForExitAsync().ConfigureAwait(false);
                await so; await se;
            }
            // ⚠ **只读 stdout**：exiftool 的 perl locale 警告走 **stderr**，合并取数会把
            //   "Falling back to the standard locale" 当成标签值读回来（本探针第一版实测踩中，
            //   6 条判据全被它带红）。stderr 仍要**排空**（P2-3：不排空会堵死子进程），只是不参与取值。
            //   ⇒ 这正是 `_probe-stderr-merge-scan.ps1` 那条债账锁要拦的形态，写探针的人也不例外。
            async Task<string> Cap(string exe, string a)
            {
                using var p = System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(exe, a)
                { RedirectStandardOutput = true, RedirectStandardError = true, UseShellExecute = false, CreateNoWindow = true })!;
                var so = p.StandardOutput.ReadToEndAsync();
                var se = p.StandardError.ReadToEndAsync();
                await p.WaitForExitAsync().ConfigureAwait(false);
                string stdout = await so.ConfigureAwait(false);
                _ = await se.ConfigureAwait(false);
                return stdout.Trim();
            }
            async Task<string> OrientationOf(string path)
                => (await Cap(exif, $"-q -n -Orientation \"{path}\"").ConfigureAwait(false))
                     .Split(':').Last().Trim();

            try
            {
                // ── 夹具：带拍摄字段的取向 JPEG（Make/Model 用来证明"复制真的发生了"）──
                string src = Path.Combine(dir, "src_orient8.jpg"); created.Add(src);
                await Run(ff, $"-y -hide_banner -loglevel error -f lavfi "
                            + $"-i \"testsrc2=size=64x32:duration=1\" -frames:v 1 -q:v 3 \"{src}\"")
                      .ConfigureAwait(false);
                await Run(exif, $"-q -n -overwrite_original \"-Orientation=8\" -Make=TESTCAM -Model=TESTMODEL "
                              + $"\"{src}\"").ConfigureAwait(false);
                var (cw, ch) = FfmpegGui.Services.ImageGeometry
                    .ParseDisplaySize(await Cap(AppSettingsService.Current.FfprobePath,
                        $"-v error -select_streams v:0 -read_intervals \"%+#1\" "
                      + $"-show_entries stream=width,height -show_entries frame_side_data_list -of json \"{src}\"")
                        .ConfigureAwait(false));
                Check(cw == 32 && ch == 64 && await OrientationOf(src) == "8",
                    $"夹具：Orientation=8 且**显示**尺寸 = 32x64（实得 {cw}x{ch} / 标签 {await OrientationOf(src)}）"
                  + $"——coded 必须是 64x32，否则两口径同轴、本探针恒真");

                // ── 产物：模拟"解码器已旋正"的出口（ffmpeg 直解，不带任何取向标签）──
                string prod = Path.Combine(dir, "prod_upright.jpg"); created.Add(prod);
                await Run(ff, $"-y -hide_banner -loglevel error -i \"{src}\" -frames:v 1 -q:v 3 \"{prod}\"")
                      .ConfigureAwait(false);
                var (pw, ph) = FfmpegGui.Services.ImageGeometry
                    .ParseDisplaySize(await Cap(AppSettingsService.Current.FfprobePath,
                        $"-v error -select_streams v:0 -read_intervals \"%+#1\" "
                      + $"-show_entries stream=width,height -show_entries frame_side_data_list -of json \"{prod}\"")
                        .ConfigureAwait(false));
                Check(pw == 32 && ph == 64 && await OrientationOf(prod) == "",
                    $"产物起点：像素已旋正（{pw}x{ph}）且**本来就没有** Orientation 标签（实得「{await OrientationOf(prod)}」）"
                  + $"⇒ 后面若出现标签，只可能是恢复步骤抄进来的");

                // ── M1/M2：产品自己的恢复调用（默认 dropOrientation=true）──
                int rc = await FfmpegGui.Services.ExifToolService.CopyMetadataAsync(
                    src, prod, null, absorb: null).ConfigureAwait(false);
                string gotOri = await OrientationOf(prod).ConfigureAwait(false);
                string gotMake = (await Cap(exif, $"-q -s -Make \"{prod}\"").ConfigureAwait(false))
                                    .Split(':').Last().Trim();
                string gotModel = (await Cap(exif, $"-q -s -Model \"{prod}\"").ConfigureAwait(false))
                                    .Split(':').Last().Trim();
                // ⚠ 排除式**不生效**时 exiftool 返回退出码 0（它只是照抄了标签），所以 rc 不是证据。
                //   控制臂：同一次调用里必须看到 Make/Model 到了产物（M2）——M1 只有在 M2 成立时才有意义。
                Console.WriteLine($"orientmeta-full  rc={rc} Orientation=「{gotOri}」 Make=「{gotMake}」 Model=「{gotModel}」");
                Check(rc == 0, $"M0 恢复调用退出码 0（实得 {rc}）");
                Check(gotOri == "",
                    $"M1 全量复制（-all:all）后产物**不得**带 Orientation（实得「{gotOri}」）"
                  + $"⇒ 修前实测这里就是 8 ⇒ 查看器二次旋转");
                Check(gotMake == "TESTCAM" && gotModel == "TESTMODEL",
                    $"M2 同一次复制必须仍把 Make/Model 带过去（实得 {gotMake}/{gotModel}）"
                  + $"⇒ 证明排除是**逐标签**的，不是把整块复制掐了（否则 M1 会假绿）");

                // ── M3：安全模式同判据 ──
                string prod2 = Path.Combine(dir, "prod_upright_safe.jpg"); created.Add(prod2);
                await Run(ff, $"-y -hide_banner -loglevel error -i \"{src}\" -frames:v 1 -q:v 3 \"{prod2}\"")
                      .ConfigureAwait(false);
                int rc2 = await FfmpegGui.Services.ExifToolService.CopyMetadataSafeAsync(
                    src, prod2, null, absorb: null).ConfigureAwait(false);
                string got2 = await OrientationOf(prod2).ConfigureAwait(false);
                string mk2 = (await Cap(exif, $"-q -s -Make \"{prod2}\"").ConfigureAwait(false))
                                .Split(':').Last().Trim();
                Console.WriteLine($"orientmeta-safe  rc={rc2} Orientation=「{got2}」 Make=「{mk2}」");
                Check(got2 == "" && mk2 == "TESTCAM",
                    $"M3 安全模式（-EXIF:all）同样剥掉 Orientation 且仍带 Make"
                  + $"（实得 Orientation=「{got2}」 Make=「{mk2}」）⇒ 两条恢复通路都得修，漏一条等于没修");

                // ── M4：反证臂——免解码重封装必须**保留**标签（判据有牙的唯一证据）──
                string prod3 = Path.Combine(dir, "prod_rewrap.jpg"); created.Add(prod3);
                await Run(ff, $"-y -hide_banner -loglevel error -i \"{src}\" -frames:v 1 -q:v 3 \"{prod3}\"")
                      .ConfigureAwait(false);
                int rc3 = await FfmpegGui.Services.ExifToolService.CopyMetadataAsync(
                    src, prod3, null, absorb: null, dropOrientation: false).ConfigureAwait(false);
                string got3 = await OrientationOf(prod3).ConfigureAwait(false);
                Console.WriteLine($"orientmeta-rewrap rc={rc3} Orientation=「{got3}」");
                Check(got3 == "8",
                    $"M4 传 dropOrientation:false（重封装路径）时标签必须**留得住**（实得「{got3}」）"
                  + $"⇒ 若这条也变空，说明排除是无条件的 ⇒ 会把真需要取向提示的免解码产物做坏");

                // ── M5：单一判据的行为面 ──
                var oRewrap = new FfmpegGui.Models.FfmpegOptions { Format = "jxl", JxlLosslessJpeg = true };
                var oPlain = new FfmpegGui.Models.FfmpegOptions { Format = "jxl", JxlLosslessJpeg = false };
                bool jpgOn = FfmpegGui.Services.CjxlService.UsesLosslessJpegRewrap(src, oRewrap);
                bool jpgOff = FfmpegGui.Services.CjxlService.UsesLosslessJpegRewrap(src, oPlain);
                bool tifOn = FfmpegGui.Services.CjxlService.UsesLosslessJpegRewrap(
                    Path.Combine(dir, "x.tif"), oRewrap);
                Console.WriteLine($"orientmeta-predicate jpg/on={jpgOn} jpg/off={jpgOff} tif/on={tifOn}");
                Check(jpgOn && !jpgOff && !tifOn,
                    $"M5 重封装判据三格：JPEG+开=true / JPEG+关=false / 非 JPEG+开=false"
                  + $"（实得 {jpgOn}/{jpgOff}/{tifOn}）⇒ 只有这一份实现能同时喂 cjxl 命令行与恢复步骤");
            }
            catch (Exception ex)
            {
                Check(false, $"orientmeta 探针异常：{ex.GetType().Name}: {ex.Message}");
            }
            finally
            {
                int total = 0;
                foreach (var p in created) { try { if (File.Exists(p)) total++; } catch { } }
                int removed = 0;
                foreach (var p in created) { try { if (File.Exists(p)) { File.Delete(p); removed++; } } catch { } }
                bool dirGone = false;
                try
                {
                    if (Directory.Exists(dir) && Directory.GetFileSystemEntries(dir).Length == 0)
                    { Directory.Delete(dir); dirGone = true; }
                }
                catch { }
                Console.WriteLine($"orientmeta-cleanup: 删除文件 {removed}/{total}，目录{(dirGone ? "已" : "未")}删除");
            }
        }
    }
}
