using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Core
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // CoreGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> CoreGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class CoreGroup
    {
        private static FfmpegGui.Services.ColorMapping.TransformSpec Spec(
            string sp, string st, string dp, string dt, bool matrix = true, bool clamp = true)
        {
            var src = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor.FromCicp(sp, st, sp) ?? throw new Exception($"src {sp}/{st}");
            var dst = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor.FromCicp(dp, dt, dp) ?? throw new Exception($"dst {dp}/{dt}");

            // ⚠️ 亮度域换算必须与生产 `ColorTransformPlan.ToSpec()` **同口径**，否则本探针测的根本
            //    不是真实引擎路径：PQ 的 1.0 = 10000nits、HLG = 1000nits、其余 = 203nits（SDR 参考白）。
            //    旧实现两项都留默认 1 ⇒ PQ→sRGB 不做 49× 换算，与 zimg 参照差出 PSNR 7.3dB，
            //    而那笔账长期被当成「zimg 参照口径分歧（PQ 归一约定不同）」豁免 —— 实为**探针自身的
            //    构造缺陷**（它绕过 ToSpec 手搓 spec），不是引擎的口径分歧。
            double Nits(FfmpegGui.Services.ColorMapping.TransferCurve c)
                => c.Kind switch
                {
                    FfmpegGui.Services.ColorMapping.TransferCurve.CurveKind.Pq
                        => FfmpegGui.Services.ColorMapping.TransferCurve.PqPeakNits,
                    FfmpegGui.Services.ColorMapping.TransferCurve.CurveKind.Hlg
                        => FfmpegGui.Services.ColorMapping.Bt2100Ootf.NominalPeakNits,
                    _ => FfmpegGui.Services.ColorMapping.TransferCurve.SdrWhiteNits,
                };
            double sdr = FfmpegGui.Services.ColorMapping.TransferCurve.SdrWhiteNits;

            // ⚠️ 白名单同步：因本缺陷而被判为「口径分歧」的格子，修复后应从 $knownNonDefects 移除，
            //    否则豁免会把真正的回归也一起免掉（门禁就失去牙齿）。见 verify-color-engine-xcheck.ps1。
            return new FfmpegGui.Services.ColorMapping.TransformSpec
            {
                SrcCurve = src.Curve,
                DstCurve = dst.Curve,
                Matrix = matrix ? src.MatrixTo(dst) : null,
                ClampLinearBeforeEncode = clamp,
                LinearScale = Nits(src.Curve) / sdr,
                EncodeScale = sdr / Nits(dst.Curve),
            };
        }

        private static void ProbeContract()
        {
            CS Mk(string prim, string trc, string name, string? icc, DC conf)
            {
                var d = CS.FromCicp(prim, trc, name)!;
                if (icc != null) { d.SourceIccPath = icc; d.IsIccDerived = true; }
                d.Confidence = conf;
                return d;
            }
            var srgbTag = Mk("bt709", "iec61966-2-1", "sRGB(仅标签)", null, DC.CicpTag);
            var srgbIcc = Mk("bt709", "iec61966-2-1", "sRGB(带ICC)", "t.srgb.icc", DC.IccMetric);
            var p3Icc = Mk("smpte432", "iec61966-2-1", "Display P3(带ICC)", "t.p3.icc", DC.IccMetric);
            var pq2020 = CS.FromCicp("bt2020", "smpte2084", "BT.2100 PQ", nitsOfLinearOne: TC.PqPeakNits)!;
            pq2020.Confidence = DC.CicpTag;
            var adobe = CS.FromNamedSpace("Adobe RGB")!; adobe.SourceIccPath = "t.adobe.icc"; adobe.Confidence = DC.IccMetric;
            var prophoto = CS.FromNamedSpace("ProPhoto RGB")!; prophoto.SourceIccPath = "t.prophoto.icc"; prophoto.Confidence = DC.IccMetric;
            var untagged = FfmpegGui.Services.ColorMapping.ColorSpaceIdentify.AssumeByConvention()!;
            // HLG 必须单独成行：它是 scene-referred，与 PQ（display-referred 绝对 nits）的处理路径不同，
            // 共用一行会掩盖“缺 OOTF”这类系统性错误。
            var hlg2020 = CS.FromCicp("bt2020", "arib-std-b67", "BT.2100 HLG", nitsOfLinearOne: 1000.0)!;
            hlg2020.Confidence = DC.CicpTag;

            var sources = new (string Name, CS D)[]
                { ("sRGB仅标签", srgbTag), ("sRGB带ICC", srgbIcc), ("P3带ICC", p3Icc), ("HDR-PQ", pq2020), ("HDR-HLG", hlg2020), ("Adobe带ICC", adobe), ("无标签", untagged) };
            var formats = new[] { "png", "jpg", "tiff", "webp", "avif", "jxl", "gif", "heic" };
            var strategies = new[] { ST.Recommended, ST.CarryIcc, ST.BakeCicpOnly, ST.Manual };

            var viol = new System.Collections.Generic.List<string>();
            var rejectReasons = new System.Collections.Generic.Dictionary<string, int>();
            var rejectByStrategy = new System.Collections.Generic.Dictionary<ST, int>();
            int cells = 0, exempted = 0, rejects = 0;

            CI MakeIntent(ST st, CS src, string fmt, CSC scope)
            {
                var it = new CI
                {
                    Strategy = st, Source = src, Format = CE.CapsFor(fmt), CarryScope = scope,
                    TargetBitDepth = 8, AllowApproximateCurve = false,
                    Manual = st == ST.Manual ? MI.Create(true, "Display P3", "smpte432", "iec61966-2-1", null)
                                             : MI.Create(false, null, null, null, null),
                };
                if (st == ST.Manual) { it.TargetExplicit = true; it.Target = p3Icc; }
                return it;
            }

            foreach (var st in strategies)
                foreach (var fmt in formats)
                    foreach (var (sname, src) in sources)
                    {
                        var it = MakeIntent(st, src, fmt, CSC.All);
                        var p = CE.Plan(it);
                        cells++;
                        var caps = CE.CapsFor(fmt);
                        bool ex = p.Override != OR.None;
                        if (ex) exempted++;
                        if (p.Action == CA.Reject)
                        {
                            rejects++;
                            rejectByStrategy[st] = rejectByStrategy.GetValueOrDefault(st) + 1;
                            var rk = p.Reason.Length > 58 ? p.Reason[..58] : p.Reason;
                            rejectReasons[rk] = rejectReasons.GetValueOrDefault(rk) + 1;
                        }
                        void V(bool ok, string msg) { if (!ok) viol.Add($"[{st}/{fmt}/{sname}] {msg}"); }

                        // 通则：拒绝必带建议；ColorLoss=None 不得伴随像素变更
                        V(p.Action != CA.Reject || p.Advice.Length > 0, "Reject 无 Advice");
                        V(p.ColorLoss != CL.None || (p.Matrix == null && !p.NeedsCurveChange), "ColorLoss=None 却有矩阵/曲线变更");
                        V(p.Annot != AC.IccAndCicp || caps.CanHaveBothIccAndCicp, "标为 ICC+CICP 双描述但容器不支持共存");
                        if (p.Action != CA.Reject)
                            V(p.AttachIcc || p.OutPrimaries != null || p.UnlabeledAssumedSrgb, "产出行无任何标注也未记 UnlabeledAssumedSrgb");
                        if (ex) V(p.Reason.Length > 0, "覆盖格缺覆盖说明（禁止偷偷覆盖）");
                        // 不变量：**同时声明了** CICP 与自生成 ICC 时，两者必须用同一条 TRC。
                        // ⚠ 已用变异测试证明：在 224 格里它是**空转的**（把 IccTrc 改回写死 sRGB 仍 95/0），
                        //   因为所有生成 ICC 的格子要么被“ICC 优先”清了 Out*、要么 IccTrc 为 null。
                        //   它只当未来变更的绊线；本 bug 的真正探测器是 verify-color-wiring (6)（已同样用变异验证过）。
                        // 只管“两条都声明”的行：故意只声明 ICC、不写 CICP 的行（容器非规范性，
                        // ColorStrategyPlanning 在 ICC 定好后清空 Out*）属合法，不构成矛盾。
                        if (p.AttachIcc && p.IccPath == null && p.IccFromGenerator
                            && p.IccTrc != null && p.OutTransfer != null)
                            V(string.Equals(p.IccTrc, p.OutTransfer, StringComparison.OrdinalIgnoreCase),
                              $"ICC 的 TRC({p.IccTrc}) 与输出 TRC({p.OutTransfer}) 不一致");

                        // C1/C2：S2 生效格（含覆盖格）永不改像素、永不生成 ICC
                        if (p.EffectiveStrategy == ST.CarryIcc)
                        {
                            V(p.Backend == CB.None && p.Matrix == null && !p.NeedsCurveChange && !p.IccFromGenerator,
                              "S2 生效格出现像素变更或生成 ICC");
                            V(p.Action is CA.CarryIcc or CA.None or CA.Reject, "S2 出现非法 Action");
                            V(!p.AttachIcc || p.IccPath != null, "S2 附着了非携带的 ICC");
                            // S2 的 Action=None 必须属于两种零改动形态之一（继承 CICP / 隐含 sRGB 无标注）
                            if (p.Action == CA.None)
                                V(p.UnlabeledAssumedSrgb || p.Annot == AC.CicpOnly,
                                  "S2 的 None 必须是「继承源 CICP」或「隐含 sRGB 无标注」");
                            if (p.UnlabeledAssumedSrgb)
                                V(!caps.HasColorPath || caps.UnlabeledMeansSrgb || it.AllowUnlabeled,
                                  "S2 无标注直通，但容器有色彩通路却不允许未标注");
                        }
                        // C2/C3：S3 绝不输出 ICC；无 CICP 容器上只能 None/Reject；可 CICP 容器上必须真写了 CICP
                        if (p.EffectiveStrategy == ST.BakeCicpOnly)
                        {
                            V(!p.AttachIcc && !p.IccFromGenerator && !p.UnlabeledAssumedSrgb || p.UnlabeledAssumedSrgb && !p.AttachIcc,
                              "S3 输出了 ICC");
                            if (!caps.CanCicp && !ex)
                            {
                                V(p.Action is CA.None or CA.Reject, "S3 在无 CICP 容器上映射了像素");
                                if (p.Action == CA.None)
                                    V(caps.UnlabeledMeansSrgb || it.AllowUnlabeled || !caps.HasColorPath,
                                      "S3 在无 CICP 容器上无标注直通，但容器既有色调通路又不在白名单（TIFF 类）");
                            }
                            if (caps.CanCicp && p.Action != CA.Reject && !ex)
                                V(p.OutPrimaries != null, "S3 在可 CICP 容器上却没写 CICP");
                        }
                        // S1：携带与否必须与 CarryScope 定义一致（此处 scope=All）
                        if (p.EffectiveStrategy == ST.Recommended && p.Action == CA.CarryIcc)
                            V(caps.CanCarryArbitraryIcc && src.SourceIccPath != null, "S1 携带了不存在的 ICC/容器不支持");
                    }

            Check(viol.Count == 0, $"contract C1–C4: {cells} 格（覆盖豁免 {exempted} 格、拒绝 {rejects} 格）零违规"
                  + (viol.Count > 0 ? " 例如: " + string.Join(" | ", viol.ConvertAll(s => s).GetRange(0, Math.Min(12, viol.Count))) : ""));

            // HEIF 专项：本工具链**无写入通路**（实测 Unknown format 'heif'），能力表必须全保守；
            // 色彩层对其与 gif/jxr 同类：无色彩通路 ⇒ 只允许“直通+无标注”或 Reject，绝不得声称描述了广色域。
            foreach (var f in new[] { "heic", "heif" })
            {
                var capsH = CE.CapsFor(f);
                Check(!capsH.CanCarryArbitraryIcc && !capsH.CanCicp && !capsH.CanGenerateIccFromCicp,
                    $"{f} 能力表为保守（无写入通路，实测：ffmpeg Unknown format 'heif'）");
                Check(!capsH.HasColorPath, $"{f} 被认定无任何色彩管理通路（HasColorPath=false）");
                // 广色域源：不得产出“看起来标了 P3/2020”的结果
                var pWide = CE.Plan(new CI { Strategy = ST.Recommended, Source = p3Icc, Format = capsH });
                Check(pWide.Action == CA.Reject || pWide.OutPrimaries == null,
                    $"{f} 广色域源不得静默产出厂色域标注（实为 {pWide.Action}/p={pWide.OutPrimaries}）");
                // S2/S3 在无任何通路的容器上只能 Reject 或无标注直通（不能映射）
                var pS2 = CE.Plan(new CI { Strategy = ST.CarryIcc, Source = p3Icc, Format = capsH });
                Check(pS2.Action == CA.Reject || pS2.Matrix == null,
                    $"{f} + S2：要么 Reject 要么像素零改动（实为 {pS2.Action}）");
            }

            // C4c HLG 专项：**无 HDR 通路**的容器上不得“默默按 PQ 方式压暗”，必须 Reject；
            // 确实请求 tonemap 时，必须把“OOTF 未标定”写进建议（已知缺口可见，而不是隐性错）。
            // ⚠ **2026-09-16 契约更新**：`png`/`apng` **有** HDR 通路（经 **cICP**）——
            //   两条管线的 HDR→PNG 产物实测都写着 `smpte2084,bt2020`，且**逐字节相同**。
            //   故它们不再属于"无 HDR 通路"组，改列正向断言（否则本断言锁的是过时的能力表）。
            foreach (var f in new[] { "tiff", "webp", "gif" })
            {
                var hp = CE.Plan(new CI { Strategy = ST.Recommended, Source = hlg2020, Format = CE.CapsFor(f) });
                Check(hp.Action == CA.Reject, $"HLG × {f}：无 HDR 通路 ⇒ Reject（实为 {hp.Action}）");
            }
            foreach (var f in new[] { "png", "apng" })
            {
                var hp = CE.Plan(new CI { Strategy = ST.Recommended, Source = hlg2020, Format = CE.CapsFor(f) });
                Check(hp.Action != CA.Reject, $"HLG × {f}：有 cICP 通路 ⇒ 不得 Reject（实为 {hp.Action}）");
                Check(CE.CapsFor(f).CanHdr, $"{f} 的能力表须标 CanHdr=true（HDR 经 cICP 承载）");
            }
            foreach (var f in new[] { "avif", "jxl" })
            {
                var hh = CE.Plan(new CI { Strategy = ST.Recommended, Source = hlg2020, Format = CE.CapsFor(f) });
                Check(hh.Matrix == null && hh.ColorLoss == CL.None,
                    $"HLG × {f}：默认保持 HDR、不改像素（实为 {hh.Action}/{hh.ColorLoss}）");
                var ht = CE.Plan(new CI { Strategy = ST.Recommended, Source = hlg2020, Format = CE.CapsFor(f),
                                           HdrOutput = false, ToneMapRequested = true, ToneMap = FfmpegGui.Services.ColorMapping.ToneMapMode.Mobius });
                Check(ht.Tone is { Active: true } && ht.Advice.Contains("OOTF"),
                    $"HLG × {f} + 请求 tonemap：必须声明 OOTF 未标定（Advice={ht.Advice}）");
            }

            // C4b GainMap 专项：它是“输出结构”能力（JPEG 的 APP2/MPF，或 AVIF 的 ISO-BMFF `tmap` 派生项），
            // 不是色调曲线；UI 的 IsVisible 不算门禁——契约层必须自拦，否则变成“以为有 HDR、实则被压暗”的静默降级。
            // ⚠ 2026-10-02：**avif 已移出本负控清单**（tmap 派生项写出已落地，三路验证见
            //   `docs/AVIF_GAINMAP_ENCODER_2026-10-02.md`）⇒ 负控**只剩 6 个格式、不得为空**；
            //   同时新增 avif 的**正向**断言（不得 Reject + 能力表位为真），把新旧口径各钉一颗牙。
            foreach (var f in new[] { "png", "tiff", "webp", "jxl", "gif", "heic" })
            {
                var gm = CE.Plan(new CI { Strategy = ST.Recommended, Source = pq2020, Format = CE.CapsFor(f), GainMapRequested = true });
                Check(gm.Action == CA.Reject && gm.Advice.Length > 0,
                    $"GainMap × {f}：必须 Reject+建议（实为 {gm.Action}）");
            }
            {
                var capsA = CE.CapsFor("avif");
                Check(capsA.SupportsGainMap, "avif 能力表须标记 SupportsGainMap（ISO-BMFF tmap 派生项）");
                var gmAvif = CE.Plan(new CI { Strategy = ST.Recommended, Source = pq2020, Format = capsA, GainMapRequested = true });
                Check(gmAvif.Action != CA.Reject,
                    $"GainMap × avif：已支持 tmap 派生项 ⇒ 不得 Reject（实为 {gmAvif.Action}）");
            }
            foreach (var f in new[] { "jpg", "jpeg", "jpegli" })
            {
                var capsG = CE.CapsFor(f);
                Check(capsG.SupportsGainMap, $"{f} 能力表标记 SupportsGainMap");
                var s2g = CE.Plan(new CI { Strategy = ST.CarryIcc, Source = pq2020, Format = capsG, GainMapRequested = true });
                Check(s2g.Override == OR.GainMapRequiresBaseMapping && s2g.EffectiveStrategy != ST.CarryIcc,
                    $"GainMap × {f}：S2 被显式覆盖为 {s2g.EffectiveStrategy}（原因 {s2g.Override}）");
            }
            // 正向（**2026-09-16 契约更新**）：GainMap 已接入引擎 ⇒ JPEG 族的**有效**任务不得被规划层拒。
            // 用「HDR 源 + 显式 tonemap」是刻意的：这正是 `ColorIntentFactory` 对 HDR→JPEG 的真实装配
            //（`!caps.CanHdr` ⇒ 自动 hable），而 GainMap 的主用途正是「HDR 底图 → SDR 底图 + 增益图」。
            // 第二条把覆盖原因 `GainMapRequiresBaseMapping` 的**承诺**钉住：底图必须真的被映射（Action=Map），
            // 而不是"记了个原因却直通"。
            {
                var gmOk = CE.Plan(new CI { Strategy = ST.Recommended, Source = pq2020, Format = CE.CapsFor("jpg"),
                                            GainMapRequested = true, ToneMapRequested = true,
                                            ToneMap = FfmpegGui.Services.ColorMapping.ToneMapMode.Hable, HdrPeakNits = 1000 });
                Check(gmOk.Action != CA.Reject, $"GainMap × jpg + 显式 tonemap ⇒ 不得 Reject（实为 {gmOk.Action}）");
                Check(gmOk.Action == CA.Map, $"GainMap × jpg：底图确实被映射（Action={gmOk.Action}，兑现 GainMapRequiresBaseMapping）");
            }

            // C4d 色域压缩（GMO）专项（**2026-09-17 新增**）：`--color-gamut-map on` 的语义此前**零覆盖**。
            // 本组把「开关 → 决策 → 后端」三段钉在同一处（纯函数，无 IO）。
            // 刻意选 **BT.2020(SDR) → Display P3** 这一对：两侧都能按 CICP 命名（`h2Possible=true`）
            // ⇒ **越界本身**并不强制进程内后端；只有开了开关（`needsGmo`）才强制。
            // 这样才能用一个开关把「决策」与「后端」两条断言同时钉住 —— 若用 Adobe RGB 这类不可命名的源，
            // 后端恒为 InProcess，负控就变成空转。
            {
                var b2020 = CS.FromCicp("bt2020", "bt709", "BT.2020(SDR)")!;
                b2020.Confidence = DC.CicpTag;

                var gmo = MakeIntent(ST.Manual, b2020, "png", CSC.All);
                gmo.AllowGamutCompression = true;
                var pg = CE.Plan(gmo);
                Check(pg.Action != CA.Reject && pg.GamutOutsideDestination && pg.GamutMap,
                    $"GMO 正向前置：BT.2020 → Display P3 越界 + 开关开 ⇒ GamutMap 必须置位（实为 {pg.Action}/{pg.GamutMap}）");
                Check(pg.ColorLoss == CL.GamutCompression,
                    $"GMO 正向：开关开 + 源越界 ⇒ ColorLoss 必须为 {CL.GamutCompression}（实为 {pg.ColorLoss}）");
                Check(pg.Backend == CB.InProcess,
                    $"GMO 正向：色域压缩只能由进程内内核执行 ⇒ 后端必须为 {CB.InProcess}（实为 {pg.Backend}）");

                // 负控：只把**开关关掉**（其余一字不动）⇒ 必须回到 Clipping + zscale 后端。
                var clip = MakeIntent(ST.Manual, b2020, "png", CSC.All);
                clip.AllowGamutCompression = false;
                var pc = CE.Plan(clip);
                Check(pc.GamutOutsideDestination && !pc.GamutMap && pc.ColorLoss == CL.Clipping,
                    $"GMO 负控：开关关 ⇒ 必须回到 {CL.Clipping} 且 GamutMap=false（实为 {pc.ColorLoss}/{pc.GamutMap}）");
                // ⚠⚠ 2026-10-05：H2 死后端已删除 ⇒ 原先「越界本身不强制进程内后端」这条
                //   （其写法是"H2 应被选中"）作废。改判**新契约**：本档一律 `InProcess`；
                //   而本条真正要守的语义（"越界**本身**不应触发 GMO 压缩"）由上面那条
                //   `GamutMap=false` + `ColorLoss=Clipping` 断言继续承担，语义未丢。
                Check(pc.Backend != CB.FfmpegFilter,
                    $"GMO 负控：H2 已删除（2026-10-05）⇒ 不得再选到 H2（实为 {pc.Backend}）");
            }

            // C4c 策略覆盖留痕（**2026-09-16 新增**）：GainMap 接入引擎后，S3/S4 两格若不被覆盖就会
            // 被规划层 Reject（S3：JPEG 无 CICP 承载通路；S4：无显式目标），而基线（旧专用管线）**有产出**
            // ⇒ 那是功能回退。故 §2 覆盖① 从「仅 S2」扩展到**三条非 S1 策略**（S2 已在上面覆盖）。
            // 这组断言把「覆盖必须发生 **且** 必须留痕 **且** 不得改写声明值」钉住 —— 只靠
            // verify-color-strategy 的产出断言是间接的：覆盖被悄悄去掉时它不会立刻转红。
            {
                var capsJpg = CE.CapsFor("jpg");
                // ⚠ 必须带上 tonemap 请求：HDR 源 + SDR 容器若**不显式请求** tonemap，规划层会因另一条
                //   独立且正确的规则（"HDR 源 → SDR 结局需显式请求 tonemap"）Reject —— 那会**掩盖**本组
                //   要测的策略覆盖（首版断言就因此假红）。真实装配路径 `ColorIntentFactory` 对 HDR→JPEG
                //   本来就会自动置 tonemap（`!caps.CanHdr`），所以带上它才是忠实的构造。
                const double kPeak = 1000;
                // S3（仅 CICP）：JPEG 结构上不可能兑现 —— 无 CICP 承载通路，底图色域只能由底图 ICC 表达。
                var s3g = CE.Plan(new CI { Strategy = ST.BakeCicpOnly, Source = pq2020, Format = capsJpg,
                                           GainMapRequested = true, ToneMapRequested = true,
                                           ToneMap = FfmpegGui.Services.ColorMapping.ToneMapMode.Hable, HdrPeakNits = kPeak });
                Check(s3g.Action != CA.Reject, $"GainMap × jpg × S3：不得 Reject（实为 {s3g.Action}）");
                Check(s3g.Override == OR.GainMapRequiresBaseMapping,
                    $"GainMap × jpg × S3：覆盖原因必须是 {OR.GainMapRequiresBaseMapping}（实为 {s3g.Override}）");
                Check(s3g.EffectiveStrategy == ST.Recommended,
                    $"GainMap × jpg × S3：生效策略应为 {ST.Recommended}（实为 {s3g.EffectiveStrategy}）");
                Check(s3g.DeclaredStrategy == ST.BakeCicpOnly,
                    $"GainMap × jpg × S3：**声明值必须原样保留**（实为 {s3g.DeclaredStrategy}）");
                // S4（手动但未给任何字段）：目标由 JpegGainMapBaseGamut 决定 ⇒「没有显式目标」不是错误。
                var s4g = CE.Plan(new CI { Strategy = ST.Manual, Source = pq2020, Format = capsJpg,
                                           GainMapRequested = true, ToneMapRequested = true,
                                           ToneMap = FfmpegGui.Services.ColorMapping.ToneMapMode.Hable, HdrPeakNits = kPeak,
                                           Manual = FfmpegGui.Services.ColorMapping.ManualIntent.Create(false, null, null, null, null) });
                Check(s4g.Action != CA.Reject, $"GainMap × jpg × S4：不得 Reject（实为 {s4g.Action}）");
                Check(s4g.Override == OR.GainMapRequiresBaseMapping,
                    $"GainMap × jpg × S4：覆盖原因必须是 {OR.GainMapRequiresBaseMapping}（实为 {s4g.Override}）");
                // 负控（**关键**）：同样的 S3 + tonemap 但**不请求 GainMap** ⇒ 不得出现该覆盖。
                // 否则「非 S1 一律被覆盖」这种退化实现也能让上面 5 条全绿 ⇒ 它们就成了空转。
                var s3n = CE.Plan(new CI { Strategy = ST.BakeCicpOnly, Source = pq2020, Format = capsJpg,
                                           GainMapRequested = false, ToneMapRequested = true,
                                           ToneMap = FfmpegGui.Services.ColorMapping.ToneMapMode.Hable, HdrPeakNits = kPeak });
                Check(s3n.Override != OR.GainMapRequiresBaseMapping,
                    $"负控：S3 × jpg **不请求 GainMap** ⇒ 不得出现 {OR.GainMapRequiresBaseMapping}（实为 {s3n.Override}）");
            }

            // C12 PNG 标注策略：ICC/CICP 取舍由**四大策略**决定（纯函数，无 IO）。
            // 规范前提（PNG Third Edition）：优先级 cICP=1 > iCCP=2；且无 cICP 时至多一个 profile
            // ⇒ cICP 与 iCCP 允许并存，关键在“ICC 是谁的”。
            {
                // ⚠ 不得把枚举装成 object 再 ==（装箱后是引用相等，永远 false 且不报错）；
                //   也不能 `var X = SomeEnumType;`（类型不是值）⇒ 取实际成员作为局部常量。
                var W = FfmpegGui.Services.PngCicpService.PngLabelAction.WriteCicp;
                var SkipSrc = FfmpegGui.Services.PngCicpService.PngLabelAction.SkipSourceIcc;
                var SkipUn = FfmpegGui.Services.PngCicpService.PngLabelAction.SkipUnnameable;
                var SkipLabeled = FfmpegGui.Services.PngCicpService.PngLabelAction.SkipAlreadyLabeled;
                FfmpegGui.Services.PngCicpService.PngLabelAction DL(ST s, bool iccp, bool cicp, bool src, bool stdIcc, bool nameable)
                    => FfmpegGui.Services.PngCicpService.DecideLabel(s, iccp, cicp, src, stdIcc, nameable);
                Check(DL(ST.Recommended, false, false, false, false, true) == W,
                    "S1 无 ICC 且可命名 ⇒ 写 cICP");
                Check(DL(ST.Recommended, true, false, false, false, true) == W,
                    "S1 带自生成标准 ICC ⇒ 仍写 cICP（与 ICC 同义，并写安全）");
                Check(DL(ST.CarryIcc, true, false, false, true, true) == W,
                    "S2 源只有 ICC、但该 ICC 是标准色彩空间⇒ 写 cICP（两者同义，不丢精度）");
                Check(DL(ST.CarryIcc, true, false, false, false, true) == SkipSrc,
                    "S2 源只有 ICC、且 ICC 非标准（色度未命中）⇒ 不写（猜出的 cICP 会降级源 ICC）");
                Check(DL(ST.CarryIcc, true, false, true, false, true) == W,
                    "S2 且源自带 CICP ⇒ 必须携带（ICC+CICP 一起带，丢掉就是丢信息）");
                Check(DL(ST.CarryIcc, false, false, false, false, true) == W,
                    "S2 但源无 ICC ⇒ 写 cICP（契约里的“零改动直通/继承标签”）");
                Check(DL(ST.BakeCicpOnly, true, false, false, false, true) == W,
                    "S3 仅CICP ⇒ 必写 cICP（残留 iCCP 由调用方另行告警）");
                Check(DL(ST.Manual, true, false, false, false, true) == W,
                    "S4 手动 ⇒ 可命名即写（用户担保）");
                // 反向护栏：证明参数真在起作用，而不是恒真断言
                Check(DL(ST.Recommended, true, false, false, false, false) == SkipUn,
                    "不可命名（ProPhoto/Adobe）⇒ 宁缺勿错，ICC 作唯一描述");
                Check(DL(ST.Manual, false, true, false, false, true) == SkipLabeled,
                    "已有 cICP ⇒ 不重复写、不覆盖");
                Check(DL(ST.BakeCicpOnly, true, false, false, false, true) == W,
                    "S3 即使源无 CICP 也写（本意就是只留 CICP）");
                // ICC 曲线 → CICP 令牌：仅当与标准曲线等价才命名（不猜）。本文件已有 TC = TransferCurve 别名。
                Check(FfmpegGui.Services.FfmpegCommandBuilder.CicpTokenOfCurve(TC.Srgb) == "iec61966-2-1",
                    "曲线 sRGB ⇒ iec61966-2-1");
                Check(FfmpegGui.Services.FfmpegCommandBuilder.CicpTokenOfCurve(TC.Pq) == "smpte2084",
                    "曲线 PQ ⇒ smpte2084");
                Check(FfmpegGui.Services.FfmpegCommandBuilder.CicpTokenOfCurve(TC.Hlg) == "arib-std-b67",
                    "曲线 HLG ⇒ arib-std-b67");
                Check(FfmpegGui.Services.FfmpegCommandBuilder.CicpTokenOfCurve(TC.Gamma28) == null,
                    "γ2.8 无标准对应 ⇒ 不命名（不猜）");
                Check(FfmpegGui.Services.FfmpegCommandBuilder.CicpTokenOfCurve(null) == null,
                    "null 曲线（非中性/无法解析 profile）⇒ 不命名");
            }

            // C5 开关鲁棒性：三档 carry-scope 下关键格行为与定义一致，且契约仍成立
            static bool ScopeAllows(CSC sc, CS src) => sc switch
            {
                CSC.None => false,
                CSC.Unnameable => !src.IsCicpNameable,
                _ => true,
            };
            foreach (var scope in new[] { CSC.None, CSC.Unnameable, CSC.All })
                foreach (var (src, fmt) in new[] { (adobe, "png"), (prophoto, "avif"), (p3Icc, "tiff"), (srgbIcc, "png") })
                {
                    var it = MakeIntent(ST.Recommended, src, fmt, scope);
                    var p = CE.Plan(it);
                    bool carries = p.Action == CA.CarryIcc;
                    bool expect = CE.CapsFor(fmt).CanCarryArbitraryIcc && src.SourceIccPath != null && ScopeAllows(scope, src);
                    Check(carries == expect, $"C5 scope={scope} {src.Name}→{fmt}: carry={carries} 预期 {expect}（{p.Reason}）");
                    Check(p.Matrix == null || p.Action == CA.Map, $"C5 scope={scope} {src.Name}→{fmt}: 非映射格不得带矩阵");
                }

            // C6 确定性（同意图两次规划结果必须一致）；完整“直接路径 vs cjxl 管道”同构待 P7 接线后补
            for (int i = 0; i < 2; i++)
            {
                var a = CE.Plan(MakeIntent(ST.Recommended, p3Icc, "avif", CSC.All));
                var b = CE.Plan(MakeIntent(ST.Recommended, p3Icc, "avif", CSC.All));
                Check(a.Action == b.Action && a.Annot == b.Annot && a.ColorLoss == b.ColorLoss
                      && ((a.Matrix == null) == (b.Matrix == null)) && a.OutPrimaries == b.OutPrimaries,
                    "C6 同一 ColorIntent 两次规划结果一致（确定性）");
            }
            // C7 H2 口径黑名单：目标曲线 bt709/bt470bg/smpte240m 在 Std 口径下不得交给 H2；Zimg 口径下允许（对齐历史）
            var b709sdr = CS.FromCicp("bt709", "bt709", "BT.709 SDR");
            var p3b = CS.FromCicp("smpte432", "iec61966-2-1", "Display P3");
            if (b709sdr != null && p3b != null)
            {
                var polForce = new FfmpegGui.Services.ColorMapping.PlanPolicy
                { AllowApproximateCurve = false, ForceMapping = true, TargetExplicit = true };
                var pStd = CE.Plan(p3b, b709sdr, polForce);
                Check(pStd.Backend != CB.FfmpegFilter,
                    $"C7 Std 口径：目标 bt709 不得走 H2（实为 {pStd.Backend}）{pStd.Reason}");
                var polZ = new FfmpegGui.Services.ColorMapping.PlanPolicy
                { AllowApproximateCurve = false, ForceMapping = true, TargetExplicit = true, Transfer709 = F709.Zimg };
                var pZ = CE.Plan(p3b, b709sdr, polZ);
                // ⚠⚠ 2026-10-05：H2 死后端已**删除**（见 `ColorTransformPlan` 后端选择处的长注释）⇒
                //   原先「Zimg 口径允许回退到 H2 对齐历史产物」与「对照：非黑名单目标仍可走 H2」
                //   两条契约**随之作废**（H2 不再可达）。此处改判**新契约**：
                //   无论口径是否对齐 zimg，后端一律 `InProcess`（H1）—— 即"本档不存在 H2 执行体"。
                //   ⚠ 这不是"为绿而放宽"：断言的方向从"H2 应当被选中"改成"**H2 不得再出现**"，
                //     仍然是有牙的（若有人恢复 H2 置位，本条立刻转红）。
                Check(pZ.Backend != CB.FfmpegFilter,
                    $"C7 Zimg 口径：H2 已删除（2026-10-05）⇒ 不得再选到 H2（实为 {pZ.Backend}）");
                // 对照：非黑名单目标同样不得走 H2
                var pOk = CE.Plan(p3b, srgbTag, polForce);
                Check(pOk.Backend != CB.FfmpegFilter,
                    $"C7 对照：H2 已删除 ⇒ 任何目标都不得走 H2（实为 {pOk.Backend}）");
            }

            // C7b —— 缺陷 #29 的**行为锁**（此前只有 C7 那条结构锁，而像素从头到尾没被这个开关碰过）：
            //   `--color-709-curve` 在**结构上必须走 H1** 的格子里，std 与 zimg 曾拿到**逐字节相同**的产物
            //   （2026-09-26 实测四格 × {std,zimg} 全数同 md5）⇒ 用户显式选了口径却是静默无效参数。
            //   本段量的是**真像素**（Plan → ToSpec → ColorKernels，与 QueueProcessor.cs:1090 同一条链），
            //   差量级按实测的曲线分歧给**上下界**，不写"不同即可"那种没牙的断言：
            //     · zimg 的 bt709 = 纯 γ(1/2.4)，与 ITU-R BT.709-6 定义式的编码差在 linear≈0.0169 处
            //       取最大 = **6986 LSB@16bit ≈ 27.2 LSB@8bit**（本轮按两条定义式自算；
            //       zscale 实测值 7231 LSB@16bit 与之差 245 ≈ 1 LSB@8bit 的量化地板，同源同向）。
            //   ⚠ 前提条件也断言：两格都**必须**落在 H1（BT.2020 ⊄ BT.709 ⇒ 开 GMO ⇒ needsGmo ⇒ 后端与口径
            //     无关），否则比较的对象变成"我们的曲线 vs zscale 的曲线"，本断言就测不到我们要测的东西。
            {
                var lin2020 = CS.FromCicp("bt2020", "linear", "BT.2020(线性源)");
                var bt709Sdr = CS.FromCicp("bt709", "bt709", "BT.709 SDR");
                var srgbDst2 = CS.FromCicp("bt709", "iec61966-2-1", "sRGB 目标");
                if (lin2020 != null && bt709Sdr != null && srgbDst2 != null)
                {
                    FfmpegGui.Services.ColorMapping.PlanPolicy Pol709(bool zimg, bool gmo = true)
                        => new()
                        {
                            Format = CE.CapsFor("png"),
                            AllowApproximateCurve = false, ForceMapping = true, TargetExplicit = true,
                            AllowGamutCompression = gmo, TargetBitDepth = 8,
                            Transfer709 = zimg ? F709.Zimg : F709.Std,
                        };
                    var c7bStd = CE.Plan(lin2020, bt709Sdr, Pol709(false));
                    var c7bZim = CE.Plan(lin2020, bt709Sdr, Pol709(true));
                    Check(c7bStd.Backend == CB.InProcess && c7bZim.Backend == CB.InProcess,
                        $"C7b 前提：两格都必须落在 H1（实 std={c7bStd.Backend} / zimg={c7bZim.Backend}）");

                    var spStd = c7bStd.ToSpec(); var spZim = c7bZim.ToSpec();
                    Check(spStd.DstCurve.Equivalent(TC.Bt709) && !spZim.DstCurve.Equivalent(TC.Bt709)
                          && Math.Abs(spZim.DstCurve.G - 2.4) < 1e-12 && spZim.DstCurve.C == 0.0 && spZim.DstCurve.D == 0.0,
                          $"C7b 结构：zimg 的出口曲线必须是纯 γ(1/2.4)（实={spZim.DstCurve.Name}），std 仍是定义式（实={spStd.DstCurve.Name}）");
                    // 口径只改**像素**，不改**标注**：这是"对齐历史产物"的字面语义（zscale 的产物也一直
                    // 是 t=bt709 标签 + γ2.4 像素）。⚠ 反过来也必须成立：这条曲线自己**不**声称可 CICP 命名。
                    Check(spZim.DstCurve.CicpToken == null && spZim.DstCurve.TableLength == 0
                          && c7bZim.OutTransfer == "bt709" && c7bStd.OutTransfer == "bt709"
                          && c7bZim.IccTrc == "bt709" && c7bStd.IccTrc == "bt709"
                          && c7bZim.AttachIcc == c7bStd.AttachIcc,
                          $"C7b 标注不随口径走：zimg 曲线 CicpToken=null（不发明命名），CICP 与 ICC 仍 bt709"
                        + $"（实 t={c7bZim.OutTransfer}/{c7bStd.OutTransfer} icc={c7bZim.IccTrc ?? "-"}/{c7bStd.IccTrc ?? "-"}）");

                    // 65536 级**线性**灰阶：源曲线=linear ⇒ 输入码值就是线性值，两条出口曲线的取差点
                    // （linear≈0.0169）必被采到；R=G=B ⇒ GMO 对中性色严格 no-op（见 GamutMapScalar 的性质），
                    // 于是 16bit 差值里只剩"曲线口径"这一项，没有别的算子混进来。
                    const int n709 = 65536;
                    var in709 = new byte[n709 * 6];
                    for (int i = 0; i < n709; i++)
                    {
                        ushort v = (ushort)i;
                        for (int c = 0; c < 3; c++) { in709[i * 6 + c * 2] = (byte)(v & 0xFF); in709[i * 6 + c * 2 + 1] = (byte)(v >> 8); }
                    }
                    var oStd = new byte[n709 * 6]; var oZim = new byte[n709 * 6];
                    var oStd2 = new byte[n709 * 6]; var oZim2 = new byte[n709 * 6];
                    CK.TransformRgb48le(in709, oStd, spStd, n709);
                    CK.TransformRgb48le(in709, oZim, spZim, n709);
                    CK.TransformRgb48le(in709, oStd2, spStd, n709);
                    CK.TransformRgb48le(in709, oZim2, spZim, n709);
                    Check(oStd.AsSpan().SequenceEqual(oStd2) && oZim.AsSpan().SequenceEqual(oZim2),
                        "C7b 反向（确定性）：同口径两跑必须逐字节相同（std/zimg 各两跑；防 RNG/抖动混进口径差里）");
                    bool same16 = oStd.AsSpan().SequenceEqual(oZim);
                    int max16 = 0; long sum16 = 0;
                    for (int i = 0; i + 1 < oStd.Length; i += 2)
                    {
                        int d = Math.Abs((oStd[i] | (oStd[i + 1] << 8)) - (oZim[i] | (oZim[i + 1] << 8)));
                        if (d > max16) max16 = d;
                        sum16 += d;
                    }
                    Check(!same16 && max16 >= 6900 && max16 <= 7100,
                        $"C7b 行为（16bit）：std vs zimg 必须**产物不同**且最大差落在 6986±100 LSB@16bit"
                      + $"（实 相同={same16} max={max16} mean={(double)sum16 / (n709 * 3):F1}）—— 静默无效或把曲线换错都拦");

                    // 同一条差换算到 8bit 出口（本工具最常见的产物位深）。⚠ 这里显式关掉有序抖动：
                    // 本断言量的是**口径差本身**，±1 LSB 的抖动不该进上下界（抖动的一致性由 C10/C11 守）。
                    var sp8Std = c7bStd.ToSpec(); sp8Std.Dither = FfmpegGui.Services.ColorMapping.DitherMode.None;
                    var sp8Zim = c7bZim.ToSpec(); sp8Zim.Dither = FfmpegGui.Services.ColorMapping.DitherMode.None;
                    var b8Std = new byte[n709 * 3]; var b8Zim = new byte[n709 * 3];
                    CK.TransformRgb48leToRgb8(in709, b8Std, sp8Std, n709, null, null, n709, 0);
                    CK.TransformRgb48leToRgb8(in709, b8Zim, sp8Zim, n709, null, null, n709, 0);
                    int max8 = 0; long sum8 = 0;
                    for (int i = 0; i < b8Std.Length; i++)
                    {
                        int d = Math.Abs(b8Std[i] - b8Zim[i]);
                        if (d > max8) max8 = d;
                        sum8 += d;
                    }
                    double mean8 = (double)sum8 / b8Std.Length;
                    Check(max8 >= 25 && max8 <= 30 && mean8 >= 9.0 && mean8 <= 15.0,
                        $"C7b 行为（8bit）：最大差应落在 27±3 LSB、均值 11.8±3 LSB（实 max={max8} mean={mean8:F2}）"
                      + "⇒ 量级对得上实测分歧，不是末位抖动");

                    // ── "不许静默"那一半：兑现要点名兑现，兑现不了要点名原因（可用性诚实）──
                    Check(c7bZim.Reason.Contains("已兑现(H1)"),
                        $"C7b 点名：zimg 在 H1 格必须声明已兑现（实 Reason={c7bZim.Reason}）");
                    Check(!c7bStd.Reason.Contains("口径=zimg"),
                        "C7b 反向：std（=默认值）不逐格播报，避免把日志变成噪声");
                    // H2 格（放行 zscale 的那条）也必须点名，且说清"由 zscale 兑现"而不是"由我们换曲线"
                    var p3lin2 = CS.FromCicp("smpte432", "iec61966-2-1", "Display P3(标签)");
                    if (p3lin2 != null)
                    {
                        var c7bH2 = CE.Plan(p3lin2, bt709Sdr, Pol709(true, gmo: false));
                        // ⚠⚠ 2026-10-05：H2 死后端已删除 ⇒ 原「H2 格要说清口径由 zscale 兑现」作废。
                        //   改判**新契约**：该格一律走 H1，且必须**点名"已兑现(H1)"**
                        //   （而不是留着一条 H2 文案挂在一个不存在的执行体上）。
                        Check(c7bH2.Backend != CB.FfmpegFilter && c7bH2.Reason.Contains("已兑现(H1)"),
                            $"C7b 点名：H2 已删除 ⇒ 本格走 H1 且须点名「已兑现(H1)」（实 backend={c7bH2.Backend} Reason={c7bH2.Reason}）");
                    }
                    var c7bNa = CE.Plan(lin2020, srgbDst2, Pol709(true));
                    Check(c7bNa.Action == CA.Map && c7bNa.Reason.Contains("与 BT.709 编码口径无关"),
                        $"C7b 点名不适用：目标是 sRGB 曲线 ⇒ 必须说明为何本开关不适用（act={c7bNa.Action} 实 Reason={c7bNa.Reason}）");
                    var polGm709 = Pol709(true); polGm709.GainMapRequested = true;
                    var c7bGm = CE.Plan(lin2020, bt709Sdr, polGm709);
                    Check(c7bGm.Reason.Contains("GainMap 出口"),
                        $"C7b 点名不适用：GainMap 出口不消费计划层曲线 ⇒ 必须点名（实 Reason={c7bGm.Reason}）");
                    var c7bNone = CE.Plan(lin2020, null, Pol709(true));
                    // ⚠ 只查"不改像素"没有牙：那四个字在**基础理由**里就有（"无目标色彩空间 → 不改像素，沿用源描述"），
                    //   把 Transfer709Note 的不适用点名整段删掉它也照样绿（实测：见下方注释的短语才是点名独有）。
                    //   故额外锁一条**只可能来自点名文本**的短语 —— 缺陷 #29 的"不许静默"就是这一条在守。
                    Check(c7bNone.Action == CA.None && c7bNone.Reason.Contains("不改像素")
                          && c7bNone.Reason.Contains("没有出口编码可换曲线"),
                        $"C7b 点名不适用：无目标（不改像素）⇒ 必须点名（act={c7bNone.Action} 实 Reason={c7bNone.Reason}）");
                    // 未验证的 zimg 形态不得被"顺手发明"成曲线：bt470bg/smpte240m 只放行 H2，不换出口曲线
                    var bt470bgDst = CS.FromCicp("bt709", "bt470bg", "BT.709 原色 + γ2.8 传递");
                    var smpte240Dst = CS.FromCicp("bt709", "smpte240m", "BT.709 原色 + SMPTE 240M 传递");
                    var p3ForToken = CS.FromCicp("smpte432", "linear", "Display P3(线性源)");
                    foreach (var dUnverified in new[] { bt470bgDst, smpte240Dst })
                    {
                        if (dUnverified == null || p3ForToken == null) { Check(false, "C7b 前提：bt470bg/smpte240m 或 P3(线性) 描述符不可用"); continue; }
                        var c7bUv = CE.Plan(p3ForToken, dUnverified, Pol709(true, gmo: false));
                        Check(c7bUv.DstCurve != null && !c7bUv.DstCurve.Value.Equivalent(TC.Bt709Zimg)
                              && c7bUv.ToSpec().DstCurve.Equivalent(dUnverified.Curve)
                              && c7bUv.Reason.Contains("未实测"),
                            $"C7b 不发明曲线：{dUnverified.TransferToken} 的 zimg 形态未验证 ⇒ 出口曲线仍是本仓那条"
                          + $"（实 dst={c7bUv.ToSpec().DstCurve.Name}）{c7bUv.Reason}");
                    }
                    // ── 上面那条量的是"计划有没有换曲线"（行为）；这条量"可用表本身长什么样"（字面）──
                    // ⚠ 正向对照（bt709 必须给出曲线）与两条 null 一起写：只写 null 那两条的话，
                    //   `ZimgExitCurve` 退化成"永远返回 null"（开关整个失效）也会让它俩假绿。
                    // ServiceProbe 不在 FfmpegGui 的 InternalsVisibleTo 名单里（改 csproj 会炸还原），
                    // 故与取私有字段的既有做法一致：NonPublic|Static 反射，取不到方法就判红。
                    var zecMi = typeof(CE).GetMethod("ZimgExitCurve",
                        System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
                    if (zecMi == null)
                        Check(false, "C7b 可用表字面锁：反射取不到 ColorMappingEngine.ZimgExitCurve（改名/改可见性 ⇒ 锁静默失效）");
                    else
                    {
                        Check(zecMi.Invoke(null, new object?[] { "bt709" }) is TC zec709 && zec709.Equivalent(TC.Bt709Zimg),
                            "C7b 可用表字面锁：ZimgExitCurve(\"bt709\") 必须给出 zimg 形态（正向对照，拦\"永远 null\"式退化）");
                        Check(zecMi.Invoke(null, new object?[] { "bt470bg" }) == null,
                            "C7b 可用表字面锁：ZimgExitCurve(\"bt470bg\") 必须为 null（未实测 ⇒ 不换曲线，也不为凑绿发明曲线）");
                        Check(zecMi.Invoke(null, new object?[] { "smpte240m" }) == null,
                            "C7b 可用表字面锁：ZimgExitCurve(\"smpte240m\") 必须为 null（未实测 ⇒ 不换曲线，也不为凑绿发明曲线）");
                    }
                }
                else Check(false, "C7b 前提描述符不可用（bt2020/linear、bt709/bt709、sRGB 之一为 null）");
            }

            // C8 单入口检测器：必须抓到真入口，且**不得误杀**标注工具（iccgen/format/纯缩放/CLI 标注选项）
            var pH1 = new FfmpegGui.Services.ColorMapping.ColorTransformPlan { Action = CA.Map, Backend = CB.InProcess };
            var pCarry = new FfmpegGui.Services.ColorMapping.ColorTransformPlan { Action = CA.CarryIcc, Backend = CB.None };
            var pNoop = new FfmpegGui.Services.ColorMapping.ColorTransformPlan { Action = CA.None, Backend = CB.None };
            // ⚠⚠ 2026-10-05：原有一条合成用例 `pH2 = { Action=Map, Backend=FfmpegFilter }` 用来测
            //   「H2 计划下出现两条色彩入口要被抓到」。H2 死后端删除后，`FindPixelColorEntry`
            //   新增了**反向自检**（置位 H2 ⇒ 直接返回"置位与执行体不匹配"）⇒ 该合成用例
            //   必然命中那条自检、不再是"H2 单链"场景 ⇒ 用例本身失去意义，**删除**。
            //   其覆盖不丢：真正的"双入口"检测由上面 `pH1` 那条承担（H1 计划 + zscale 链）。
            string zs = "-vf format=gbrpf32le,zscale=pin=bt709:tin=iec61966-2-1:min=gbr:p=smpte432:t=iec61966-2-1:m=bt709,format=rgb48le";
            Check(CE.FindPixelColorEntry(zs, pH1) != null, "C8 抓到双映射入口（H1 计划 + zscale 色彩链）");
            Check(CE.FindPixelColorEntry(zs, pCarry) != null, "C8 抓到违反：携带计划却带色彩链");
            // 反向自检（新，2026-10-05）：H2 置位必须**响亮报错**（而不是静默当"单链合法"）
            var pH2Probe = new FfmpegGui.Services.ColorMapping.ColorTransformPlan { Action = CA.Map, Backend = CB.FfmpegFilter };
            var h2Verdict = CE.FindPixelColorEntry("-vf scale=800:-1,format=rgb48le", pH2Probe);
            Check(h2Verdict != null && h2Verdict.Contains("无 H2 执行体"),
                $"C8 反向自检：H2 置位必须报「无 H2 执行体」（实 {h2Verdict ?? "null"}）");
            // 不误杀：iccgen（标注生成器）/ format= / 纯缩放 / -colorspace 等 CLI 标注选项 / 无参 zscale
            Check(CE.FindPixelColorEntry("-vf format=rgb48le,iccgen=color_primaries=smpte432:color_trc=iec61966-2-1:force=1 -colorspace bt709 -color_trc bt709", pNoop) == null,
                "C8 无误杀：iccgen + CLI 标注选项不算像素入口");
            Check(CE.FindPixelColorEntry("-vf scale=800:-1,format=rgb48le,zscale=3840:2160,iccgen", pH1) == null,
                "C8 无误杀：纯缩放（无色彩参数）不算入口（H1 单链合法）");
            Check(CE.FindPixelColorEntry("-i in.png -c:v libjxl out.jxl", pCarry) == null, "C8 无误杀：无色彩滤镜的命令行");

            // C9 几何凸包包含判据（取代旧的“矩阵元素全非负”近似）：已知关系必须全部正确
            var gSrgb = CS.FromCicp("bt709", "iec61966-2-1", "sRGB");
            var gP3 = CS.FromCicp("smpte432", "iec61966-2-1", "Display P3");
            var g2020 = CS.FromCicp("bt2020", "bt709", "BT.2020");
            var gPro = CS.FromNamedSpace("ProPhoto RGB");
            if (gSrgb != null && gP3 != null && g2020 != null && gPro != null)
            {
                (bool? got, bool want, string what)[] cases = {
                    (CS.ContainsGamut(gSrgb, gP3), true,  "sRGB ⊆ Display P3"),
                    (CS.ContainsGamut(gSrgb, g2020), true, "sRGB ⊆ BT.2020"),
                    // ⚠ 不是笔误："BT.2020 包住 P3" 是**近似说法**。实测/手算均表明：
                    //   2020 的 G→R 边在 x=0.680 处 y≈0.3183，而 Display P3 红原色 y=0.320
                    //   ⇒ P3 红原色超出 2020 三角形约 0.0017（近共线），严格几何上 P3 ⊄ BT.2020。
                    //   几何判据能抓到这个差正是它优于“矩阵元素非负”近似的地方。
                    (CS.ContainsGamut(gP3, g2020), false,   "Display P3 ⊄ BT.2020（红原色超出≈0.0017）"),
                    (CS.ContainsGamut(gP3, gSrgb), false,  "Display P3 ⊄ sRGB"),
                    (CS.ContainsGamut(g2020, gP3), false,  "BT.2020 ⊄ Display P3"),
                    (CS.ContainsGamut(g2020, gSrgb), false,"BT.2020 ⊄ sRGB"),
                    (CS.ContainsGamut(gPro, g2020), false, "ProPhoto ⊄ BT.2020"),
                    (CS.ContainsGamut(gPro, gSrgb), false, "ProPhoto ⊄ sRGB"),
                    (CS.ContainsGamut(gSrgb, gSrgb), true, "sRGB ⊆ sRGB（自身，边界松弛）"),
                };
                foreach (var (got, want, what) in cases)
                {
                    Check(got == want, $"C9 {what}（实={got}）");
                    if (got != want)
                    {
                        // 失败时输出实际参与判定的 xy（D50 列归一）与目标三角形，便于区分"几何真值"与"实现错"
                        static string Fmt(double[]? v) => v == null ? "null"
                            : $"R({v[0]:F5},{v[1]:F5}) G({v[2]:F5},{v[3]:F5}) B({v[4]:F5},{v[5]:F5})";
                        var srcD = what.StartsWith("sRGB ⊆") ? gSrgb : what.StartsWith("Display P3 ⊆") ? gP3
                               : what.StartsWith("BT.2020 ⊄") ? g2020 : gPro;
                        var dstD = what.EndsWith("Display P3") && what.Contains("⊆") ? gP3
                                 : what.Contains("BT.2020") && !what.StartsWith("BT.2020") ? g2020
                                 : what.Contains("sRGB") && what.StartsWith("ProPhoto") ? gSrgb
                                 : what.Contains("sRGB（自身") ? gSrgb : g2020;
                        Console.WriteLine($"      源={Fmt(srcD?.PrimariesXyD50())}");
                        Console.WriteLine($"      标={Fmt(dstD?.PrimariesXyD50())}");
                    }
                }
            }

            // C10 抖动确定性：相位取绝对坐标 ⇒ 整幅与逐条 tile 必须逐字节一致
            {
                int dw = 32, dh = 32;
                var srcA = new byte[dw * dh * 4];
                for (int i = 0; i < dw * dh; i++)
                {
                    byte g = (byte)(i % 251);
                    srcA[i * 4] = g; srcA[i * 4 + 1] = (byte)(255 - g); srcA[i * 4 + 2] = (byte)((i * 7) % 256); srcA[i * 4 + 3] = 255;
                }
                var specD = Spec("bt709", "iec61966-2-1", "smpte432", "iec61966-2-1");
                specD.Dither = FfmpegGui.Services.ColorMapping.DitherMode.Ordered4x4;
                var eotf8 = TC.Srgb.BuildEotfTable8();
                var whole = new byte[srcA.Length];
                CK.TransformRgba8(srcA, whole, specD, eotf8, dw, dh);
                var tiled = new byte[srcA.Length];
                for (int y0 = 0; y0 < dh; y0 += 7)
                {
                    int hh = Math.Min(7, dh - y0);
                    CK.TransformRgba8(srcA.AsSpan(y0 * dw * 4, hh * dw * 4), tiled.AsSpan(y0 * dw * 4, hh * dw * 4),
                                      specD, eotf8, dw, hh, null, 0, y0);
                }
                bool same = true; int first = -1;
                for (int i = 0; i < whole.Length; i++) if (whole[i] != tiled[i]) { same = false; first = i; break; }
                Check(same, $"C10 抖动：整幅 vs 逐条 tile（originY）逐字节一致{(same ? "" : $"，首个差异在字节 {first}")}");
                // 确定性：两次运行结果相同（无 RNG）
                var again = new byte[srcA.Length];
                CK.TransformRgba8(srcA, again, specD, eotf8, dw, dh);
                Check(whole.AsSpan().SequenceEqual(again), "C10 抖动：同输入两次运行逐字节一致（无 RNG）");
            }

            // C11 rgb48→rgb8 降位内核：绝对相位 ⇒ tile 切分逐字节一致；拑动后渐变仍单调
            {
                int cw = 64, ch = 8;
                var src16 = new byte[cw * ch * 6];
                for (int i = 0; i < cw * ch; i++)
                {
                    int v = (int)Math.Round(i / (double)(cw * ch - 1) * 65535.0);
                    for (int c = 0; c < 3; c++)
                    {
                        src16[i * 6 + c * 2] = (byte)(v & 0xFF); src16[i * 6 + c * 2 + 1] = (byte)(v >> 8);
                    }
                }
                var spec8 = Spec("bt709", "iec61966-2-1", "smpte432", "iec61966-2-1");
                spec8.Dither = FfmpegGui.Services.ColorMapping.DitherMode.Ordered4x4;
                var tS = CK.BuildTables(spec8.SrcCurve); var tD = CK.BuildTables(spec8.DstCurve);
                var whole8 = new byte[cw * ch * 3];
                CK.TransformRgb48leToRgb8(src16, whole8, spec8, cw * ch, tS, tD, cw, 0);
                var tiled8 = new byte[cw * ch * 3];
                for (int y0 = 0; y0 < ch; y0 += 3)
                {
                    int hh = Math.Min(3, ch - y0);
                    CK.TransformRgb48leToRgb8(src16.AsSpan(y0 * cw * 6, hh * cw * 6), tiled8.AsSpan(y0 * cw * 3, hh * cw * 3),
                                              spec8, hh * cw, tS, tD, cw, y0 * cw);
                }
                bool same8 = true; int diffAt = -1;
                for (int i = 0; i < whole8.Length; i++) if (whole8[i] != tiled8[i]) { same8 = false; diffAt = i; break; }
                Check(same8, $"C11 8bit 降位：整幅 vs 逐条 tile（originIndex）逐字节一致{(same8 ? "" : $"，首差 {diffAt}")}");
                // 单调不降：拑动后沿渐变 R 不应前进后退（允许相邻等值，不允许下降超过 1）
                int worstDrop = 0;
                for (int i = 1; i < cw * ch; i++)
                {
                    int d = whole8[i * 3] - whole8[(i - 1) * 3];
                    if (d < worstDrop) worstDrop = d;
                }
                Check(worstDrop >= -1, $"C11 拑动后渐变仍单调（最大回落 {worstDrop} LSB，仅允许拖动带来的 ±1）");
                // 精度：与 16bit 路径的 8bit 化结果相比，误差 ≤1 LSB（拑动只应搬动 1 个台阶）
                var specN = Spec("bt709", "iec61966-2-1", "smpte432", "iec61966-2-1");
                var mid16 = new byte[src16.Length];
                CK.TransformRgb48le(src16, mid16, specN, cw * ch, tS, tD);
                int maxDev = 0;
                for (int i = 0; i < cw * ch; i++)
                {
                    int plain = (int)Math.Round((mid16[i * 6] + mid16[i * 6 + 1] * 256) / 65535.0 * 255.0);
                    int dev = Math.Abs(plain - whole8[i * 3]);
                    if (dev > maxDev) maxDev = dev;
                }
                Check(maxDev <= 1, $"C11 拑动幅度受控：与无拑动降位最大偏差 {maxDev} LSB（应 ≤1）");
            }

            // C12 **精确可表示的码值必须原样出来**（有序抖动的居中判据；2026-09-26 补）
            //   动机：C10/C11 只测「tile 一致」与「单调」，两者对**中心偏移**都不敏感 ——
            //   旧写法 t = Bayer4[p] − 0.5f/4f ⇒ t ∈ [−0.125, +0.8125]，16 个相位里 **6 个** t > 0.5，
            //   于是"本来 8bit 能 1:1 精确表示"的码值被系统性抬 +1（8bit 源经 rgb48le 后码值恒为 257 的整数倍）。
            //   这就是维护者点名的**无意义精度损失**：没有任何视觉收益，只是把可精确表达的值推高一档。
            //   ⇒ 判据必须按相位穷举（只跑一种相位会随机落在"恰好没事"的那 10/16 上）。
            {
                int w12 = 16, h12 = 16;                       // 16×16 ⇒ 4×4 相位各出现 16 次
                var specN12 = Spec("bt709", "iec61966-2-1", "bt709", "iec61966-2-1");   // 同原色 ⇒ 无矩阵
                specN12.Dither = FfmpegGui.Services.ColorMapping.DitherMode.Ordered4x4;
                var tbl12 = CK.BuildTables(specN12.SrcCurve);
                var src12 = new byte[w12 * h12 * 6];
                var want12 = new byte[w12 * h12 * 3];
                for (int i = 0; i < w12 * h12; i++)
                {
                    // 扫过整条 8bit 码轴（含 0/255 两端），16bit 值 = 257×码值 ⇒ 8bit 能 1:1 精确表示
                    int code = (int)Math.Round(i / (double)(w12 * h12 - 1) * 255.0);
                    int v16 = code * 257;
                    for (int c = 0; c < 3; c++)
                    {
                        src12[i * 6 + c * 2] = (byte)(v16 & 0xFF); src12[i * 6 + c * 2 + 1] = (byte)(v16 >> 8);
                        want12[i * 3 + c] = (byte)code;
                    }
                }
                var got12 = new byte[w12 * h12 * 3];
                CK.TransformRgb48leToRgb8(src12, got12, specN12, w12 * h12, tbl12, tbl12, w12, 0);
                int lifted = 0, dropped = 0, worstPhase = 0;
                var phaseBad = new int[16];
                for (int i = 0; i < w12 * h12; i++)
                {
                    int ph = (i % w12 & 3) + ((i / w12 & 3) << 2);
                    for (int c = 0; c < 3; c++)
                    {
                        int d = got12[i * 3 + c] - want12[i * 3 + c];
                        if (d > 0) lifted++; else if (d < 0) dropped++;
                        if (d != 0) phaseBad[ph]++;
                    }
                }
                for (int p = 1; p < 16; p++) if (phaseBad[p] > phaseBad[worstPhase]) worstPhase = p;
                Check(lifted == 0 && dropped == 0,
                    $"C12 精确可表示的码值经拑动降位必须逐字节 no-op（抬升 {lifted} / 下降 {dropped}，最差相位 {worstPhase} 命中 {phaseBad[worstPhase]} 次）");
                // 这条判据自己也要有对照：同一内核关掉抖动时必须仍逐字节相等（否则上面那条可能只是"抖动根本没跑"）
                specN12.Dither = FfmpegGui.Services.ColorMapping.DitherMode.None;
                var gotOff = new byte[got12.Length];
                CK.TransformRgb48leToRgb8(src12, gotOff, specN12, w12 * h12, tbl12, tbl12, w12, 0);
                Check(gotOff.AsSpan().SequenceEqual(want12), "C12 对照：关掉抖动同样逐字节 no-op ⇒ 上面那条不是「抖动没生效」造出来的假绿");
                // 反向哨兵：**半档**输入（257 的整数倍 +128，8bit 不可精确表示）在 16 个相位上必须展开成
                //   ≥2 个不同输出。没有这条，"C12 全等"也可能只是这条路把抖动整体吞掉了。
                var srcOdd = new byte[src12.Length]; var gotOdd = new byte[got12.Length];
                for (int i = 0; i < w12 * h12; i++)
                {
                    int vOdd = ((i % 254) + 1) * 257 + 128;      // ≤ 254×257+128 = 65346，不越 16bit 界
                    for (int c = 0; c < 3; c++)
                    { srcOdd[i * 6 + c * 2] = (byte)(vOdd & 0xFF); srcOdd[i * 6 + c * 2 + 1] = (byte)(vOdd >> 8); }
                }
                var specD2 = Spec("bt709", "iec61966-2-1", "bt709", "iec61966-2-1");
                specD2.Dither = FfmpegGui.Services.ColorMapping.DitherMode.Ordered4x4;
                CK.TransformRgb48leToRgb8(srcOdd, gotOdd, specD2, w12 * h12, tbl12, tbl12, w12, 0);
                int distinct = new System.Collections.Generic.HashSet<byte>(gotOdd).Count;
                Check(distinct >= 2, $"C12 哨兵：半档输入经抖动必须展开成 ≥2 个不同输出（实得 {distinct} 种）⇒ 抖动确实在这条路上生效");
            }

            // C13 RGBA 出口的抖动必须加在**码域**（`ColorKernels.cs:351-362` 现在加在线性域）
            //   依据：本出口的输入是 8-bit ⇒ 每一个源码值在 8-bit 出口上都**精确可表示**，
            //   所以"抖动的正确行为"在这里就是**整体 no-op**；任何偏离都是纯损伤。
            //   而线性域加法会被 sRGB OETF 趾段斜率（12.92）放大：暗部 ±0.469/255 的线性位移
            //   折算成码值可达 ~10 档 ⇒ 比不抖更差（取证见 docs/COLOR_MATRIX_AUDIT_2026-09-24.md §4.3）。
            //   ⚠ 本出口的**产品调用数为 0**（同 §4.3："只被门禁养着"）⇒ 这条锁的是"两副面孔"不再出现，
            //     以及 P3 把自研出口定样时不许把它复制成活路。
            {
                int w13 = 16, h13 = 16;                       // 16×16 ⇒ 16 个 Bayer 相位全覆盖
                var spec13 = Spec("bt709", "iec61966-2-1", "bt709", "iec61966-2-1");   // 同原色 ⇒ 无矩阵
                var eotf813 = TC.Srgb.BuildEotfTable8();
                var src13 = new byte[w13 * h13 * 4];
                for (int i = 0; i < w13 * h13; i++)
                {
                    byte c13 = (byte)(i % 256);               // 扫遍整条 8bit 码轴（含 0 与 255 端点）
                    src13[i * 4 + 0] = c13; src13[i * 4 + 1] = c13; src13[i * 4 + 2] = c13; src13[i * 4 + 3] = 200;
                }
                var off13 = new byte[src13.Length];
                CK.TransformRgba8(src13, off13, spec13, eotf813, w13, h13);            // Dither 默认 None
                int offBad = 0, firstOff = -1;
                for (int i = 0; i < w13 * h13; i++)
                    for (int c = 0; c < 3; c++)
                        if (off13[i * 4 + c] != src13[i * 4 + c]) { offBad++; if (firstOff < 0) firstOff = src13[i * 4 + c]; }
                Check(offBad == 0,
                    $"C13 对照：不抖时 identity 直通必须逐字节还原（破坏 {offBad} 处，首个源码值 {firstOff}）⇒ 否则下面两条是编码表的锅，不是抖动的锅");

                var specD13 = Spec("bt709", "iec61966-2-1", "bt709", "iec61966-2-1");
                specD13.Dither = FfmpegGui.Services.ColorMapping.DitherMode.Ordered4x4;
                var on13 = new byte[src13.Length];
                CK.TransformRgba8(src13, on13, specD13, eotf813, w13, h13);
                int changed = 0, maxDev = 0, darkestHit = 255;
                for (int i = 0; i < w13 * h13; i++)
                    for (int c = 0; c < 3; c++)
                    {
                        int d = Math.Abs(on13[i * 4 + c] - src13[i * 4 + c]);
                        if (d != 0) { changed++; if (src13[i * 4 + c] < darkestHit) darkestHit = src13[i * 4 + c]; }
                        if (d > maxDev) maxDev = d;
                    }
                Check(changed == 0,
                    $"C13 8bit→8bit 精确可表示 ⇒ 开抖动后必须逐字节还原（被改变 {changed} 处，最低的受损源码值 {darkestHit}）");
                Check(maxDev <= 1,
                    $"C13 抖动幅度上限：与源码值最大偏离 {maxDev} 必须 ≤1 档（码域抖动的定义；线性域加会被趾段斜率放大到 ~10）");
                Console.WriteLine($"  C13 读数：改动 {changed}/768 处、最大偏离 {maxDev} 档、最低受损码值 {darkestHit}");

                // 反向哨兵：换成**跨色域矩阵 + 非中性像素**（会产生真正的分数码值）⇒ 抖动必须仍然起作用，
                //   但偏离仍受"码域加 ±0.469 档"的定义约束（`Round(x+t)` vs `Round(x)` 最多差 1）。
                //   ⚠ 输入必须**带彩色**：三条通道相等时，行和为 1 的原色矩阵保中性 ⇒ 输出仍落在整数码上，
                //     抖动"无事可做"是正确行为而不是失效（实测用灰阶跑这条 ⇒ 改动 0/768，误判成"抖动被关掉"）。
                //   没有这条哨兵，"把抖动整段删掉"也能让上面三条全绿 ⇒ 那才是真的降级。
                var srcC = new byte[src13.Length];
                for (int i = 0; i < w13 * h13; i++)
                {
                    srcC[i * 4 + 0] = (byte)(i % 256);
                    srcC[i * 4 + 1] = (byte)((i * 7 + 3) % 256);
                    srcC[i * 4 + 2] = (byte)((i * 13 + 5) % 256);
                    srcC[i * 4 + 3] = 255;
                }
                var specOn13 = Spec("bt709", "iec61966-2-1", "smpte432", "iec61966-2-1");
                var specMx13 = Spec("bt709", "iec61966-2-1", "smpte432", "iec61966-2-1");
                specMx13.Dither = FfmpegGui.Services.ColorMapping.DitherMode.Ordered4x4;
                var mOff = new byte[srcC.Length]; var mOn = new byte[srcC.Length];
                CK.TransformRgba8(srcC, mOff, specOn13, eotf813, w13, h13);
                CK.TransformRgba8(srcC, mOn, specMx13, eotf813, w13, h13);
                int diffM = 0, devM = 0;
                for (int i = 0; i + 4 <= srcC.Length; i += 4)
                    for (int c = 0; c < 3; c++)
                    {
                        int d = Math.Abs(mOn[i + c] - mOff[i + c]);
                        if (d != 0) diffM++;
                        if (d > devM) devM = d;
                    }
                Check(diffM > 0 && devM <= 1,
                    $"C13 哨兵：有矩阵且非中性输入时抖动仍要生效且只在码域展开（实际改动 {diffM}/768 处、最大偏离 {devM} 档；要求 >0 且 ≤1）");
            }

            Console.WriteLine($"  contract: 共 {cells} 格，覆盖豁免 {exempted}，拒绝 {rejects}");
            // 拒绝必须可审计：按策略与原因分组列出（防止“过度拒绝”被一个总数掩盖）
            foreach (var (s, n) in rejectByStrategy)
                Console.WriteLine($"    拒绝 {s,-12} {n,3} 格");
            foreach (var (r, n) in rejectReasons)
                Console.WriteLine($"    · {n,3}× {r}");
        }
    }
}
