using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Core
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // CoreGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> CoreGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class CoreGroup
    {
        private static string Dump(System.Text.StringBuilder sb)
        {
            var s = sb.ToString().Replace("\r", " ").Replace("\n", " ").Trim();
            if (s.Length == 0) return "(无输出)";
            return s.Length > 300 ? s.Substring(0, 300) + "…" : s;
        }

        private static async Task ProbeRunnerGuard(string[] args)
        {
            const string Cmd = @"C:\Windows\System32\cmd.exe";
            // ❗ 替身一律用**绝对路径**，不要写裸命令名 ping：
            //   本宿主下 Start-Process 传给子进程的环境块**不含 System32**（实测 where.exe ping ⇒ exit=1、
            //   cmd 报 "'ping' is not recognized..."），而宿主里 Get-Command ping.exe 却能找到。
            //   用裸名会让本探针在“经门禁脚本跑”时假红（退出码 1/0.2s），而直接跑却绿 —— 曾据此误判为产物陈旧。
            //   生产代码不受影响：FfmpegRunner 用的是 AppSettingsService.Current.FfmpegPath（绝对路径）。
            const string Ping = @"C:\Windows\System32\PING.EXE";
            // 忙等载体：真 ffmpeg + 1 字节 `0x00` 的 .jxl（与 verify-ffmpeg-heartbeat.ps1 ② 同一 fixture）。
            // ⚠ 实测（本探针落地前）：`-i <1字节.jxl> -frames:v 1 <out.png>` 在 4.0 s 时**仍存活且进度 0 字节**
            //   ⇒ 满足「会被注入」（名字含 ffmpeg）∧「零进度块」两个必要条件。
            var ff = FfmpegGui.Services.AppSettingsService.Current.FfmpegPath;
            var work = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "runnerprobe_" + Guid.NewGuid().ToString("N"));
            System.IO.Directory.CreateDirectory(work);
            var badJxl = System.IO.Path.Combine(work, "bad.jxl");
            System.IO.File.WriteAllBytes(badJxl, new byte[] { 0x00 });
            var logA = new System.Text.StringBuilder();
            var swA = System.Diagnostics.Stopwatch.StartNew();
            var rcA = await FfmpegRunner.RunAsync($"/c {Ping} -n 3 127.0.0.1 >nul", s => logA.Append(s), Cmd);
            swA.Stop();
            // ⚠ 失败时必须把子进程输出带出来：只报“退出码 1”无法区分“cmd 自己报错”与“守卫误杀”。
            //   实测（2026-09-15）：经 Start-Process 启动本探针时 cmd 退 1/0.2s，直接跑却退 0/2.4s；
            //   没有这段输出就只能靠猜。
            Check(rcA == 0 && logA.ToString().IndexOf("[超时]") < 0,
                $"静默但正常退出的子进程不被误杀（退出码 {rcA}，{swA.Elapsed.TotalSeconds:F1}s）"
                + (rcA == 0 ? "" : $"；子进程输出=<{Dump(logA)}>"));

            // ── C-legacy：取消语义（cmd 替身 ⇒ (A) 后走**旧双信号路径**）──────────────────────
            //   ⚠ 它**不再**经过心跳判死分支 ⇒ 只能验“旧路径的取消语义”，别当成“取消优先于心跳判死”。
            //   ⚠ 两条都用 `threwC` 前置判据 ⇒ **绿/红都算 2 条**，断言总数不随成败漂移（基线才可对账）。
            var logC = new System.Text.StringBuilder();
            var swC = System.Diagnostics.Stopwatch.StartNew();
            var threwC = false;
            var rcC = 0;
            using (var cts = new CancellationTokenSource(TimeSpan.FromSeconds(2)))
            {
                try
                {
                    rcC = await FfmpegRunner.RunAsync($"/c {Ping} -n 600 127.0.0.1 >nul", s => logC.Append(s), Cmd, cts.Token);
                }
                catch (OperationCanceledException) { threwC = true; }
            }
            swC.Stop();
            Check(threwC, "C-legacy 取消应抛 OperationCanceledException"
                + (threwC ? "" : $"（实际返回码 {rcC}；子进程输出=<{Dump(logC)}>）"));
            Check(threwC && swC.Elapsed.TotalSeconds < 30,
                $"C-legacy 取消在 {swC.Elapsed.TotalSeconds:F1}s 内传播（子进程被终止，不是等到自然退出）");

            // ── C1：真 ffmpeg 忙等（零进度块）下，**取消必须优先于心跳判死** ──────────────────────
            //   hbSec=8 ⇒ 心跳判死最早落在 ~8 s；取消在 3 s ⇒ 若实现把取消**推迟到心跳 tick**（或让心跳
            //   抢先判死），本用例会拿到 HangExitCode（≈8 s）而不是 OCE ⇒ 转红。
            //   ⚠ 两条自检专防“空断言”：注入必须真的发生、且心跳判死行必须**不出现**。
            {
                var prev = Environment.GetEnvironmentVariable("FFMPEGGUI_HEARTBEAT_TIMEOUT_SEC");
                Environment.SetEnvironmentVariable("FFMPEGGUI_HEARTBEAT_TIMEOUT_SEC", "8");
                try
                {
                    var log1 = new System.Text.StringBuilder();
                    var sw1 = System.Diagnostics.Stopwatch.StartNew();
                    var threw1 = false;
                    var rc1 = 0;
                    using (var cts1 = new CancellationTokenSource(TimeSpan.FromSeconds(3)))
                    {
                        try
                        {
                            rc1 = await FfmpegRunner.RunAsync(
                                $"-y -hide_banner -loglevel error -i \"{badJxl}\" -frames:v 1 \"{System.IO.Path.Combine(work, "out_c1.png")}\"",
                                s => log1.Append(s), ff, cts1.Token);
                        }
                        catch (OperationCanceledException) { threw1 = true; }
                    }
                    sw1.Stop();
                    var t1 = log1.ToString();
                    Check(threw1, "C1 真 ffmpeg 忙等（零进度块）下，**取消**必须抛 OperationCanceledException"
                        + (threw1 ? "" : $"；实际返回码 {rc1}（{FfmpegRunner.HangExitCode} = 心跳判死抢先），"
                            + $"耗时 {sw1.Elapsed.TotalSeconds:F1}s；输出=<{Dump(log1)}>"));
                    Check(threw1 && sw1.Elapsed.TotalSeconds >= 2.5 && sw1.Elapsed.TotalSeconds <= 6,
                        $"C1 取消在 ~3 s 生效（实测 {sw1.Elapsed.TotalSeconds:F1}s ∈ [2.5, 6]）⇒ **远早于** 8 s 心跳阈值"
                        + " ⇒ 取消没有被推迟到心跳 tick");
                    Check(t1.IndexOf("[心跳] 已追加") >= 0,
                        "C1 自检：本用例确实**注入了** `-progress pipe:1`（否则「取消优先」是空断言）");
                    Check(t1.IndexOf("无进度心跳") < 0,
                        "C1 自检：**没有**出现心跳判死行 ⇒ 判死没有抢先于取消");
                }
                finally { Environment.SetEnvironmentVariable("FFMPEGGUI_HEARTBEAT_TIMEOUT_SEC", prev); }
            }

            // ── B：忙等（零进度块）必须被心跳**限时判死**（原 `--hang` 的真 ffmpeg 版）────────────
            {
                var prevB = Environment.GetEnvironmentVariable("FFMPEGGUI_HEARTBEAT_TIMEOUT_SEC");
                Environment.SetEnvironmentVariable("FFMPEGGUI_HEARTBEAT_TIMEOUT_SEC", "1");
                try
                {
                    var logB = new System.Text.StringBuilder();
                    var swB = System.Diagnostics.Stopwatch.StartNew();
                    var rcB = await FfmpegRunner.RunAsync(
                        $"-y -hide_banner -loglevel error -i \"{badJxl}\" -frames:v 1 \"{System.IO.Path.Combine(work, "out_stall.png")}\"",
                        s => logB.Append(s), ff);
                    swB.Stop();
                    var txt = logB.ToString();
                    Check(rcB == FfmpegRunner.HangExitCode && txt.IndexOf("无进度心跳") >= 0,
                        $"B 忙等（零进度块）被心跳限时判死（退出码 {rcB}，期望 {FfmpegRunner.HangExitCode}，"
                        + $"耗时 {swB.Elapsed.TotalSeconds:F0}s）—— 忙等型挂死不再永不返回");
                }
                finally { Environment.SetEnvironmentVariable("FFMPEGGUI_HEARTBEAT_TIMEOUT_SEC", prevB); }
            }

            try { System.IO.Directory.Delete(work, true); } catch { }
        }
    }
}
