using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Core
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // CoreGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> CoreGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class CoreGroup
    {
        private static object? SettingsSentinel(System.Reflection.PropertyInfo p, object? freshDefault)
        {
            var t = p.PropertyType;
            if (t == typeof(string))
            {
                var s = "zz-" + p.Name + "-7";
                return (freshDefault as string) == s ? s + "x" : s;
            }
            if (t == typeof(bool)) return !(freshDefault as bool? ?? false);
            if (t == typeof(int))
            {
                var v = 4242;
                return (freshDefault as int?) == v ? 4243 : v;
            }
            if (t == typeof(System.Collections.Generic.List<string>))
                return new System.Collections.Generic.List<string> { "zz-a", "zz-b" };
            return null;
        }

        private static bool SettingsSame(Type t, object? a, object? b)
        {
            if (t == typeof(System.Collections.Generic.List<string>))
            {
                var la = a as System.Collections.Generic.List<string>;
                var lb = b as System.Collections.Generic.List<string>;
                if (la == null || lb == null || la.Count != lb.Count) return false;
                for (int i = 0; i < la.Count; i++) if (la[i] != lb[i]) return false;
                return true;
            }
            return Equals(a, b);
        }

        private static string SettingsShow(object? v)
        {
            if (v is System.Collections.Generic.List<string> l) return "[" + string.Join(",", l) + "]";
            return v?.ToString() ?? "(null)";
        }

        private static void ProbeSettingsSave()
        {
            var dir = System.IO.Path.Combine(System.IO.Path.GetTempPath(), $"cfgprobe_{Guid.NewGuid():N}");
            System.IO.Directory.CreateDirectory(dir);
            try
            {
                var f = System.IO.Path.Combine(dir, "settings.json");
                System.IO.File.WriteAllText(f, "{}");
                AAS.Load(f);

                AAS.Current.Language = "en-US";
                AAS.Current.MaxQueueSize = 7;
                bool ok1 = AAS.Save();
                Check(ok1 && AAS.LastSaveIssue == null,
                    $"第一次保存成功且无告警（ok={ok1}, issue={AAS.LastSaveIssue}）");
                Check(!System.IO.File.Exists(f + ".tmp"), "原子写不留 .tmp 残片");
                var t1 = System.IO.File.ReadAllText(f);
                Check(t1.Contains("en-US") && t1.Contains("7"), "落盘内容确实是本次内存值（语言 + 队列并发）");

                AAS.Current.Language = "zh-CN";
                bool ok2 = AAS.Save();
                Check(ok2 && System.IO.File.Exists(f + ".bak")
                        && System.IO.File.ReadAllText(f + ".bak").Contains("en-US"),
                    "第二次保存把上一版留在 .bak（写坏/崩溃时可回滚）");

                var beforeLocked = System.IO.File.ReadAllText(f);
                using (new System.IO.FileStream(f, System.IO.FileMode.Open,
                           System.IO.FileAccess.ReadWrite, System.IO.FileShare.None))
                {
                    AAS.Current.Language = "en-US";
                    bool ok3 = AAS.Save();
                    Check(!ok3 && !string.IsNullOrEmpty(AAS.LastSaveIssue),
                        $"目标不可写时 Save 返回 false 并给出原因（ok={ok3}, issue={AAS.LastSaveIssue}）");
                    // ⚠ 不能在独占句柄还开着时 ReadAllText —— 那连打开都不允许（实测 IOException），是探针自己的错
                }
                Check(System.IO.File.ReadAllText(f) == beforeLocked,
                    "失败时目标文件内容一字未动（原子写真正要买的东西）");

                var bad = System.IO.Path.Combine(dir, "corrupt.json");
                System.IO.File.WriteAllText(bad, "{ this is not json");
                AAS.Load(bad);
                Check(AAS.LastLoadIssue != null,
                    $"损坏的设置文件被记录而非静默重置（issue={AAS.LastLoadIssue}）");

                // ── 全字段落盘往返锁（2026-09-24 补）──
                //   上面几条只测 Language / MaxQueueSize ⇒ **没进 `Save()` 手写克隆表**的属性能永远不被发现
                //   （实测就是这样漏着 `RenderingMode` 而本探针一直绿）。⚠ 光看"文件里有没有这个键"也不够：
                //   `Save()` 序列化的是 `new AppSettings{…}` 那个 clone ⇒ 漏掉的字段会带着**模型默认值**
                //   一起落盘，键在、值却是错的。⇒ 判据只能是「设非默认值 → Save → 读回 → 逐个相等」。
                AAS.Load(f);   // 目标重新指回 f（上一步的损坏文件会把 Save 引到 corrupt.json）
                var fresh = new FfmpegGui.Models.AppSettings();
                var props = typeof(FfmpegGui.Models.AppSettings)
                    .GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
                var sentinels = new System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<System.Reflection.PropertyInfo, object?>>();
                var unsupported = new System.Collections.Generic.List<string>();
                int eligible = 0;
                foreach (var p in props)
                {
                    if (!p.CanRead || !p.CanWrite) continue;
                    if (p.GetCustomAttributes(typeof(System.Text.Json.Serialization.JsonIgnoreAttribute), false).Length > 0) continue;
                    if (p.GetCustomAttributes(typeof(ObsoleteAttribute), false).Length > 0) continue;
                    eligible++;
                    var sent = SettingsSentinel(p, p.GetValue(fresh));
                    if (sent == null) { unsupported.Add(p.Name + ":" + p.PropertyType.Name); continue; }
                    p.SetValue(AAS.Current, sent);
                    sentinels.Add(new System.Collections.Generic.KeyValuePair<System.Reflection.PropertyInfo, object?>(p, sent));
                }
                Check(unsupported.Count == 0,
                    "每个候选持久化属性都能造出非默认哨兵（不支持的类型 = " + (unsupported.Count == 0 ? "无" : string.Join(", ", unsupported)) + "）");
                Check(eligible >= 20,
                    $"反射口径自检：候选持久化属性 >= 20（实得 {eligible}）⇒ 否则下面的往返比对会空转");
                Check(AAS.Save(), "带哨兵值的那次 Save 成功");
                //   ⚠ 读回**不用** `AppJsonContext`（它是 internal，探针看不见），也不用 `AAS.Load`
                //     （它会用 `FFMPEGGUI_*` 环境变量覆盖路径/队列/主题等字段 ⇒ 哨兵会被环境值洗掉，测的就不是落盘了）。
                //     这里用默认命名 + 大小写不敏感的普通反序列化：文件里的键就是 PascalCase 的属性名，
                //     读回口径与写出口径一致 ⇒ 本条只回答"我设的值有没有真的出去再回来"。
                var back = System.Text.Json.JsonSerializer.Deserialize<FfmpegGui.Models.AppSettings>(
                    System.IO.File.ReadAllText(f),
                    new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true });
                var diffs = new System.Collections.Generic.List<string>();
                if (back == null) diffs.Add("反序列化读回 null");
                else
                {
                    foreach (var kv in sentinels)
                    {
                        var got = kv.Key.GetValue(back);
                        if (!SettingsSame(kv.Key.PropertyType, kv.Value, got))
                            diffs.Add(kv.Key.Name + ": 写入 " + SettingsShow(kv.Value) + " / 读回 " + SettingsShow(got));
                    }
                }
                Check(diffs.Count == 0,
                    "全部 " + sentinels.Count + " 个持久化属性都真的落盘并能读回（不同源 = "
                    + (diffs.Count == 0 ? "无" : string.Join(" | ", diffs)) + "）");
            }
            finally
            {
                try { System.IO.Directory.Delete(dir, true); } catch { }
            }
        }
    }
}
