using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Core
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // CoreGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> CoreGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class CoreGroup
    {
        private static void ProbeVerdict()
        {
            CS Mk(string prim, string trc, string name, string? icc, DC conf)
            {
                var d = CS.FromCicp(prim, trc, name)!;
                if (icc != null) { d.SourceIccPath = icc; d.IsIccDerived = true; }
                d.Confidence = conf;
                return d;
            }
            var srgbTag = Mk("bt709", "iec61966-2-1", "sRGB(仅标签)", null, DC.CicpTag);
            var srgbIcc = Mk("bt709", "iec61966-2-1", "sRGB(带ICC)", "t.srgb.icc", DC.IccMetric);
            var p3Icc = Mk("smpte432", "iec61966-2-1", "Display P3(带ICC)", "t.p3.icc", DC.IccMetric);
            var adobe = CS.FromNamedSpace("Adobe RGB")!;
            adobe.SourceIccPath = "t.adobe.icc"; adobe.Confidence = DC.IccMetric;
            var bt2020Sdr = CS.FromCicp("bt2020", "bt709", "BT.2020(SDR)")!;
            bt2020Sdr.Confidence = DC.CicpTag;
            // 与 `contract` 网格同源的其余三类源：HDR-PQ / HDR-HLG / 无标签（按惯例假定）。
            var pq2020 = CS.FromCicp("bt2020", "smpte2084", "BT.2100 PQ", nitsOfLinearOne: TC.PqPeakNits)!;
            pq2020.Confidence = DC.CicpTag;
            var hlg2020 = CS.FromCicp("bt2020", "arib-std-b67", "BT.2100 HLG", nitsOfLinearOne: 1000.0)!;
            hlg2020.Confidence = DC.CicpTag;
            var untagged = FfmpegGui.Services.ColorMapping.ColorSpaceIdentify.AssumeByConvention()!;

            string[] CodesOf(CP pl)
            {
                var v = pl.Verdict;
                if (v == null) return Array.Empty<string>();
                var a = new string[v.Degradations.Count];
                for (int i = 0; i < a.Length; i++) a[i] = v.Degradations[i].Code;
                return a;
            }
            bool Has(CP pl, string code) => Array.IndexOf(CodesOf(pl), code) >= 0;
            string Show(CP pl) => $"{pl.Action}/kind={pl.Verdict?.Kind}/bit={pl.OutBitDepth}/codes=[{string.Join(",", CodesOf(pl))}]";

            var seen = new System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);
            void Note(CP pl) { foreach (var c in CodesOf(pl)) seen.Add(c); }

            // ══════════ ① BitDepthReduced：出口位深 16 → 8（发生变换 + 8bit 容器上限）══════════
            // 判据来源：`ColorStrategyPlanning.PlanWithPolicy` 的 OutBitDepth 赋值
            //   （Action==Map && ColorLoss!=None && TargetBitDepth<=8 && !Requires16BitIntermediate && RgbNative）。
            // 用例：S4 手动 Adobe RGB → Display P3、输出 PNG（RgbNative、上限 16bit 但目标位深 8）。
            CI ManualToP3(string fmt, int depth, CS? target = null) => new()
            {
                Strategy = ST.Manual, Source = adobe, Target = target ?? p3Icc, TargetExplicit = true,
                Format = CE.CapsFor(fmt), TargetBitDepth = depth, AllowApproximateCurve = false,
                Manual = MI.Create(true, "Display P3", "smpte432", "iec61966-2-1", null),
            };
            {
                var pos = CE.Plan(ManualToP3("png", 8));
                Note(pos);
                Check(pos.Action == CA.Map && pos.OutBitDepth == 8,
                    $"BitDepthReduced 正向前置：需 Map + OutBitDepth=8（实为 {Show(pos)}）");
                Check(pos.Verdict?.Kind == VK.ProceedWithDegradation && Has(pos, DG.BitDepthReduced),
                    $"BitDepthReduced 正向：{DG.BitDepthReduced} 必须被登记且 Kind={VK.ProceedWithDegradation}（实为 {Show(pos)}）");

                // 负控：只把**目标位深 8 → 16**（其余一字不动）⇒ 该损失必须消失，且仍然产出。
                var neg = CE.Plan(ManualToP3("png", 16));
                Note(neg);
                Check(neg.Action == CA.Map && neg.OutBitDepth == 16,
                    $"BitDepthReduced 负控前置：16bit 目标仍须产出且 OutBitDepth=16（实为 {Show(neg)}）");
                Check(!Has(neg, DG.BitDepthReduced),
                    $"BitDepthReduced 负控：目标位深 8→16 后 {DG.BitDepthReduced} 必须消失（实为 {Show(neg)}）");
            }

            // ══════════ ② GamutClipped：源色域超出目标（裁切/GMO）══════════
            // 判据来源：`ColorTransformPlan.GamutOutsideDestination`（PlanCore 里由 GamutContainedIn 置位）。
            {
                var pos = CE.Plan(ManualToP3("png", 8));
                Check(pos.GamutOutsideDestination && Has(pos, DG.GamutClipped),
                    $"GamutClipped 正向：Adobe RGB → Display P3 越界必须登记 {DG.GamutClipped}（实为 {Show(pos)}）");

                // 负控：只把**目标改成超集 BT.2020(SDR)**（其余一字不动）⇒ 越界消失，该 Code 必须消失。
                var neg = CE.Plan(ManualToP3("png", 8, bt2020Sdr));
                Note(neg);
                Check(neg.Action != CA.Reject,
                    $"GamutClipped 负控前置：换超集目标仍须产出（实为 {Show(neg)}）");
                Check(!neg.GamutOutsideDestination && !Has(neg, DG.GamutClipped),
                    $"GamutClipped 负控：目标改为超集 BT.2020(SDR) 后 {DG.GamutClipped} 必须消失（实为 {Show(neg)}）");
            }

            // ══════════ ②′ GamutCompressed：开关开 + 源越界 ⇒ GMO 压缩（与 GamutClipped 互斥）══════════
            // 判据来源：`ColorTransformPlan.GamutMap`（PlanCore 的**单点置位** =
            //   `GamutOutsideDestination && policy.AllowGamutCompression && 目标亮度系数可取`）。
            // ⚠ 本组是本轮（2026-09-17）补的**零覆盖**：`GamutCompressed` 与 `ColorLoss=GamutCompression`
            //   此前没有任何门禁断言（`--color-gamut-map` 接进引擎后只靠 H1 后端日志间接可见）。
            {
                CI GmoOn(string fmt, int depth)
                {
                    var it = ManualToP3(fmt, depth);
                    it.AllowGamutCompression = true;
                    return it;
                }
                var pos = CE.Plan(GmoOn("png", 8));
                Note(pos);
                Check(pos.GamutOutsideDestination && pos.GamutMap,
                    $"GamutCompressed 正向前置：源越界 + 开关开 ⇒ GamutMap 必须置位（实为 {Show(pos)}）");
                Check(pos.Verdict?.Kind == VK.ProceedWithDegradation && Has(pos, DG.GamutCompressed),
                    $"GamutCompressed 正向：{DG.GamutCompressed} 必须被登记且 Kind={VK.ProceedWithDegradation}（实为 {Show(pos)}）");
                Check(pos.ColorLoss == CL.GamutCompression,
                    $"GamutCompressed 正向：ColorLoss 必须是 {CL.GamutCompression}（实为 {pos.ColorLoss}）");
                Check(!Has(pos, DG.GamutClipped),
                    $"GamutCompressed 正向：与 {DG.GamutClipped} 互斥，不得同时登记（实为 {Show(pos)}）");

                // 负控：只把**开关关掉**（其余一字不动）⇒ GamutCompressed 消失、GamutClipped 回来。
                // 这是「判据真的跟着开关走」的直接证据：若 GamutMap 被写成常量，本组必然转红。
                var neg = CE.Plan(ManualToP3("png", 8));
                Note(neg);
                Check(!neg.GamutMap && neg.GamutOutsideDestination,
                    $"GamutCompressed 负控前置：开关关 ⇒ GamutMap=false 且仍越界（实为 {Show(neg)}）");
                Check(!Has(neg, DG.GamutCompressed) && Has(neg, DG.GamutClipped),
                    $"GamutCompressed 负控：开关关后 {DG.GamutCompressed} 必须消失、{DG.GamutClipped} 必须回来（实为 {Show(neg)}）");

                // 越界判据必须**独立于**开关（本条是变异逼出来的）：把 `GamutOutsideDestination` 从
                // GamutMap 的判据里删掉（只留 AllowGamutCompression）时，上面 6 条**全绿**
                // —— 因为源越界那格照样压、开关关那格照样裁。只有"开关开 + **未越界**"这一格能分辨：
                // 它必须 `GamutMap=false`（否则"允许压缩"被误当成"必须压缩"，未越界内容也会被推上 H1 后端）。
                var inGamut = new CI
                {
                    Strategy = ST.Manual, Source = srgbTag, Target = p3Icc, TargetExplicit = true,
                    Format = CE.CapsFor("png"), TargetBitDepth = 8, AllowApproximateCurve = false,
                    AllowGamutCompression = true,
                    Manual = MI.Create(true, "Display P3", "smpte432", "iec61966-2-1", null),
                };
                var ig = CE.Plan(inGamut);
                Note(ig);
                Check(!ig.GamutOutsideDestination && !ig.GamutMap && ig.ColorLoss != CL.GamutCompression,
                    $"GamutCompressed 越界判据：开关开但源**未越界**（sRGB ⊆ Display P3）⇒ 不得置位 GamutMap（实为 {Show(ig)}）");
            }

            // ══════════ ③ UnlabeledAssumedSrgb：产物无标注、按隐含 sRGB 处理 ══════════
            // 判据来源：`ColorTransformPlan.UnlabeledAssumedSrgb`。
            // 用例：S2 携带 + sRGB 源（仅 CICP 标签、无 ICC）+ JPEG（无 CICP 通路、未标注即 sRGB 成立）
            //   ⇒ PlanCarry 结局 2b（无标注直通）。
            CI CarryJpg(CS src, string fmt) => new()
            {
                Strategy = ST.CarryIcc, Source = src, Format = CE.CapsFor(fmt),
                TargetBitDepth = 8, AllowApproximateCurve = false,
            };
            {
                var pos = CE.Plan(CarryJpg(srgbTag, "jpg"));
                Note(pos);
                Check(pos.Action == CA.None && pos.UnlabeledAssumedSrgb && Has(pos, DG.UnlabeledAssumedSrgb),
                    $"UnlabeledAssumedSrgb 正向：S2 × sRGB标签源 × jpg 必须登记该 Code（实为 {Show(pos)}）");

                // 负控：只把**容器 jpg → png**（可写 CICP）⇒ 走"继承 CICP 标签"形态，该 Code 必须消失。
                var neg = CE.Plan(CarryJpg(srgbTag, "png"));
                Note(neg);
                Check(neg.Action != CA.Reject && !neg.UnlabeledAssumedSrgb && !Has(neg, DG.UnlabeledAssumedSrgb),
                    $"UnlabeledAssumedSrgb 负控：容器 jpg→png（可写 CICP）后该 Code 必须消失（实为 {Show(neg)}）");
            }

            // ══════════ ④ NoIccCarrier：源有 ICC 但产物不附 ICC ══════════
            // 判据来源：`!AttachIcc && Src.SourceIccPath != null`（已产出的格）。
            // 用例：S3 仅 CICP + Display P3（带 ICC）+ AVIF（可写 CICP；源已可 CICP 精确表达 ⇒ 不改像素）
            //   —— 刻意选 **AVIF**（CanCarryArbitraryIcc=true）以**隔离** NoIccCarrier，
            //      避免与 ContainerCannotCarryIcc 同时命中（后者另有用例）。
            {
                var pos = CE.Plan(new CI
                {
                    Strategy = ST.BakeCicpOnly, Source = p3Icc, Format = CE.CapsFor("avif"),
                    TargetBitDepth = 8, AllowApproximateCurve = false,
                });
                Note(pos);
                // ⚠ 前置条件里的"源带 ICC"必须看**意图的源描述符**：`pos.Src` 在 PlanCicpOnly 的
                //   等价分支返回的是 Fresh() 计划（Src==null）⇒ 用 pos.Src 会把前置写成假红。
                Check(pos.Action != CA.Reject && !pos.AttachIcc && p3Icc.SourceIccPath != null,
                    $"NoIccCarrier 正向前置：须产出、不附 ICC、且源带 ICC（实为 {Show(pos)}）");
                Check(pos.Verdict?.Kind == VK.ProceedWithDegradation && Has(pos, DG.NoIccCarrier),
                    $"NoIccCarrier 正向：{DG.NoIccCarrier} 必须被登记（实为 {Show(pos)}）");
                Check(!Has(pos, DG.ContainerCannotCarryIcc),
                    $"NoIccCarrier 用例须隔离：AVIF 可携带任意 ICC ⇒ 不得同时命中 {DG.ContainerCannotCarryIcc}（实为 {Show(pos)}）");

                // 负控：只把**源从"带 ICC"换成"仅 CICP 标签"**（其余一字不动）⇒ 该 Code 必须消失。
                var neg = CE.Plan(new CI
                {
                    Strategy = ST.BakeCicpOnly, Source = srgbTag, Format = CE.CapsFor("avif"),
                    TargetBitDepth = 8, AllowApproximateCurve = false,
                });
                Note(neg);
                Check(neg.Action != CA.Reject && !Has(neg, DG.NoIccCarrier),
                    $"NoIccCarrier 负控：源改为无 ICC（仅 CICP 标签）后该 Code 必须消失（实为 {Show(neg)}）");
            }

            // ══════════ ⑤ ContainerCannotCarryIcc：容器能力表判 `!CanCarryArbitraryIcc` ══════════
            // 判据来源：`PlanPolicy.Format.CanCarryArbitraryIcc == false`（能力表事实，非从计划字段反猜）。
            // 用例：S1 推荐 + sRGB（带 ICC）+ GIF（无任何色彩管理通路）⇒ 映射到 sRGB 工作空间、无标注输出。
            CI RecommendedGif(CS src, string fmt) => new()
            {
                Strategy = ST.Recommended, Source = src, Format = CE.CapsFor(fmt),
                TargetBitDepth = 8, AllowApproximateCurve = false, CarryScope = CSC.All,
            };
            {
                var pos = CE.Plan(RecommendedGif(srgbIcc, "gif"));
                Note(pos);
                Check(pos.Action != CA.Reject && !CE.CapsFor("gif").CanCarryArbitraryIcc,
                    $"ContainerCannotCarryIcc 正向前置：须产出且能力表判不可携带（实为 {Show(pos)}）");
                Check(Has(pos, DG.ContainerCannotCarryIcc) && Has(pos, DG.NoIccCarrier),
                    $"ContainerCannotCarryIcc 正向：必须同时登记 {DG.ContainerCannotCarryIcc}（结构性归因）"
                    + $"与 {DG.NoIccCarrier}（已发生的损失）（实为 {Show(pos)}）");

                // 负控：只把**容器 gif → png**（可携带任意 ICC）⇒ 改走 L1 携带，两个 Code 都必须消失。
                var neg = CE.Plan(RecommendedGif(srgbIcc, "png"));
                Note(neg);
                Check(neg.AttachIcc && neg.IccPath != null,
                    $"ContainerCannotCarryIcc 负控前置：png 应改走 L1 携带（实为 {Show(neg)}）");
                Check(!Has(neg, DG.ContainerCannotCarryIcc) && !Has(neg, DG.NoIccCarrier),
                    $"ContainerCannotCarryIcc 负控：容器 gif→png 后该 Code 与 {DG.NoIccCarrier} 都必须消失（实为 {Show(neg)}）");
            }

            // ══════════ ⑥ Reject 格**不得**登记任何损失（Degradations 的语义是"已发生"）══════════
            // 用例：S3 仅 CICP + Display P3（带 ICC）+ JPEG —— 契约不可兑现（JPEG 无 CICP 通路）⇒ Reject。
            {
                var rej = CE.Plan(new CI
                {
                    Strategy = ST.BakeCicpOnly, Source = p3Icc, Format = CE.CapsFor("jpg"),
                    TargetBitDepth = 8, AllowApproximateCurve = false,
                });
                Note(rej);
                var rv = rej.Verdict!;
                Check(rej.Action == CA.Reject, $"Reject 用例前置：S3 × P3带ICC × jpg 应 Reject（实为 {Show(rej)}）");
                Check(rv.Kind == VK.Reject && rv.Degradations.Count == 0,
                    $"Reject 格不得登记 Degradations（实为 {Show(rej)}）");
                Check(rv.Alternatives.Count > 0,
                    $"Reject 格应给出结构化 Alternatives（实为 {rv.Alternatives.Count} 条）");
            }

            // ══════════ ⑥′ ToneMapNotAppliedToGainMap：GainMap 出口**不消费**计划层 tonemap ══════════
            // 判据来源：`CollectDegradations` 末条（`p.GainMap && it.ToneMapRequested && !it.ToneMapAuto`）。
            // 用例（= 实测的「误伤」格）：**SDR 源** + 用户**显式** tonemap + GainMap。
            //   改动前该组合在 `ColorIntentFactory` 的 tonemap 装配门被 Reject（连 GainMap 出口都没进）；
            //   现在放行并由本 Code 诚实登记「该选项未生效」（产出不变，只有 Kind 翻成降级）。
            CI GainMapWithToneMap(CS src, bool gm, bool auto) => new()
            {
                Strategy = ST.Recommended, Source = src, Format = CE.CapsFor("jpg"),
                TargetBitDepth = 8, AllowApproximateCurve = false, CarryScope = CSC.All,
                GainMapRequested = gm, ToneMapRequested = true,
                ToneMap = FfmpegGui.Services.ColorMapping.ToneMapMode.Hable, ToneMapAuto = auto,
            };
            {
                var pos = CE.Plan(GainMapWithToneMap(srgbTag, true, false));
                Note(pos);
                Check(pos.GainMap && pos.Action != CA.Reject,
                    $"ToneMapNotAppliedToGainMap 正向前置：须为 GainMap 出口且产出（实为 {Show(pos)}）");
                Check(pos.Verdict?.Kind == VK.ProceedWithDegradation && Has(pos, DG.ToneMapNotAppliedToGainMap),
                    $"ToneMapNotAppliedToGainMap 正向：{DG.ToneMapNotAppliedToGainMap} 必须被登记且 "
                    + $"Kind={VK.ProceedWithDegradation}（实为 {Show(pos)}）");

                // 负控①：只把 **GainMap 关掉**（其余一字不动）⇒ 该 Code 必须消失。
                //   这是「判据真的跟着 GainMap 位走」的直接证据：若判据被写成只看 ToneMapRequested，本组必红。
                var neg1 = CE.Plan(GainMapWithToneMap(srgbTag, false, false));
                Note(neg1);
                Check(!neg1.GainMap && !Has(neg1, DG.ToneMapNotAppliedToGainMap),
                    $"ToneMapNotAppliedToGainMap 负控①：非 GainMap 格不得登记该 Code（实为 {Show(neg1)}）");

                // 负控②：只把 **ToneMapAuto 打开**（GainMap 仍开）⇒ 该 Code 必须消失。
                //   理由：自动兜底（HDR 源 + 容器不支持 HDR）的目的就是「把 HDR 压成可看的 SDR 底图」，
                //   而 GainMap 出口的分段 Reinhard 正是干这件事 ⇒ 目的已达成，不构成损失。
                //   少了这条，「每一次 HDR→JPEG GainMap 都被误报成降级」不会被任何断言发现。
                var neg2 = CE.Plan(GainMapWithToneMap(srgbTag, true, true));
                Note(neg2);
                Check(neg2.GainMap && !Has(neg2, DG.ToneMapNotAppliedToGainMap),
                    $"ToneMapNotAppliedToGainMap 负控②：ToneMapAuto 格不得登记该 Code（实为 {Show(neg2)}）");
            }

            // ══════════ ⑦ 自洽性 + 覆盖面（对 contract 同源网格全格断言）══════════
            var formats = new[] { "png", "jpg", "tiff", "webp", "avif", "jxl", "gif", "heic" };
            var sources = new (string Name, CS D)[]
                { ("sRGB仅标签", srgbTag), ("sRGB带ICC", srgbIcc), ("P3带ICC", p3Icc), ("HDR-PQ", pq2020),
                  ("HDR-HLG", hlg2020), ("Adobe带ICC", adobe), ("无标签", untagged) };
            var strategies = new[] { ST.Recommended, ST.CarryIcc, ST.BakeCicpOnly, ST.Manual };
            var viol = new System.Collections.Generic.List<string>();
            int cells = 0, degradated = 0, produced = 0, rejected = 0, producedEmpty = 0;
            foreach (var st in strategies)
                foreach (var fmt in formats)
                    foreach (var (sname, src) in sources)
                    {
                        var it = new CI
                        {
                            Strategy = st, Source = src, Format = CE.CapsFor(fmt),
                            TargetBitDepth = 8, AllowApproximateCurve = false, CarryScope = CSC.All,
                            Manual = st == ST.Manual ? MI.Create(true, "Display P3", "smpte432", "iec61966-2-1", null)
                                                     : MI.Create(false, null, null, null, null),
                        };
                        if (st == ST.Manual) { it.TargetExplicit = true; it.Target = p3Icc; }
                        var p = CE.Plan(it);
                        cells++;
                        Note(p);
                        var v = p.Verdict;
                        if (v == null) { viol.Add($"[{st}/{fmt}/{sname}] Verdict 为 null"); continue; }
                        if (v.Kind == VK.ProceedWithDegradation) degradated++;
                        if (p.Action == CA.Reject) rejected++; else produced++;
                        void V(bool ok, string msg) { if (!ok) viol.Add($"[{st}/{fmt}/{sname}] {msg}"); }
                        // 自洽（三条互相钉住；**不**写成 `Kind==Proceed ⇔ Count==0`，
                        // 因为 Reject 格同样是 Count==0 却不是 Proceed）：
                        //   ① ProceedWithDegradation ⇔ 非空；
                        //   ② Proceed ⇒ 空（即"Proceed + 非空"这一不自洽状态被禁掉）；
                        //   ③ Reject ⇔ Action==Reject，且 Reject 格必须为空。
                        V((v.Kind == VK.ProceedWithDegradation) == (v.Degradations.Count > 0),
                          $"Kind={v.Kind} 与 Degradations.Count={v.Degradations.Count} 不自洽");
                        V(v.Kind != VK.Proceed || v.Degradations.Count == 0,
                          $"Kind=Proceed 却带 {v.Degradations.Count} 条 Degradations（不自洽状态）");
                        V((v.Kind == VK.Reject) == (p.Action == CA.Reject),
                          $"Kind={v.Kind} 与 Action={p.Action} 不自洽");
                        V(p.Action != CA.Reject || v.Degradations.Count == 0,
                          $"Reject 格却登记了 {v.Degradations.Count} 条 Degradations");
                        if (p.Action != CA.Reject && v.Degradations.Count == 0) producedEmpty++;
                        // 投影一致性：Action/Reason/Advice 必须是计划的兼容投影（一字不改）
                        V(v.Action == p.Action && v.Reason == p.Reason && v.Advice == p.Advice,
                          "Verdict 的 Action/Reason/Advice 与计划不一致（兼容投影被破坏）");
                        // Code 去重：同一 Code 不得重复登记（GUI/门禁按 Code 计数）
                        for (int i = 0; i < v.Degradations.Count; i++)
                            for (int j = i + 1; j < v.Degradations.Count; j++)
                                V(v.Degradations[i].Code != v.Degradations[j].Code,
                                  $"重复登记 Code={v.Degradations[i].Code}");
                    }
            Check(viol.Count == 0,
                $"verdict 自洽性：{cells} 格（产出 {produced} 含降级 {degradated}、拒绝 {rejected}）零违规"
                + (viol.Count > 0 ? " 例如: " + string.Join(" | ", viol.GetRange(0, Math.Min(8, viol.Count))) : ""));
            // 任务书要求的等价表述（**限定在已产出的格上**）：`Kind==Proceed ⇔ Degradations 为空`。
            Check(producedEmpty + degradated == produced,
                $"verdict 自洽性：已产出 {produced} 格必须恰好二分（Proceed {producedEmpty} + "
                + $"{VK.ProceedWithDegradation} {degradated}）（实为 {producedEmpty + degradated}）");

            // 覆盖面双向钉住：**每个已填 Code 至少被命中一次**（否则正向断言缺失）；
            // 且**不得**出现未登记在案（未被本模式断言）的 Code（否则新 Code 会静默溜过门禁）。
            var filled = new[] { DG.BitDepthReduced, DG.GamutClipped, DG.GamutCompressed, DG.UnlabeledAssumedSrgb,
                                 DG.NoIccCarrier, DG.ContainerCannotCarryIcc, DG.ToneMapNotAppliedToGainMap };
            foreach (var c in filled)
                Check(seen.Contains(c), $"覆盖：{c} 至少被一条正向断言命中");
            var unexpected = new System.Collections.Generic.List<string>();
            foreach (var c in seen) if (Array.IndexOf(filled, c) < 0) unexpected.Add(c);
            Check(unexpected.Count == 0,
                $"覆盖：不得出现未被断言登记的 Code（实际多出: {string.Join(",", unexpected)}）");
        }
    }
}
