using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using Tests.Shared;
using FfmpegGui.Services;
using TC = FfmpegGui.Services.ColorMapping.TransferCurve;
using CK = FfmpegGui.Services.ColorMapping.ColorKernels;
using CM = FfmpegGui.Services.ColorMapping.ColorMetrics;
using CS = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor;
using CE = FfmpegGui.Services.ColorMapping.ColorMappingEngine;
using CI = FfmpegGui.Services.ColorMapping.ColorIntent;
using CA = FfmpegGui.Services.ColorMapping.ColorAction;
using CB = FfmpegGui.Services.ColorMapping.ColorBackend;
using CL = FfmpegGui.Services.ColorMapping.ColorLoss;
using ST = FfmpegGui.Models.ColorStrategy;
using DC = FfmpegGui.Services.ColorMapping.DescriptorConfidence;
using OR = FfmpegGui.Services.ColorMapping.OverrideReason;
using AC = FfmpegGui.Services.ColorMapping.AnnotChoice;
using CSC = FfmpegGui.Services.ColorMapping.CarryScope;
using MI = FfmpegGui.Services.ColorMapping.ManualIntent;
using CP = FfmpegGui.Services.ColorMapping.ColorTransformPlan;
using GF = FfmpegGui.Services.ColorMapping.RawGamutFit;
using VK = FfmpegGui.Services.ColorMapping.VerdictKind;
using DG = FfmpegGui.Services.ColorMapping.DegradationCodes;
using F709 = FfmpegGui.Services.ColorMapping.Transfer709Curve;
using AAS = FfmpegGui.Services.AppSettingsService;

namespace Tests.Core
{
    // Generated by _gen-mode-split.ps1: the mode body was copied VERBATIM out of
    // CoreGroup.cs (logic / strings / indentation unchanged).
    // Motive: split one subsystem further into one-file-per-mode so that a change
    // touches only that mode, not the whole monolith.
    // The class became `partial` so all call sites (Program.cs -> CoreGroup.Run*())
    // stay byte-identical. Assertion count MUST NOT change: acceptance = per-mode
    // readings identical before vs after the split.
    // NOTE: ASCII-only on purpose (see _probe-cjk-hardcode-scan.ps1 UI bucket).
    internal static partial class CoreGroup
    {
        private static void ProbeWire()
        {
            var sdr = "tests/output/sources/src_8bit.png";
            var pq = "tests/output/validate/src_hdr.png";   // 带真 cICP(9,16) 的 HDR 素材（由 ensure-fixtures 产出）
            if (!File.Exists(sdr) || !File.Exists(pq)) { Check(false, "素材缺失（先跑 generate-sources.ps1 + ensure-fixtures.ps1）"); return; }
            // 防“假 HDR 素材”：源本身必须被探测为 PQ，否则后面的 tonemap 用例没有意义
            var mHdr = FfmpegGui.Services.FfmpegCommandBuilder.ProbeInputColorMetadata(pq);
            Check(mHdr.colorTrc == "smpte2084",
                $"HDR 素材确实被探测为 PQ（实际 trc={mHdr.colorTrc ?? "null"}）——否则素材未带 cICP");
            FfmpegGui.Models.FfmpegOptions O(string fmt, string? cs = null, string? tm = null, string? inPath = null,
                                            double? sdrPeak = null, bool adv = false, string? trc = null)
                => new() { Format = fmt, ColorSpace = cs ?? "auto", ColorStrategy = FfmpegGui.Models.ColorStrategy.Recommended,
                           ColorToneMap = tm ?? "none", BitDepth = 8, UseAdvancedColorParameters = adv, ColorTrc = trc,
                           // 路由门要求“引擎已承接所设参数”；默认质量才算不干涉编码出口
                           Quality = FfmpegGui.Models.FfmpegOptions.GetDefaultQuality(fmt),
                           ColorSdrPeakNits = sdrPeak ?? 100 };

            // 1) SDR 源 + auto 目标：可装配，且不应请求映射
            var i1 = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("png"), sdr, out var r1);
            Check(i1 != null && !i1!.ToneMapRequested && i1.Target == null, $"png/auto 装配 OK（reason={r1 ?? "无"}）");
            var p1 = CE.Plan(i1!);
            Check(p1.IsOk && p1.ColorLoss == CL.None, $"png/auto 计划不改像素（{p1.Action}/{p1.ColorLoss}）");

            // 2) 显式目标 P3：可装配且应做矩阵映射
            var i2 = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("png", "Display P3"), sdr, out var r2);
            var p2 = i2 == null ? null : CE.Plan(i2);
            Check(i2 != null && i2.TargetExplicit && i2.Target?.PrimariesToken == "smpte432",
                $"目标 P3 解析正确（{(i2 == null ? r2 : i2.Target?.Name)}）");
            Check(p2 != null && p2.IsOk && p2.Matrix != null, $"P3 目标发生矩阵映射（act={p2?.Action}）");

            // （此处曾加过一条“BT.2020 目标的 ICC TRC ≡ 输出 TRC”正例，但它挑错了格子：
            //   PNG 的 CanHaveBothIccAndCicp=false ⇒“ICC 优先”会把 Out* 清空（合法），
            //   没有“两条都声明”可比。面它倒出了一个更结构的问题：
            //   QueueProcessor 的 png3 后置步骤会往 PNG 写 cICP，不看能力表的“不可共存”裁决
            //   ⇒ “PNG 能否 ICC+CICP 并存”在两处答案不同，这是 P7 步骤 3 要收敛的范围。）

            // 3) HDR 源 + bt2446a + SDR 目标：挂载 Method A 并归类 ToneMapped
            var i3 = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("png", "sRGB", "bt2446a", pq, 300), pq, out var r3);
            var p3 = i3 == null ? null : CE.Plan(i3);
            var TM2 = FfmpegGui.Services.ColorMapping.ToneMapMode.Bt2446A;
            Check(i3 != null && i3.ToneMapRequested && i3.ToneMap == TM2, $"bt2446a 装配（{(i3 == null ? r3 : i3.ToneMap.ToString())}）");
            // ⚠ 加严：必须确认 Tone 真的“激活”（headroom>1），而不是靠另一条分支给出 ToneMapped
            Check(p3?.Tone?.Mode == TM2 && p3.Tone.Active && p3.Tone.Headroom > 1.5
                  && p3.ColorLoss == CL.ToneMapped,
                $"bt2446a 真的生效（active={p3?.Tone?.Active} headroom={p3?.Tone?.Headroom:F2} loss={p3?.ColorLoss}）");
            Check(System.Math.Abs((p3?.Tone?.SdrPeakNits ?? 0) - 300) < 1e-9, $"L_SDR 透传（{(p3?.Tone?.SdrPeakNits).ToString() ?? "-"}）");

            // 4) 拒绝/回退路径：必须返回 null 并给原因
            Check(FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("png", "sRGB", "bt2390", pq), pq, out var rr1) == null
                  && (rr1 ?? "").Contains("出处"), $"bt2390 不装配（{rr1}）");
            Check(FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("png", "sRGB", "bogus"), sdr, out var rr2) == null,
                  $"未知 tone-map 值不装配（{rr2}）");
            // **2026-09-17 契约更新**：GIF 已接入引擎 ⇒ 意图**必须装配**（原断言 `== null` 锁的是
            // "GIF 尚未接入"这一历史状态）。「无色彩通路」这个**能力事实**不再由装配层表达，
            // 改由规划层给结局（不改像素 / 映射到 sRGB 工作空间，两种都**不写标注**）。
            // ⚠ 无通路容器里**放行 gif 与 jxr**（两者都已接入引擎；jxr 的执行出口 = BMP/TIFF 中转 +
            //   JxrEncApp，2026-09-17 接入）。DNG 需传感器 Bayer 数据，PPM/BMP/HEIC 无接入计划
            //   ⇒ "其余不放行"仍由下面的 heic 守着。
            var ig = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("gif"), sdr, out var rr3);
            Check(ig != null, $"GIF 已接入 ⇒ 意图必须装配（reason={rr3 ?? "无"}）");
            if (ig != null)
            {
                var pg = CE.Plan(ig);
                Check(pg.IsOk && pg.UnlabeledAssumedSrgb,
                    $"GIF 计划：不写任何色彩标注（Action={pg.Action} UnlabeledAssumedSrgb={pg.UnlabeledAssumedSrgb}）");
            }
            // JXR 与 GIF **同款结局**（容器无色彩通路 ⇒ 映射到 sRGB 工作空间且不写标注），
            // 且必须**置 ExternalEncoderExit** —— 否则计划说"像素改了"、执行层却走 ffmpeg 编码器，
            // 而本工具链的 ffmpeg **没有 jxr 编码器** ⇒ 必然产不出产物（不是静默降级，是直接失败）。
            var ij = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("jxr"), sdr, out var rr3b);
            Check(ij != null, $"JXR 已接入 ⇒ 意图必须装配（reason={rr3b ?? "无"}）");
            if (ij != null)
            {
                Check(ij.ExternalEncoderExit, "JXR 意图必须置 ExternalEncoderExit（ffmpeg 无 jxr 编码器）");
                var pj = CE.Plan(ij);
                Check(pj.IsOk && pj.ExternalEncoderExit && pj.UnlabeledAssumedSrgb,
                    $"JXR 计划：ExternalEncoderExit + 不写标注（Action={pj.Action} exit={pj.ExternalEncoderExit} "
                    + $"unlabeled={pj.UnlabeledAssumedSrgb}）");
            }
            Check(FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("heic"), sdr, out var rr4) == null,
                  $"HEIC（无写入通路）不装配（{rr4}）");
            // HDR 源 + 显式 HDR 目标 + 请求映射 ⇒ 矛盾，不装配
            Check(FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("png", "BT.2020 PQ", "hable", pq), pq, out var rr5) == null,
                  $"tone-map 与 HDR 目标矛盾时不装配（{rr5}）");
            // SDR 源却请求 tonemap ⇒ 不装配（避免无意义压暗）
            Check(FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(O("png", "sRGB", "mobius"), sdr, out var rr6) == null,
                  $"非 HDR 源请求 tonemap 时不装配（{rr6}）");

            // 5) A2 前置件：路由判据（纯函数，与 QueueProcessor 插入点无关）
            // **2026-09-16 契约更新**：默认改为**走引擎**（用户指令「清理传统管线」），
            // `legacy` 降级为显式逃生门。故这里同时锁两条：
            //   ① 显式 legacy ⇒ 不路由（逃生门有效，可用于 A/B 与排查）；
            //   ② **默认（不传参）⇒ 路由**（默认值本身就是契约，必须有断言守着，
            //      否则"哪天被改回 legacy"无人发现）。
            var R = typeof(FfmpegGui.Services.ColorMapping.ColorEngineRouter);
            var eng = O("png"); eng.ColorEngine = "engine";
            var leg = O("png"); leg.ColorEngine = "legacy";
            var def = O("png");
            Check(!FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(leg, "o.png", false),
                "显式 legacy ⇒ 不路由（逃生门有效）");
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(def, "o.png", false),
                "**默认（不传 --color-engine）⇒ 路由到引擎**（默认值即契约）");
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(eng, "o.png", false), "engine + png ⇒ 路由");
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(eng, "o.webp", false), "engine + webp ⇒ 路由");
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(eng, "o.tif", false), "engine + tif ⇒ 路由");
            // **2026-09-17**：gif 接入引擎出口（调色板链 + 第二输入补 alpha）⇒ 必须路由。
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(eng, "o.gif", false),
                "engine + gif ⇒ 路由（2026-09-17 接入）");
            // 负控：仍在白名单外的格式不得被"连带放行"（ppm 无色彩通路且无接入计划）。
            // ⚠ 2026-09-17（S2）：`BlockReason` 返回 `EngineBlock?` ⇒ 判据一律打 **Code**（禁止匹配 Text）。
            var bppm = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(eng, "o.ppm", false);
            Check(bppm?.Code == "FormatNotSupported",
                $"engine + ppm ⇒ 不路由且 Code=FormatNotSupported（{bppm?.Text}）");
            // **2026-09-17：jxl 接入引擎出口（ffmpeg 的 libjxl 子情形）**。两条断言成对锁住分级，
            // 二者**只差一个变量**（EncoderBackend）⇒ "把该变量改回去"就是一次干净的变异：
            //   ① backend=Ffmpeg ⇒ **路由**（与 png/avif/gif 同型）；
            //   ② backend=Cjxl（本机装了 cjxl 时的**默认后端**，EncoderDetectionService:55）
            //      ⇒ **同日第二轮起也路由**（cjxl 执行出口接入，见下方契约变更说明）。
            // 分级结论因此从「按后端拦」变成「按**出口是否存在**判」—— 这正是本轮的实质：
            // 原来挡住 Cjxl 的**不是**"它是外部编码器"，而是"引擎没有能兑现它的出口"。
            var jxlFf = O("jxl"); jxlFf.ColorEngine = "engine";
            jxlFf.EncoderBackend = FfmpegGui.Services.EncoderBackend.Ffmpeg;
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(jxlFf, "o.jxl", false),
                "engine + jxl(backend=Ffmpeg) ⇒ 路由（2026-09-17 接入 ffmpeg-libjxl 子情形）");
            // **2026-09-17（cjxl 出口轮）：契约变更 —— jxl+Cjxl 由"被挡"改为"路由"**。
            // 变更理由：引擎新增了 cjxl 执行出口（`RawColorPipeline.EncodeJxlViaCjxlAsync`），
            // 它**兑现了**原来挡它的那条理由（"cjxl 不吃 rawvideo、色彩语义 ffmpeg 参数表达不了"）：
            // 出口把变换后的 raw 经 PPM/PAM 管道喂 cjxl，色彩语义由 `-x color_space=` /
            // `-x icc_pathname=` / `--intensity_target=` 表达（后两者复用**同一份**
            // `CjxlService.BuildCjxlArguments`，不另写一套）。
            // ⚠ 这是**有意**的契约变更：旧断言（⇒ 不路由）会转红，**不要**为了让旧断言变绿而放弃放宽。
            var jxlCjxl = O("jxl"); jxlCjxl.ColorEngine = "engine";
            jxlCjxl.EncoderBackend = FfmpegGui.Services.EncoderBackend.Cjxl;
            var br = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(jxlCjxl, "o.jxl", false);
            Check(br == null, $"engine + jxl(backend=Cjxl) ⇒ **路由**（2026-09-17 cjxl 出口接入；block={br?.Text ?? "无"}）");
            // 计划位（`ExternalEncoderExit`）：**只有 jxl+Cjxl 置位**。ffmpeg 子情形绝不能也走外部管道
            //（多一个进程、还会丢掉 ffmpeg 侧参数）⇒ 两条成对断言，只差 EncoderBackend 一个变量。
            var itCjxl = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(jxlCjxl, sdr, out var whyCjxl);
            Check(itCjxl is { ExternalEncoderExit: true },
                $"意图装配：jxl + Cjxl ⇒ ExternalEncoderExit=true（{whyCjxl ?? "ok"}）");
            var itFf = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(jxlFf, sdr, out var whyFf);
            Check(itFf is { ExternalEncoderExit: false },
                $"意图装配：jxl + Ffmpeg ⇒ ExternalEncoderExit=false（走普通 ffmpeg 出口；{whyFf ?? "ok"}）");
            // 负控：**其他格式** + 外部后端仍必须被挡 —— 放宽不得外溢（cjpgli/cjpegli 尚无出口）。
            var jpgCjpegli = O("jpg"); jpgCjpegli.ColorEngine = "engine";
            jpgCjpegli.EncoderBackend = FfmpegGui.Services.EncoderBackend.Cjpegli;
            var brJpg = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(jpgCjpegli, "o.jpg", false);
            Check(brJpg?.Code == "ExternalBackend",
                $"engine + jpg(backend=Cjpegli) ⇒ 仍被挡（负控：放宽只对 jxl+Cjxl 生效；Code={brJpg?.Code}）");
            // ── cjxl 出口的命令行形态（纯函数层；CLI 端到端形态另见 verify-color-wiring 第 (10) 段）──
            // 要钉住的不变量：**色彩语义来自计划**（override），既不能凭空生成、也不能回头读 options。
            var cjxlOpts = O("jxl"); cjxlOpts.Quality = 75; cjxlOpts.JxlEffort = 7;
            var argsCs = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "-", "o.jxl", cjxlOpts, default, null, "Rec2100PQ", 1000);
            Check(argsCs.Contains("-x color_space=Rec2100PQ") && argsCs.Contains("--intensity_target=1000"),
                $"cjxl 出口命令行：色彩语义与显示峰值均来自计划（{argsCs}）");
            var argsNone = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "-", "o.jxl", cjxlOpts, default, null, null, 0);
            Check(!argsNone.Contains("color_space") && !argsNone.Contains("intensity_target"),
                $"cjxl 出口命令行：计划未给色彩语义时**不得凭空生成**标注（{argsNone}）");
            // ── cjxl 的 --photon_noise_iso：三条规则（2026-09-30 实机复现后定，取证 tests/output/t62/）──
            // ① **真执行永不输出 `auto`**：cjxl 的解析器是 `ParseFloat && >= 0`（libjxl
            //    `tools/cjxl_main.cc:ParsePhotonNoiseParameter`），收到 `auto` 会在读 stdin 之前
            //    退出 1、零产物，写方表现为 broken pipe（"管道正在被关闭"）。
            // ② 预览**保留** `auto`：那是"待从 EXIF 解析"的显示意图，不发给编码器。
            // ③ **distance=0 时不发噪声**：实测 `-d 0 --photon_noise_iso=400` 让 99.46% 的 16-bit
            //    样本偏离源（平均偏差 30875/65535），而 jxlinfo 对两者都报 "(possibly) lossless"
            //    —— 噪声由解码端按帧头参数合成，体积只多 10 B ⇒ 从文件大小查不出来。
            //    判据是**实际发出的 distance**，不是 Lossless 复选框（Quality=100 也算数学无损）。
            string pnLog = "";
            Action<string> pnSink = s => pnLog += s;
            var pnLossy = O("jxl"); pnLossy.Quality = 75; pnLossy.JxlEffort = 7;   // distance 2.4（2026-10-02 起按 libjxl 官方曲线；旧公式算出来是 3.8）
            var pnAutoUnresolved = O("jxl"); pnAutoUnresolved.Quality = 75; pnAutoUnresolved.JxlEffort = 7;
            pnAutoUnresolved.CjxlAutoPhotonNoise = true;   // CjxlPhotonNoiseIso 保持 0 = 未解析
            var a1 = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "-", "o.jxl", pnAutoUnresolved, default, null, null, 0, false, pnSink);
            Check(!a1.Contains("photon_noise_iso"),
                $"① 真执行 + 未解析的 auto ⇒ **省略该 flag**，绝不发占位串（{a1}）");
            Check(pnLog.Contains("dropped"),
                $"① 省略时**点名**（不静默吞掉用户设置）：[{pnLog.Trim()}]");
            var a2 = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "-", "o.jxl", pnAutoUnresolved, default, null, null, 0, true, null);
            Check(a2.Contains("--photon_noise_iso=auto"),
                $"② 预览仍显示 auto 占位（有损距离下）：[{a2}]");
            var pnLossless = O("jxl"); pnLossless.Lossless = true; pnLossless.JxlEffort = 7;
            pnLossless.CjxlPhotonNoiseIso = 400;
            pnLog = "";
            var a3 = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "-", "o.jxl", pnLossless, default, null, null, 0, false, pnSink);
            Check(a3.Contains("-d 0") && !a3.Contains("photon_noise_iso"),
                $"③ 无损 ⇒ 只有 -d 0、不带噪声（叠加会静默破坏逐比特无损）（{a3}）");
            Check(pnLog.Contains("photon noise skipped"), $"③ 无损丢弃时点名：[{pnLog.Trim()}]");
            pnLossy.CjxlPhotonNoiseIso = 400;
            var a4 = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "-", "o.jxl", pnLossy, default, null, null, 0, false, null);
            Check(a4.Contains("--photon_noise_iso=400"),
                $"④ **正控**：有损 + 数值 ISO ⇒ flag 照发（否则 ①③ 只是「功能没接上」的假绿）（{a4}）");
            var pnQ100 = O("jxl"); pnQ100.Quality = 100; pnQ100.JxlEffort = 7; pnQ100.CjxlPhotonNoiseIso = 400;
            var a5 = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "-", "o.jxl", pnQ100, default, null, null, 0, false, null);
            Check(a5.Contains("-d 0.0") && !a5.Contains("photon_noise_iso"),
                $"⑤ 判据是**发出的 distance**而非复选框：Quality=100 ⇒ -d 0.0 ⇒ 同样不发噪声（{a5}）");
            // ── jbrd 无损重封装（2026-09-30：开关默认启用，且此前被三道独立失效永久掐死）──
            // 实测失效链（取证 tests/output/t64/）：模型默认 false + 采集式「面板不可见⇒false」
            //   + 与一只**默认勾着**的「保留 Ultra HDR 增益图」无条件相与 ⇒ 三条里任一条都足以让
            //   它恒假 ⇒ 默认配置下 JPEG→JXL 从来走的是 `-d 3.8` 像素重编码（产物 908 kB，非无损）。
            // ⚠ 语义分工（本组要钉的就是这个）：`DefaultJxlLosslessJpeg` = **开关**默认（true）；
            //   `FfmpegOptions.JxlLosslessJpeg` = **本次有效值**，必须与「输入真是 JPEG」相与 ——
            //   因为 `ImageEncoderArgs` 只看这个布尔就拦掉整个 jxl 引擎路线，而它看不到输入格式。
            Check(FfmpegGui.Models.FfmpegOptions.DefaultJxlLosslessJpeg
                    && !new FfmpegGui.Models.FfmpegOptions().JxlLosslessJpeg,
                "jbrd-① 开关默认开=true 而模型字段(有效值)默认=false；两者必须分家，否则 PNG→JXL 会被误拦出引擎");
            var jbOn = O("jxl"); jbOn.JxlEffort = 7; jbOn.Threads = 0; jbOn.JxlLosslessJpeg = true;
            var jbFile = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "in.jpg", "o.jxl", jbOn, default, null, null, 0, false, null);
            Check(jbFile.Contains("-d 0") && jbFile.Contains("--lossless_jpeg=1"),
                $"jbrd-② 有效值+真 JPEG 输入 ⇒ 发出无损重封装（{jbFile}）");
            pnLog = "";
            var jbPipe = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "-", "o.jxl", jbOn, default, null, null, 0, false, pnSink);
            Check(!jbPipe.Contains("--lossless_jpeg=1") && pnLog.Contains("input is not a JPEG file"),
                $"jbrd-③ 有效值开着但输入是管道 ⇒ **不冒充**重封装且点名（日志=[{pnLog.Trim()}] 命令=[{jbPipe}]）");
            var jbOff = O("jxl"); jbOff.JxlLosslessJpeg = false; jbOff.Quality = 75;
            var jbOffArgs = FfmpegGui.Services.CjxlService.BuildCjxlArguments(
                "in.jpg", "o.jxl", jbOff, default, null, null, 0, false, null);
            Check(jbOffArgs.Contains("--lossless_jpeg=0"),
                $"jbrd-④ **正控**：手动关掉 ⇒ 显式发 --lossless_jpeg=0（不是省略，cjxl 对 JPEG 默认是 1）（{jbOffArgs}）");
            var jbRoute = O("jxl"); jbRoute.ColorEngine = "engine";
            jbRoute.EncoderBackend = FfmpegGui.Services.EncoderBackend.Cjxl;
            jbRoute.JxlLosslessJpeg = true;
            var jbBr = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(jbRoute, "o.jxl", false);
            Check(jbBr?.Code == "EncoderUnsupportedSetting",
                $"jbrd-⑤ 有效值为真时引擎**必须拦**（引擎要先解码，结构上无法复制 DCT 系数）⇒ 实 Code={jbBr?.Code ?? "null"}");
            // 负控（与 ⑤ 只差一个布尔）：有效值为假 ⇒ jxl+Cjxl 照旧路由 —— 放宽/拦截都不得外溢。
            var jbRouteOff = O("jxl"); jbRouteOff.ColorEngine = "engine";
            jbRouteOff.EncoderBackend = FfmpegGui.Services.EncoderBackend.Cjxl;
            var jbBr2 = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(jbRouteOff, "o.jxl", false);
            Check(jbBr2 == null, $"jbrd-⑥ 负控：有效值 false ⇒ 仍走引擎出口（block={jbBr2?.Code ?? "无"}）");
            // ── jbrd 开关**不得改写在 ffmpeg-libjxl 后端上的质量轴**（2026-10-01 实测后补）──
            // 该开关 09-30 起默认启用，而 `FfmpegCommandBuilder` 里曾有一条
            // `if (JxlLosslessJpeg) ⇒ -distance 0` 的特例：ffmpeg 的 libjxl 做不到 jbrd（09-19 实测），
            // 这条特例只剩副作用 —— 实测 `-e Ffmpeg` 下 q=30/50/75/90 **产物全是 58.3 kB、命令行恒为
            // -distance 0**（关掉后恢复质量轴起效）。默认值一翻，这格从罕见变成常态。
            // ⚠ 2026-10-02：下方 qa-① 的期望值随 JXL distance 公式换成 libjxl 官方曲线而更新
            //   （旧 10.5 / 1.5 ⇒ 新 6.4 / 1.0；公式见 ImageEncoderArgs.MapJxlDistance）。
            // ⚠ 这里显式给 BitDepth，避免 BuildArguments 去探测不存在的输入而把读数搅浑。
            string JxlCmd(int q, bool lossless, bool? modular)
            {
                var o = O("jxl"); o.Quality = q; o.Lossless = lossless; o.BitDepth = 8;
                o.JxlLosslessJpeg = true; o.JxlModular = modular;
                return FfmpegGui.Services.FfmpegCommandBuilder.BuildArguments(o, "in.jpg", "out.jxl");
            }
            var qa30 = JxlCmd(30, false, null); var qa90 = JxlCmd(90, false, null);
            Check(qa30.Contains("-distance 6.4") && qa90.Contains("-distance 1.0")
                    && !qa30.Contains("-distance 0") && !qa90.Contains("-distance 0"),
                $"qa-① 开关开着也不吞质量轴：q30⇒6.4 / q90⇒1.0（实 [{qa30}] / [{qa90}]）");
            // ⚠ P1-3（2026-10-03 复查）：`MapJxlDistanceInverse` 只是**近似**互逆（正函数 1 位小数取整），
            //   旧注释自称"严格互逆"（自相矛盾），且旧锚点 q30/q90 恰落在互逆点上 ⇒ 结构性抓不到差异。
            //   此处**显式钉死往返读数**并把锚点选在**非互逆点 q75**（→2.4→74，差 1）以恢复判别力：
            //   q75 的 74 是量化的**诚实结果**（不是缺陷）—— 若日后有人"修"成严格互逆，这条会红，逼一次有意识决策。
            int rt75 = FfmpegGui.Models.FfmpegOptions.MapJxlDistanceInverse(
                FfmpegGui.Models.FfmpegOptions.MapJxlDistanceForward(75));
            int rt30 = FfmpegGui.Models.FfmpegOptions.MapJxlDistanceInverse(
                FfmpegGui.Models.FfmpegOptions.MapJxlDistanceForward(30));
            Check(rt75 == 74 && rt30 == 30,
                $"jxl-rt 反函数往返（近似互逆）：非互逆点 q75 ⇒ {rt75}（期望 74，差 1 属量化）；互逆点 q30 ⇒ {rt30}（期望 30）");
            var qaL = JxlCmd(75, true, null);
            Check(qaL.Contains("-distance 0"), $"qa-② 正控：真要无损由 Lossless 决定（{qaL}）");
            var qaM = JxlCmd(75, false, true);
            Check(qaM.Contains("-modular 1"), $"qa-③ 特例曾漏发的 -modular 现在跟着单一真值走（{qaM}）");
            // **2026-09-17 单一真值锁**：白名单此前在 `ColorEngineRouter` 与 `ImageEncoderArgs` 各写一份
            // 字面量（后者**全仓无调用者**，只在 Router 文档里被引用）⇒ 已合并为
            // `ImageEncoderArgs.IsEngineEncodable` **一份**，Router 改为调用它。
            // 本断言把合并后的那一份**逐字钉死**：今后新增/移除出口格式必须同步改探针（防再次漂移）。
            string[] encWhitelist = { "png", "apng", "tiff", "tif", "webp", "jpg", "jpeg", "avif", "gif", "jxl", "jxr" };
            string[] encOutside = { "dng", "ppm", "bmp", "heic", "heif", "qoi" };
            var encMissing = new StringBuilder(); var encExtra = new StringBuilder();
            foreach (var f in encWhitelist)
                if (!FfmpegGui.Services.ColorMapping.ImageEncoderArgs.IsEngineEncodable(f)) encMissing.Append(f).Append(' ');
            foreach (var f in encOutside)
                if (FfmpegGui.Services.ColorMapping.ImageEncoderArgs.IsEngineEncodable(f)) encExtra.Append(f).Append(' ');
            Check(encMissing.Length == 0 && encExtra.Length == 0,
                $"引擎出口白名单必须恰为 {string.Join("/", encWhitelist)}（缺=[{encMissing}] 多=[{encExtra}]）");
            // ── JXL 的 ICC 通路：**引擎出口只能写 CICP**（2026-09-17 实测，本次接入的设计约束）──
            // 实测事实链（两条独立路径都不通 ⇒ 不是"命令写错"）：
            //   ① **编码器丢弃**：`-vf iccgen` 生成的 ICC 不落盘 —— legacy 参照 ref.jxl 与引擎出口产物，
            //      exiftool 都读不出 ICC（方法自检：读 cjxl 产的 cjxl_lossless.jxl 同样读不出）；
            //   ② **后置被拒**：`exiftool "-icc_profile<=p3.icc" -overwrite_original w.jxl`
            //      ⇒ 退出码 **1**、`Error: [minor] Will wrap JXL codestream in ISO BMFF container for writing`、
            //      `0 image files updated`（**同一命令写 PNG 成功 584B**）⇒ 是 JXL 容器限制。
            // ⇒ `RawColorPipeline` 对「jxl + 计划要求附 ICC」**显式拒绝**（宁可硬失败，
            //    也不产出一个无任何色彩描述的 JXL —— 那正是历史偏色根因）。
            // 下面两条把这道门**为何不空转**钉住；第 3 条界定它是不是主路径（结论：不是）。
            var jxlCaps = CE.CapsFor("jxl");
            var proP = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor.FromNamedSpace("ProPhoto RGB");
            var p3d = FfmpegGui.Services.ColorMapping.ColorSpaceDescriptor.FromCicp("smpte432", "iec61966-2-1", "Display P3");
            Check(proP != null && p3d != null, "构造 ProPhoto / Display P3 描述符（JXL ICC 通路用例前置）");
            if (proP != null && p3d != null)
            {
                // 第三个参数 = **外部编码器出口**（#38）：这条断言讲的正是 cjxl 的 `-x color_space=`
                // 枚举宽度（ProPhoto 无处可标 ⇒ 只能走 ICC），故必须显式给 true；
                // 同一目标走 ffmpeg 的 libjxl 出口时该枚举**不适用**（`CapsAcceptsCicp(…, false)` 为真）。
                Check(!CE.CapsAcceptsCicp(jxlCaps, proP, true),
                    "jxl 的 CICP 枚举（sRGB/DisplayP3/Rec2100PQ/Rec2100HLG）表达不了 ProPhoto ⇒ 该目标只能走 ICC");
                var polJxl = new FfmpegGui.Services.ColorMapping.PlanPolicy
                { Format = jxlCaps, AllowApproximateCurve = false, ForceMapping = true, TargetExplicit = true };
                var pJxlIcc = CE.Plan(p3d, proP, polJxl);
                Check(pJxlIcc.AttachIcc && pJxlIcc.Action == CA.Map,
                    $"规划层对「jxl + 不可命名目标」确实要求附 ICC（act={pJxlIcc.Action} attachIcc={pJxlIcc.AttachIcc}）"
                    + " ⇒ 出口那道拒绝门不是恒 false 的空断言");
                // 第 3 条（**界定**）：CLI **到不了**上面那个组合 —— 目标描述符由
                // `EffectiveOutputColorTokens` 的 CICP 三元组构造（`ColorSpaceDescriptor.FromCicp`），
                // 装配层还会按容器能力钳制，故 CLI 得到的目标**恒为可 CICP 命名**的
                // ⇒ 规划层的「择一」规则（`EnforceContainerAnnotationRules`，jxl 的
                // `CanHaveBothIccAndCicp=false`）必然剥掉 AttachIcc。下面这条钉的就是这个不变量：
                // 「CLI 装配出的 jxl 计划**永不**同时要求『附 ICC + 改像素』」。
                // 门若变成主路径（该不变量被破坏）⇒ 本条转红，正是我们要的告警。
                var badJxl = O("jxl"); badJxl.ColorEngine = "engine";
                badJxl.UseAdvancedColorParameters = true; badJxl.ColorPrimaries = "smpte431"; badJxl.ColorTrc = "gamma22";
                var badJxlIt = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(badJxl, sdr, out var whyBadJxl);
                var badJxlPlan = badJxlIt == null ? null : CE.Plan(badJxlIt);
                Check(badJxlIt == null || !(badJxlPlan!.AttachIcc && badJxlPlan.Action == CA.Map),
                    "界定：CLI 装配出的 jxl 计划**永不**同时要求「附 ICC + 改像素」"
                    + $"（target={badJxlIt?.Target?.Name ?? ("装配失败: " + whyBadJxl)} "
                    + $"act={badJxlPlan?.Action} attachIcc={badJxlPlan?.AttachIcc}）"
                    + " ⇒ 出口那道门是兜底而非主路径");
                // 第 4 条：**执行体那道门本身**也要有牙（删掉它 ⇒ 本条转红）。
                // 刻意把门放在 `ProbeSizeAsync` **之前** ⇒ 这里可以用不存在的输入路径 + 任意存在的
                // ffmpeg 占位（`ffmpegOverride`），**不需要真素材、不启动任何子进程**（纯拒绝路径）。
                bool jxlIccThrew = false; string? jxlIccMsg = null;
                try
                {
                    FfmpegGui.Services.ColorMapping.RawColorPipeline.TransformFileAsync(
                        "tests/output/_no_such_input.png", "tests/output/_no_such_output.jxl",
                        pJxlIcc.ToSpec(), pJxlIcc, null, default, 1, Environment.ProcessPath)
                        .GetAwaiter().GetResult();
                }
                catch (InvalidOperationException ex) { jxlIccThrew = true; jxlIccMsg = ex.Message; }
                Check(jxlIccThrew && (jxlIccMsg ?? "").Contains("JXL 出口无法附 ICC"),
                    $"执行体的 JXL ICC 拒绝门确实生效（threw={jxlIccThrew} msg={jxlIccMsg}）");
                // 第 5 条（**分叉**，2026-09-17 cjxl 出口轮）：同一份「jxl + AttachIcc」计划，置上
                // `ExternalEncoderExit` 之后**不得**再被那道门拦住 —— 因为 cjxl 出口**真的能写 ICC**
                //（`-x icc_pathname=`，实测产物 jxlinfo 读回 P3 primaries）。
                // 判据：抛出的异常**不再是** ICC 门那一条（此处会因输入不存在而在更后面失败）
                // ⇒ 说明它**越过了**门。⚠ 把分叉改回"按扩展名判"（删掉 `&& !plan.ExternalEncoderExit`）⇒ 本条转红。
                var pForkPlan = CE.Plan(p3d, proP, polJxl);
                pForkPlan.ExternalEncoderExit = true;
                bool forkThrew = false; string? forkMsg = null;
                try
                {
                    FfmpegGui.Services.ColorMapping.RawColorPipeline.TransformFileAsync(
                        "tests/output/_no_such_input.png", "tests/output/_no_such_output.jxl",
                        pForkPlan.ToSpec(), pForkPlan, null, default, 1, Environment.ProcessPath)
                        .GetAwaiter().GetResult();
                }
                catch (InvalidOperationException ex) { forkThrew = true; forkMsg = ex.Message; }
                Check(!(forkThrew && (forkMsg ?? "").Contains("JXL 出口无法附 ICC")),
                    "ICC 拒绝门**按出口分叉**：置 ExternalEncoderExit 后不再按扩展名拦"
                    + $"（threw={forkThrew} msg={forkMsg}）");
            }
            // 第 6 条（2026-09-17 cjxl 出口轮**暴露并修复的真实缺陷**的回归锁）：
            // `CarryIcc` / `None` 两个 Action 的语义是"像素零改动"，但这类计划**不填**
            // `SrcCurve`/`DstCurve`/`Matrix`（`PlanCarry` 是提前 return 的分支）⇒ 会落进
            // `ToSpec()` 里 `?? TransferCurve.Linear` / `?? TransferCurve.Srgb` 两个**猜测式默认**
            // ⇒ 得到"按线性解码、按 sRGB 编码"的 spec ⇒ **整幅提亮**。
            // 实测（512x384 P3 源，jxl+Cjxl）：变换输出 == lin2srgb(解码输出)，平均绝对差 0.0000，
            // 均值 0.600 → 0.713。修复 = `ToSpec()` 按 Action 短路成恒等。
            // ⚠ 用**参考算子**直接钉"恒等"，不依赖任何素材/子进程；把短路删掉 ⇒ 0.6 会变成 0.798 ⇒ 转红。
            foreach (var noChange in new[] { CA.CarryIcc, CA.None })
            {
                var pNo = new FfmpegGui.Services.ColorMapping.ColorTransformPlan { Action = noChange };
                var spNo = pNo.ToSpec();
                var rt = FfmpegGui.Services.ColorMapping.ColorKernels.TransformPixelReference(0.6f, 0.6f, 0.6f, spNo);
                Check(spNo.Matrix == null && spNo.SrcCurve.Name == spNo.DstCurve.Name
                      && Math.Abs(rt.R - 0.6) < 1e-6 && Math.Abs(rt.G - 0.6) < 1e-6 && Math.Abs(rt.B - 0.6) < 1e-6,
                    $"{noChange} 计划的 ToSpec 必须是**恒等**（曲线同名={spNo.SrcCurve.Name}、矩阵空、0.6→{rt.R:F4}）"
                    + " —— 否则 cjxl 出口会把「像素零改动」的产物整幅提亮");
            }
            var bAnim = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(eng, "o.png", true);
            Check(bAnim?.Code == "AnimatedInput",
                $"动画输入 ⇒ 不路由（引擎是单帧）且 Code=AnimatedInput（{bAnim?.Text}）");
            // 诚实门（**2026-09-16 契约更新**）：引擎编码出口**已承接**质量/结构参数
            //（见 ImageEncoderArgs），故不再拒绝；但"承接了"必须真的落到编码器参数上，
            // 否则就是一句空话 —— 下面第二条断言即为此处的"牙"。
            var qOk = O("png"); qOk.ColorEngine = "engine"; qOk.Quality = 60;
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(qOk, "o.png", false) == null,
                "质量参数已由引擎编码出口承接 ⇒ 不再拒绝");
            var qArgs = FfmpegGui.Services.ColorMapping.ImageEncoderArgs.BuildEncoderOptions("png", qOk);
            int expectCl = FfmpegGui.Services.ColorMapping.ImageEncoderArgs.MapPngCompression(60);
            Check(qArgs.Contains($"-compression_level {expectCl}"),
                $"质量确实落到编码器参数（q=60 ⇒ -compression_level {expectCl}，实得「{qArgs.Trim()}」）");
            // **2026-09-16 契约更新**：最长边几何缩放**已接入引擎**（解码步复用同一个
            // `BuildMaxDimensionScaleFilter`）⇒ 不再拒绝。此处改为"不再拒绝"的正向断言；
            // "真的缩到限值"由 `verify-color-wiring.ps1` 第 (7) 节实测宽高守护（探针是纯函数层，看不到像素）。
            var geo = O("png"); geo.ColorEngine = "engine"; geo.EnableMaxDimension = true;
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(geo, "o.png", false) == null,
                "最长边几何缩放已承接 ⇒ 不再拒绝");
            var old = O("png"); old.ColorEngine = "engine"; old.TonemapCurve = "reinhard";
            var bo = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(old, "o.png", false);
            Check(bo?.Code == "LegacyTonemapCurve",
                $"旧 --tonemap-curve 未接入 ⇒ 拒绝并提示改用 --color-tone-map（Code={bo?.Code}）");
            var chroma = O("jpg"); chroma.ColorEngine = "engine"; chroma.Chroma = "4:2:0";
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(chroma, "o.jpg", false) == null,
                "jpg 的色度子采样已承接 ⇒ 不再拒绝");
            Check(FfmpegGui.Services.ColorMapping.ImageEncoderArgs.MapEnginePixFmt("jpg", chroma)?.Contains("yuvj420p") == true,
                "色度确实落到 -pix_fmt（jpg 4:2:0 ⇒ yuvj420p）");
            // 负控（**不得为了绿而放宽**）：libwebp 只接受 yuv420p/yuva420p/bgra ⇒ 4:4:4 必须仍然拒绝
            var chBad = O("webp"); chBad.ColorEngine = "engine"; chBad.Chroma = "4:4:4";
            var bchBad = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(chBad, "o.webp", false);
            Check(bchBad?.Code == "EncoderUnsupportedSetting",
                $"负控：libwebp 无 4:4:4 ⇒ 仍拒绝且 Code=EncoderUnsupportedSetting（{bchBad?.Text}）");
            // ── GainMap 接入色彩引擎（**2026-09-16 契约更新**）──────────────────────────
            // 旧契约：`--jpeg-gain-map true` 被路由层整条拦下（此处断言 BlockReason 含 "GainMap"）。
            // 新契约：**JPEG 输出 + GainMap 由色彩引擎决策并执行** ⇒ 路由层不再拦截；
            // 非 JPEG 的拒绝点下移到**规划层**（`ColorStrategyPlanning` 的
            // `GainMapRequested && !Format.SupportsGainMap ⇒ Reject`）⇒ 负控必须改看 Plan。
            var gm = O("jpg"); gm.ColorEngine = "engine"; gm.JpegGainMap = true;
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(gm, "o.jpg", false) == null,
                "jpg + JpegGainMap ⇒ 路由层不再拦截（GainMap 已接入引擎）");
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(gm, "o.jpg", false),
                "jpg + JpegGainMap ⇒ ShouldRoute 为真（确实交给引擎，而非仅“不报错”）");
            // 正向（走**真实装配**，与 CLI 同源）：HDR 源 + jpg + GainMap ⇒ 规划层不得 Reject。
            // 用 HDR 源是刻意的：GainMap 的主用途正是「HDR 底图 → SDR 底图 + 增益图」。
            var gmIt = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(gm, pq, out var whyGm);
            Check(gmIt != null && gmIt.GainMapRequested,
                $"jpg + JpegGainMap 装配意图并携带 GainMapRequested（reason={whyGm ?? "无"}）");
            var gmPlan = gmIt == null ? null : CE.Plan(gmIt);
            Check(gmPlan != null && gmPlan.Action != CA.Reject,
                $"jpg + JpegGainMap ⇒ 规划层不得 Reject（实为 {gmPlan?.Action}）");
            // 负控（不得为了绿而放宽）：非 JPEG 格式 + GainMap 仍必须被拒 + 给建议，
            // 且拒绝点是**规划层**而不是路由层（路由层现在放行一切 GainMap）。
            var gmPng = O("png"); gmPng.ColorEngine = "engine"; gmPng.JpegGainMap = true;
            var gmPngIt = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(gmPng, pq, out var whyGmP);
            Check(gmPngIt != null, $"png + JpegGainMap 仍可装配意图（reason={whyGmP ?? "无"}）");
            var gmPngPlan = gmPngIt == null ? null : CE.Plan(gmPngIt);
            Check(gmPngPlan != null && gmPngPlan.Action == CA.Reject && (gmPngPlan.Advice ?? "").Contains("AVIF"),
                $"负控：png + JpegGainMap ⇒ 规划层 Reject 并建议改 AVIF/JXL 或目标改 JPEG（{gmPngPlan?.Reason}）");
            // ── GainMap × 最长边几何缩放：**2026-09-18 起不再拦**（Part C 删除了那段死拦截）─────────
            // 【旧契约（已废）】`BlockReason.Code == "GeometryWithGainMap"`，负控「关掉最长边缩放 ⇒ 不拦」。
            // 【为什么废】那段拦截的前置条件在产品里**恒不成立**：`QueueProcessor.cs:421-470` 的预缩放中继
            //   （**所有后端共用**、在格式分发之前）已把超限输入换成缩过的临时件 ⇒ 引擎侧
            //   `BuildMaxDimensionScaleFilter` 恒返回 null ⇒ 判据恒假。实测删前/删后读数**完全相同**
            //   （exit 0、4621B、`images=2`/`iso min=0 max=2.3`/`mpf[1] soi=True`/探针 6/0）。
            // 【新契约】几何**不再**构成阻塞 ⇒ `BlockReason == null` **且** `ShouldRoute == true`。
            //   两条都断言：只断言"不报错"会让「路由说能走、执行体却不接」的形态溜过去。
            var gmGeo = O("jpg"); gmGeo.ColorEngine = "engine"; gmGeo.JpegGainMap = true;
            gmGeo.EnableMaxDimension = true; gmGeo.MaxDimension = 1280;
            var bgmGeo = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(gmGeo, "o.jpg", false);
            Check(bgmGeo == null,
                $"GainMap × 最长边缩放 ⇒ 路由层**不再**拦截（实得 Code={bgmGeo?.Code ?? "null"}；2026-09-18 Part C 删死拦截）");
            Check(FfmpegGui.Services.ColorMapping.ColorEngineRouter.ShouldRoute(gmGeo, "o.jpg", false),
                "GainMap × 最长边缩放 ⇒ ShouldRoute 为真（几何不再把该组合踢出引擎）");
            // 负控必须**仍有牙**：证明"几何不再拦"是**收窄**，不是"GainMap 一律放行"。
            // 只改**一个变量**（inputIsAnimated: false → true），其余与正例逐字相同 ——
            // 这样「把它改回 false」就必然转红，变异验证有一个干净的对照。
            // 为什么选动画这道门：删掉几何拦截后，`AnimatedInput` 是**唯一**还能把 GainMap 踢出引擎的
            //   路由级判据（实测：`anim_gif.gif` + `--jpeg-gain-map true` ⇒ 走专用管线）。
            //   ⇒ 这条负控正好钉住"剩下的那道门还在"。
            var gmGeoAnim = O("jpg"); gmGeoAnim.ColorEngine = "engine"; gmGeoAnim.JpegGainMap = true;
            gmGeoAnim.EnableMaxDimension = true; gmGeoAnim.MaxDimension = 1280;
            var bgmGeoAnim = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(gmGeoAnim, "o.jpg", true);
            Check(bgmGeoAnim?.Code == "AnimatedInput",
                $"负控：同一输入换成动画 ⇒ 仍须拦（Code={bgmGeoAnim?.Code}；证明放行的只是几何这一道门）");
            var ext = O("png"); ext.ColorEngine = "engine"; ext.EncoderBackend = FfmpegGui.Services.EncoderBackend.Cjxl;
            var bExt = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(ext, "o.png", false);
            Check(bExt?.Code == "ExternalBackend",
                $"用户选了外部编码器 ⇒ 引擎不抢决断权（Code={bExt?.Code}）");

            // ══════════════════════════════════════════════════════════════════════════════════
            // 6) **S2：路由拦截的结构化**（规划 §5-D；`BlockReason` 由 `string?` 改为 `EngineBlock?`）
            // ══════════════════════════════════════════════════════════════════════════════════
            // 要钉住的契约：
            //   ① **每个 Code 至少一条正向断言**（构造对应场景 ⇒ 断言 `Block.Code`，**绝不匹配 Text**）；
            //   ② 引擎可走时 `Block` 必须为 **null**（负控，代表格式）；
            //   ③ 语义**不得**回退成"任务做不了"：`BlockReason` 返回的是 `EngineBlock`，**不是** `ColorVerdict`
            //      —— 这条由**类型系统**保证（编译期），此处只需守住 Code 词表。
            //   ④ Code 词表**逐条对应** `BlockReason`/`UnconsumedOutputSettings` 的现有判据（不多不少）。

            // 6a) `OptionsNull`：防御性分支（实际不可达，但既然存在就必须有 Code，否则"逐条对应"有缺口）。
            var bNull = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(null, "o.png", false);
            Check(bNull?.Code == "OptionsNull", $"options 为空 ⇒ Code=OptionsNull（{bNull?.Text}）");

            // 6b) `AnimationScaleUnsupported`：动画缩放（原分支：UnconsumedOutputSettings 的 bad.Add("动画缩放")）。
            var animScale = O("png"); animScale.ColorEngine = "engine"; animScale.AnimationScaleW = 1920;
            var bAnimScale = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(animScale, "o.png", false);
            Check(bAnimScale?.Code == "AnimationScaleUnsupported",
                $"动画缩放未承接 ⇒ Code=AnimationScaleUnsupported（{bAnimScale?.Text}）");

            // 6c) `ProgressiveJpeg`：ffmpeg 的 mjpeg 无渐进能力（原分支：JpegProgressiveId != 0）。
            var prog = O("jpg"); prog.ColorEngine = "engine"; prog.JpegProgressiveId = 1;
            var bProg = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(prog, "o.jpg", false);
            Check(bProg?.Code == "ProgressiveJpeg",
                $"JPEG 渐进未承接 ⇒ Code=ProgressiveJpeg（{bProg?.Text}）");

            // 6d) 多项同时命中 ⇒ Code 取**列表首项**（= 文案里第一个原因），顺序即判据的固定顺序。
            //     ⚠ 这是**确定性契约**（GUI 要按 Code 分派解释），不是"随便取一个"。
            var multi = O("jpg"); multi.ColorEngine = "engine";
            multi.AnimationScaleW = 1920; multi.TonemapCurve = "reinhard"; multi.JpegProgressiveId = 1;
            var bMulti = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(multi, "o.jpg", false);
            Check(bMulti?.Code == "AnimationScaleUnsupported",
                $"多因同时命中 ⇒ Code 取首项 AnimationScaleUnsupported（Code={bMulti?.Code}）");
            // 文案锁（**不是**行为判据）：多因场景的 Text 必须与改动前的拼串**逐字相同**
            // （「、」分隔、顺序一致）。这里用**严格相等**而不是 Contains —— 后者才是"匹配自由文本"。
            Check(bMulti?.Text == "引擎编码出口尚未承接这些输出参数：动画缩放、"
                  + "旧 --tonemap-curve=reinhard（请改用 --color-tone-map）、"
                  + "JPEG 渐进（ffmpeg 的 mjpeg 编码器无此能力；请改用 cjpegli 后端，或把该项设回自动）",
                $"多因场景的 Text 与改动前逐字相同（实得「{bMulti?.Text}」）");
            // 6d-2) ⚠ **`Alternatives` 必须跨所有命中的判据聚合**（不是只给首项那条的替代）。
            //   这是"`Code` 保持单值"的**前提**：team-lead 裁定 ① 的理由正是"GUI 一键修正要的是
            //   **全部可行动替代**，而 `Alternatives` 是列表"。只给首项 ⇒ 那个理由就不成立。
            //   本用例同时命中 3 条判据 ⇒ 必须有 3 条替代，且顺序与判据顺序一致。
            var mAlts = bMulti?.Alternatives
                        ?? System.Array.Empty<FfmpegGui.Services.ColorMapping.ColorAlternative>();
            var mVals = new StringBuilder();
            for (int i = 0; i < mAlts.Count; i++) mVals.Append(mAlts[i].Value).Append(' ');
            Check(mVals.ToString() == "animation-scale-w color-tone-map jpeg-progressive ",
                $"多因命中的 Alternatives 必须**跨全部判据聚合**（实得「{mVals}」）");

            // 6e) `Alternatives`：**只在代码本来就知道替代时填**。填了的必须有，没填的必须为空
            //     —— 两个方向都断言，否则"哪天有人随手补一个编造的替代"无人发现。
            // ⚠ 取值用**空安全**投影（`Block` 为 null 时给 `(0, default, "")`）：变异让某条判据恒假时
            //   本段必须**转红**而不是抛 NullReference（抛异常会把"哪条断言失败"掩盖掉）。
            (int n, FfmpegGui.Services.ColorMapping.AlternativeKind kind, string value) Alt1(
                FfmpegGui.Services.ColorMapping.EngineBlock? b)
                => b != null && b.Alternatives.Count > 0
                   ? (b.Alternatives.Count, b.Alternatives[0].Kind, b.Alternatives[0].Value)
                   : (0, default, "");
            var ALT = FfmpegGui.Services.ColorMapping.AlternativeKind.Option;
            Check(Alt1(bExt) == (1, ALT, "encoder"),
                $"ExternalBackend 给出替代「改 -e Ffmpeg」（实得 {Alt1(bExt)}）");
            // ⚠ 2026-09-18：`GeometryWithGainMap` **已不再被生产**（Part C 删掉那段死拦截）
            //   ⇒ 该组合不再有 `Block`，也就无从谈"替代项"。这里保留一条**反向**断言：
            //   若哪天有人把拦截加回去，`Alt1(bgmGeo)` 会变成 `(1, Option, max-dimension-enabled)`
            //   ⇒ 本条转红（等于给 Part C 的删除上了一把锁）。
            Check(Alt1(bgmGeo).n == 0,
                $"GeometryWithGainMap 已不再生产 ⇒ 该组合无替代项（实得 {Alt1(bgmGeo)}）");
            Check(Alt1(bo) == (1, ALT, "color-tone-map"),
                $"LegacyTonemapCurve 给出替代「改用 --color-tone-map」（实得 {Alt1(bo)}）");
            Check(Alt1(bProg) == (1, ALT, "jpeg-progressive"),
                $"ProgressiveJpeg 给出替代「把 --jpeg-progressive 设回自动」（实得 {Alt1(bProg)}）");
            Check(Alt1(bAnimScale) == (1, ALT, "animation-scale-w"),
                $"AnimationScaleUnsupported 给出替代「把 --animation-scale-w 设回 0」（实得 {Alt1(bAnimScale)}）");
            // 反向：**不该编替代**的三处必须留空（各自的理由见 Router 内的注释）。
            Check(Alt1(bppm).n == 0 && Alt1(bAnim).n == 0 && Alt1(bchBad).n == 0 && Alt1(bNull).n == 0,
                "FormatNotSupported / AnimatedInput / EncoderUnsupportedSetting / OptionsNull "
                + $"⇒ Alternatives 必须为空（实得 {Alt1(bppm).n}/{Alt1(bAnim).n}/{Alt1(bchBad).n}/{Alt1(bNull).n}）");

            // 6f) **负控**：引擎可走的代表格式 ⇒ `Block` 必须为 **null**（漏一个格式就是"假路由"）。
            var negBad = new StringBuilder();
            foreach (var nf in new[] { "png", "webp", "tif", "gif", "jpg", "jxl", "avif" })
            {
                var okF = O(nf); okF.ColorEngine = "engine";
                var bF = FfmpegGui.Services.ColorMapping.ColorEngineRouter.BlockReason(okF, "o." + nf, false);
                if (bF != null) negBad.Append($"{nf}={bF.Code} ");
            }
            Check(negBad.Length == 0,
                $"负控：引擎可走的代表格式 Block 必须为 null（非空=[{negBad}]）");

            // 7) **P1-3 枚举序锁**（2026-10-04 补）────────────────────────────────────────
            // 病因：RAW 源描述符的置信度曾**恰好等于**闸门阈值（`CicpTag == MinConfidenceForMapping`），
            // 靠 `>=` 才放行 ⇒ 只要有人往枚举里插一个成员、或把闸门抬到 `NamedIcc`，这条刚修好的
            // RAW 路径就**零告警地退回「直通」**（像素一个都不动，却仍标目标域）。
            // 现修法：RAW 分支**显式**把置信度抬到 `NamedIcc`（见 `ColorIntentFactory` 的 `ColorSourceDecl*` 分支）。
            // 下面三条把「枚举序不可随意插成员」钉死，并锁住「显式抬高」这件事本身（不再依赖枚举巧合）。
            var minConf = FfmpegGui.Services.ColorMapping.EquivalenceTolerances.MinConfidenceForMapping;
            Check(minConf == FfmpegGui.Services.ColorMapping.DescriptorConfidence.CicpTag,
                $"P1-3 闸门阈值仍是 CicpTag（实 {minConf}）—— 若有意抬高，须同步确认 RAW 源描述符仍 >= 阈值");
            Check((int)FfmpegGui.Services.ColorMapping.DescriptorConfidence.CicpTag
                  < (int)FfmpegGui.Services.ColorMapping.DescriptorConfidence.NamedIcc,
                "P1-3 枚举序不变：CicpTag("
                + $"{(int)FfmpegGui.Services.ColorMapping.DescriptorConfidence.CicpTag}) < NamedIcc("
                + $"{(int)FfmpegGui.Services.ColorMapping.DescriptorConfidence.NamedIcc})");
            var rawDeclO = O("tiff");
            rawDeclO.ColorSourceDeclPrimaries = "bt2020";
            rawDeclO.ColorSourceDeclTrc = "linear";
            // ⚠⚠ 输入路径必须是 **RAW**（用真素材，避免探测抛错）：`ColorIntentFactory` 的「自产中间件」
            //   分支自 2026-10-04 审查起**只认 RAW 与 Ultra HDR 解码**两条路 —— 用 png 路径会让该分支
            //   不触发 ⇒ 下面这条 P1-3 锁**假红**（实测：收紧后 `probe:wire` exit=1）。
            //   ⇒ 这里改用 `tests/output/raw_samples/` 下的真 ARW（`RawService.IsRawFile` 是扩展名判据）。
            const string rawDeclPath = "tests/output/raw_samples/Sony_ILCE7S.ARW";
            var iRawDecl = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(rawDeclO, rawDeclPath, out var rRawDecl);
            Check(iRawDecl?.Source != null
                  && iRawDecl.Source!.Confidence == FfmpegGui.Services.ColorMapping.DescriptorConfidence.NamedIcc
                  && iRawDecl.Source.Confidence >= minConf,
                $"P1-3 RAW 源描述符置信度**显式** NamedIcc（实 {iRawDecl?.Source?.Confidence}，闸门 {minConf}）"
                + $"⇒ 不依赖「恰好等于」（reason={rRawDecl ?? "无"}）");

            // 8) **回归锁（2026-10-04）**：`ColorMatrix` 是**输入声明**、不是目标轴 ——
            //    设了它**不得**吃掉 `ColorSpace` 目标。
            //    曾踩：把「用户是否选了目标」的值派生判据写成含 `ColorMatrix` 的 `HasExplicitColorParams`，
            //    而下游判据是**互斥**形状（`!advanced && ColorSpace…`）⇒ `--color-matrix bt709
            //    --color-space sRGB` 会把 ColorSpace 目标**整条丢掉**。
            //    实测后果：HDR(PQ) 源 → png 变 `决策：None`、产物仍 `smpte2084/bt2020`（用户要的 sRGB 被静默丢弃）。
            //    ⇒ 锁住「矩阵在位 + 指定色空间 ⇒ 目标仍成立」。
            var matO = O("png", "sRGB");
            matO.ColorMatrix = "bt709";
            var iMat = FfmpegGui.Services.ColorMapping.ColorIntentFactory.FromOptions(matO, sdr, out var rMat);
            Check(iMat?.Target != null && iMat.TargetExplicit,
                $"ColorMatrix 不得吃掉 ColorSpace 目标（Target={(iMat?.Target == null ? "null" : iMat.Target.Name)}"
                + $"，TargetExplicit={iMat?.TargetExplicit}，reason={rMat ?? "无"}）");

            _ = R;
        }
    }
}
