<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- 主项目 TFM，升级 .NET 11 时改为 net11.0 -->
    <MainTfm>net10.0</MainTfm>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FfmpegGui\FfmpegGui.csproj" />
  </ItemGroup>
</Project>